/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateCryptoDepositRequest,
    CreateCryptoDepositRequestFromJSON,
    CreateCryptoDepositRequestToJSON,
} from '../models/CreateCryptoDepositRequest';
import {
    type CryptoDeposit,
    CryptoDepositFromJSON,
    CryptoDepositToJSON,
} from '../models/CryptoDeposit';
import {
    type ListDeposits200Response,
    ListDeposits200ResponseFromJSON,
    ListDeposits200ResponseToJSON,
} from '../models/ListDeposits200Response';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type SpendingLimit,
    SpendingLimitFromJSON,
    SpendingLimitToJSON,
} from '../models/SpendingLimit';
import {
    type UpdateSpendingLimitRequest,
    UpdateSpendingLimitRequestFromJSON,
    UpdateSpendingLimitRequestToJSON,
} from '../models/UpdateSpendingLimitRequest';

export interface CreateCryptoDepositOperationRequest {
    createCryptoDepositRequest: CreateCryptoDepositRequest;
}

export interface GetDepositRequest {
    id: string;
}

export interface UpdateSpendingLimitOperationRequest {
    updateSpendingLimitRequest: UpdateSpendingLimitRequest;
}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCryptoDeposit without sending the request
     */
    async createCryptoDepositRequestOpts(requestParameters: CreateCryptoDepositOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createCryptoDepositRequest'] == null) {
            throw new runtime.RequiredError(
                'createCryptoDepositRequest',
                'Required parameter "createCryptoDepositRequest" was null or undefined when calling createCryptoDeposit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/billing/deposits/crypto`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCryptoDepositRequestToJSON(requestParameters['createCryptoDepositRequest']),
        };
    }

    /**
     * Creates a deposit intent and returns the payment address and the exact token amount to send. Requires the `billing:write` scope; any member of the organization may add funds. Send the exact `pay_amount` of `asset` on `chain` and no other network — funds sent on a different network are not detected automatically. Returns 404 when stablecoin deposits are not enabled for this deployment. 
     * Create a stablecoin deposit
     */
    async createCryptoDepositRaw(requestParameters: CreateCryptoDepositOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CryptoDeposit>> {
        const requestOptions = await this.createCryptoDepositRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CryptoDepositFromJSON(jsonValue));
    }

    /**
     * Creates a deposit intent and returns the payment address and the exact token amount to send. Requires the `billing:write` scope; any member of the organization may add funds. Send the exact `pay_amount` of `asset` on `chain` and no other network — funds sent on a different network are not detected automatically. Returns 404 when stablecoin deposits are not enabled for this deployment. 
     * Create a stablecoin deposit
     */
    async createCryptoDeposit(requestParameters: CreateCryptoDepositOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CryptoDeposit> {
        const response = await this.createCryptoDepositRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDeposit without sending the request
     */
    async getDepositRequestOpts(requestParameters: GetDepositRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDeposit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/billing/deposits/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single deposit belonging to the caller\'s organization. Requires the `billing:read` scope. A deposit belonging to another organization returns the same `404 deposit-not-found` as one that does not exist — deliberately, so this endpoint cannot be used to test whether a deposit id is real. Also 404 when stablecoin deposits are not enabled for this deployment. 
     * Get one stablecoin deposit
     */
    async getDepositRaw(requestParameters: GetDepositRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CryptoDeposit>> {
        const requestOptions = await this.getDepositRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CryptoDepositFromJSON(jsonValue));
    }

    /**
     * Returns a single deposit belonging to the caller\'s organization. Requires the `billing:read` scope. A deposit belonging to another organization returns the same `404 deposit-not-found` as one that does not exist — deliberately, so this endpoint cannot be used to test whether a deposit id is real. Also 404 when stablecoin deposits are not enabled for this deployment. 
     * Get one stablecoin deposit
     */
    async getDeposit(requestParameters: GetDepositRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CryptoDeposit> {
        const response = await this.getDepositRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSpendingLimit without sending the request
     */
    async getSpendingLimitRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/billing/spending-limit`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the organization\'s monthly spending limit and opt-in daily spend cap, with the current month and day spend. Requires the `billing:read` scope. Returns 404 when no limit is configured. 
     * Get the org spending limit
     */
    async getSpendingLimitRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SpendingLimit>> {
        const requestOptions = await this.getSpendingLimitRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpendingLimitFromJSON(jsonValue));
    }

    /**
     * Returns the organization\'s monthly spending limit and opt-in daily spend cap, with the current month and day spend. Requires the `billing:read` scope. Returns 404 when no limit is configured. 
     * Get the org spending limit
     */
    async getSpendingLimit(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SpendingLimit> {
        const response = await this.getSpendingLimitRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDeposits without sending the request
     */
    async listDepositsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/billing/deposits`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the organization\'s stablecoin deposits, newest first, capped at 50. Requires the `billing:read` scope. The organization is taken from the authenticated API key, never from a parameter. Returns 404 when stablecoin deposits are not enabled for this deployment. 
     * List stablecoin deposits
     */
    async listDepositsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDeposits200Response>> {
        const requestOptions = await this.listDepositsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDeposits200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the organization\'s stablecoin deposits, newest first, capped at 50. Requires the `billing:read` scope. The organization is taken from the authenticated API key, never from a parameter. Returns 404 when stablecoin deposits are not enabled for this deployment. 
     * List stablecoin deposits
     */
    async listDeposits(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDeposits200Response> {
        const response = await this.listDepositsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSpendingLimit without sending the request
     */
    async updateSpendingLimitRequestOpts(requestParameters: UpdateSpendingLimitOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateSpendingLimitRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSpendingLimitRequest',
                'Required parameter "updateSpendingLimitRequest" was null or undefined when calling updateSpendingLimit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/billing/spending-limit`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSpendingLimitRequestToJSON(requestParameters['updateSpendingLimitRequest']),
        };
    }

    /**
     * Sets the monthly spending limit and optionally sets or clears the opt-in daily spend cap. Requires the `billing:write` scope AND org-admin privileges (a non-admin member gets 403). `daily_limit_dollars` uses pointer semantics: omit to leave the cap unchanged, 0 to clear it, a positive value to set it. 
     * Set the org spending limit
     */
    async updateSpendingLimitRaw(requestParameters: UpdateSpendingLimitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SpendingLimit>> {
        const requestOptions = await this.updateSpendingLimitRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpendingLimitFromJSON(jsonValue));
    }

    /**
     * Sets the monthly spending limit and optionally sets or clears the opt-in daily spend cap. Requires the `billing:write` scope AND org-admin privileges (a non-admin member gets 403). `daily_limit_dollars` uses pointer semantics: omit to leave the cap unchanged, 0 to clear it, a positive value to set it. 
     * Set the org spending limit
     */
    async updateSpendingLimit(requestParameters: UpdateSpendingLimitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SpendingLimit> {
        const response = await this.updateSpendingLimitRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
