/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CommunityEarnings,
    CommunityEarningsFromJSON,
    CommunityEarningsToJSON,
} from '../models/CommunityEarnings';
import {
    type CommunityMachineDelistResult,
    CommunityMachineDelistResultFromJSON,
    CommunityMachineDelistResultToJSON,
} from '../models/CommunityMachineDelistResult';
import {
    type CommunityMachineRegistration,
    CommunityMachineRegistrationFromJSON,
    CommunityMachineRegistrationToJSON,
} from '../models/CommunityMachineRegistration';
import {
    type CommunitySupplier,
    CommunitySupplierFromJSON,
    CommunitySupplierToJSON,
} from '../models/CommunitySupplier';
import {
    type ListCommunityMachines200Response,
    ListCommunityMachines200ResponseFromJSON,
    ListCommunityMachines200ResponseToJSON,
} from '../models/ListCommunityMachines200Response';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type RegisterCommunityMachineRequest,
    RegisterCommunityMachineRequestFromJSON,
    RegisterCommunityMachineRequestToJSON,
} from '../models/RegisterCommunityMachineRequest';
import {
    type SupplierMachineView,
    SupplierMachineViewFromJSON,
    SupplierMachineViewToJSON,
} from '../models/SupplierMachineView';
import {
    type UpdateCommunityMachineRequest,
    UpdateCommunityMachineRequestFromJSON,
    UpdateCommunityMachineRequestToJSON,
} from '../models/UpdateCommunityMachineRequest';

export interface DelistCommunityMachineRequest {
    id: string;
}

export interface EnableCommunitySupplierRequest {
    idempotencyKey?: string;
}

export interface GetCommunityEarningsRequest {
    limit?: number;
}

export interface GetCommunityMachineRequest {
    id: string;
}

export interface ReclaimCommunityMachineRequest {
    id: string;
}

export interface RegisterCommunityMachineOperationRequest {
    idempotencyKey?: string;
    registerCommunityMachineRequest?: RegisterCommunityMachineRequest;
}

export interface UpdateCommunityMachineOperationRequest {
    id: string;
    updateCommunityMachineRequest: UpdateCommunityMachineRequest;
}

/**
 * 
 */
export class CommunityApi extends runtime.BaseAPI {

    /**
     * Creates request options for delistCommunityMachine without sending the request
     */
    async delistCommunityMachineRequestOpts(requestParameters: DelistCommunityMachineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling delistCommunityMachine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/machines/{id}/delist`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes a machine the caller\'s org owns from supply (ONBD-04). Drain-not-kill: an occupied machine becomes `draining` (its customer rental keeps running until it ends naturally) and an idle machine becomes `delisted`. The endpoint never force-terminates a running rental. A missing or cross-org machine returns 404 with an indistinguishable body so existence never leaks across orgs. Requires the `community` scope (or `full_access`).
     * Delist a Community Cloud machine
     */
    async delistCommunityMachineRaw(requestParameters: DelistCommunityMachineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunityMachineDelistResult>> {
        const requestOptions = await this.delistCommunityMachineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunityMachineDelistResultFromJSON(jsonValue));
    }

    /**
     * Removes a machine the caller\'s org owns from supply (ONBD-04). Drain-not-kill: an occupied machine becomes `draining` (its customer rental keeps running until it ends naturally) and an idle machine becomes `delisted`. The endpoint never force-terminates a running rental. A missing or cross-org machine returns 404 with an indistinguishable body so existence never leaks across orgs. Requires the `community` scope (or `full_access`).
     * Delist a Community Cloud machine
     */
    async delistCommunityMachine(requestParameters: DelistCommunityMachineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunityMachineDelistResult> {
        const response = await this.delistCommunityMachineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for enableCommunitySupplier without sending the request
     */
    async enableCommunitySupplierRequestOpts(requestParameters: EnableCommunitySupplierRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/suppliers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Idempotently enables the Community Cloud supplier role for the organization the API key belongs to. A repeat call is a no-op that returns the same supplier record (200, not 201). Requires the `community` scope (or `full_access`).
     * Enable the Community Cloud supplier role
     */
    async enableCommunitySupplierRaw(requestParameters: EnableCommunitySupplierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunitySupplier>> {
        const requestOptions = await this.enableCommunitySupplierRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunitySupplierFromJSON(jsonValue));
    }

    /**
     * Idempotently enables the Community Cloud supplier role for the organization the API key belongs to. A repeat call is a no-op that returns the same supplier record (200, not 201). Requires the `community` scope (or `full_access`).
     * Enable the Community Cloud supplier role
     */
    async enableCommunitySupplier(requestParameters: EnableCommunitySupplierRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunitySupplier> {
        const response = await this.enableCommunitySupplierRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommunityEarnings without sending the request
     */
    async getCommunityEarningsRequestOpts(requestParameters: GetCommunityEarningsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/earnings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the caller org\'s supplier earnings — lifetime accrued and unpaid totals in cents plus recent ledger entries, newest first. An optional `limit` caps the ledger rows (server-clamped). Requires the `community` scope (read).
     * Get your Community Cloud earnings
     */
    async getCommunityEarningsRaw(requestParameters: GetCommunityEarningsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunityEarnings>> {
        const requestOptions = await this.getCommunityEarningsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunityEarningsFromJSON(jsonValue));
    }

    /**
     * Returns the caller org\'s supplier earnings — lifetime accrued and unpaid totals in cents plus recent ledger entries, newest first. An optional `limit` caps the ledger rows (server-clamped). Requires the `community` scope (read).
     * Get your Community Cloud earnings
     */
    async getCommunityEarnings(requestParameters: GetCommunityEarningsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunityEarnings> {
        const response = await this.getCommunityEarningsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommunityMachine without sending the request
     */
    async getCommunityMachineRequestOpts(requestParameters: GetCommunityMachineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCommunityMachine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/machines/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one machine the caller\'s org owns, as a supplier-facing view (`occupied`/`online` projections — the renting customer\'s instance id is never exposed). A missing or cross-org machine returns 404 with an indistinguishable body. Requires the `community` scope (read).
     * Get one of your Community Cloud machines
     */
    async getCommunityMachineRaw(requestParameters: GetCommunityMachineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierMachineView>> {
        const requestOptions = await this.getCommunityMachineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierMachineViewFromJSON(jsonValue));
    }

    /**
     * Returns one machine the caller\'s org owns, as a supplier-facing view (`occupied`/`online` projections — the renting customer\'s instance id is never exposed). A missing or cross-org machine returns 404 with an indistinguishable body. Requires the `community` scope (read).
     * Get one of your Community Cloud machines
     */
    async getCommunityMachine(requestParameters: GetCommunityMachineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierMachineView> {
        const response = await this.getCommunityMachineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommunitySupplierMe without sending the request
     */
    async getCommunitySupplierMeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/suppliers/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the community supplier record for the organization the API key belongs to, or 404 `not-a-supplier` when the role has not been enabled. Requires the `community` scope (read).
     * Get the caller\'s Community Cloud supplier
     */
    async getCommunitySupplierMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunitySupplier>> {
        const requestOptions = await this.getCommunitySupplierMeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunitySupplierFromJSON(jsonValue));
    }

    /**
     * Returns the community supplier record for the organization the API key belongs to, or 404 `not-a-supplier` when the role has not been enabled. Requires the `community` scope (read).
     * Get the caller\'s Community Cloud supplier
     */
    async getCommunitySupplierMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunitySupplier> {
        const response = await this.getCommunitySupplierMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCommunityMachines without sending the request
     */
    async listCommunityMachinesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/machines`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns every machine the caller\'s org has registered, newest first, as supplier-facing views (`occupied`/`online` projections — the renting customer\'s instance id is never exposed). Requires the `community` scope (read).
     * List your Community Cloud machines
     */
    async listCommunityMachinesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCommunityMachines200Response>> {
        const requestOptions = await this.listCommunityMachinesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCommunityMachines200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns every machine the caller\'s org has registered, newest first, as supplier-facing views (`occupied`/`online` projections — the renting customer\'s instance id is never exposed). Requires the `community` scope (read).
     * List your Community Cloud machines
     */
    async listCommunityMachines(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCommunityMachines200Response> {
        const response = await this.listCommunityMachinesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reclaimCommunityMachine without sending the request
     */
    async reclaimCommunityMachineRequestOpts(requestParameters: ReclaimCommunityMachineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reclaimCommunityMachine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/machines/{id}/reclaim`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The spot interruption mechanic — the supplier takes back a machine they listed as interruptible (tier=spot). Drain-not-kill: an occupied machine becomes `draining` (the renter gets the grace window, surfaced to the spot router as a preemption warning) and an idle machine becomes `delisted`. An on-demand machine cannot be reclaimed (409 `machine-not-spot`) — use delist instead. Requires the `community` scope (or `full_access`).
     * Reclaim a spot-tier Community Cloud machine
     */
    async reclaimCommunityMachineRaw(requestParameters: ReclaimCommunityMachineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunityMachineDelistResult>> {
        const requestOptions = await this.reclaimCommunityMachineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunityMachineDelistResultFromJSON(jsonValue));
    }

    /**
     * The spot interruption mechanic — the supplier takes back a machine they listed as interruptible (tier=spot). Drain-not-kill: an occupied machine becomes `draining` (the renter gets the grace window, surfaced to the spot router as a preemption warning) and an idle machine becomes `delisted`. An on-demand machine cannot be reclaimed (409 `machine-not-spot`) — use delist instead. Requires the `community` scope (or `full_access`).
     * Reclaim a spot-tier Community Cloud machine
     */
    async reclaimCommunityMachine(requestParameters: ReclaimCommunityMachineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunityMachineDelistResult> {
        const response = await this.reclaimCommunityMachineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerCommunityMachine without sending the request
     */
    async registerCommunityMachineRequestOpts(requestParameters: RegisterCommunityMachineOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/machines`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterCommunityMachineRequestToJSON(requestParameters['registerCommunityMachineRequest']),
        };
    }

    /**
     * Registers a self-declared machine under the caller\'s community supplier and mints a one-time enrollment token. All spec fields are optional — an empty body registers a placeholder in `pending_verification`. The `enrollment_token` is shown exactly once and never returned again. Requires the `community` scope (or `full_access`).
     * Register a Community Cloud machine
     */
    async registerCommunityMachineRaw(requestParameters: RegisterCommunityMachineOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunityMachineRegistration>> {
        const requestOptions = await this.registerCommunityMachineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunityMachineRegistrationFromJSON(jsonValue));
    }

    /**
     * Registers a self-declared machine under the caller\'s community supplier and mints a one-time enrollment token. All spec fields are optional — an empty body registers a placeholder in `pending_verification`. The `enrollment_token` is shown exactly once and never returned again. Requires the `community` scope (or `full_access`).
     * Register a Community Cloud machine
     */
    async registerCommunityMachine(requestParameters: RegisterCommunityMachineOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunityMachineRegistration> {
        const response = await this.registerCommunityMachineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCommunityMachine without sending the request
     */
    async updateCommunityMachineRequestOpts(requestParameters: UpdateCommunityMachineOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCommunityMachine().'
            );
        }

        if (requestParameters['updateCommunityMachineRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCommunityMachineRequest',
                'Required parameter "updateCommunityMachineRequest" was null or undefined when calling updateCommunityMachine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/community/machines/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCommunityMachineRequestToJSON(requestParameters['updateCommunityMachineRequest']),
        };
    }

    /**
     * Sets the machine\'s hourly price. `price_per_hour` is the WHOLE-MACHINE rate (never per-GPU). Prices below the platform floor are rejected with a `price-below-floor` problem carrying the concrete `floor_per_hour` extension member. A price change never affects an in-flight rental (its rate was snapshotted at provision); the catalog reprices on the next poll. Requires the `community` scope (or `full_access`).
     * Update a Community Cloud machine\'s price
     */
    async updateCommunityMachineRaw(requestParameters: UpdateCommunityMachineOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierMachineView>> {
        const requestOptions = await this.updateCommunityMachineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierMachineViewFromJSON(jsonValue));
    }

    /**
     * Sets the machine\'s hourly price. `price_per_hour` is the WHOLE-MACHINE rate (never per-GPU). Prices below the platform floor are rejected with a `price-below-floor` problem carrying the concrete `floor_per_hour` extension member. A price change never affects an in-flight rental (its rate was snapshotted at provision); the catalog reprices on the next poll. Requires the `community` scope (or `full_access`).
     * Update a Community Cloud machine\'s price
     */
    async updateCommunityMachine(requestParameters: UpdateCommunityMachineOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierMachineView> {
        const response = await this.updateCommunityMachineRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
