/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Environments,
    EnvironmentsFromJSON,
    EnvironmentsToJSON,
} from '../models/Environments';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

/**
 * 
 */
export class EnvironmentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getEnvironments without sending the request
     */
    async getEnvironmentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/environments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The server-controlled launch environment catalog — the certified framework roster, the selectable version(s) per framework (the version picker), the \"What\'s included\" software lists, and the raw-VM OS catalog. These are exactly the values accepted by the `environment` field of POST /v1/instances.
     * List launch environments (no auth required)
     */
    async getEnvironmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Environments>> {
        const requestOptions = await this.getEnvironmentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvironmentsFromJSON(jsonValue));
    }

    /**
     * The server-controlled launch environment catalog — the certified framework roster, the selectable version(s) per framework (the version picker), the \"What\'s included\" software lists, and the raw-VM OS catalog. These are exactly the values accepted by the `environment` field of POST /v1/instances.
     * List launch environments (no auth required)
     */
    async getEnvironments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Environments> {
        const response = await this.getEnvironmentsRaw(initOverrides);
        return await response.value();
    }

}
