/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateFineTuningJobRequest,
    CreateFineTuningJobRequestFromJSON,
    CreateFineTuningJobRequestToJSON,
} from '../models/CreateFineTuningJobRequest';
import {
    type FileObject,
    FileObjectFromJSON,
    FileObjectToJSON,
} from '../models/FileObject';
import {
    type FineTuningJob,
    FineTuningJobFromJSON,
    FineTuningJobToJSON,
} from '../models/FineTuningJob';
import {
    type FineTuningJobEventList,
    FineTuningJobEventListFromJSON,
    FineTuningJobEventListToJSON,
} from '../models/FineTuningJobEventList';
import {
    type FineTuningJobList,
    FineTuningJobListFromJSON,
    FineTuningJobListToJSON,
} from '../models/FineTuningJobList';
import {
    type OpenAIErrorEnvelope,
    OpenAIErrorEnvelopeFromJSON,
    OpenAIErrorEnvelopeToJSON,
} from '../models/OpenAIErrorEnvelope';

export interface CancelFineTuningJobRequest {
    id: string;
}

export interface CreateFileRequest {
    purpose: CreateFilePurposeEnum;
    file: Blob;
}

export interface CreateFineTuningJobOperationRequest {
    createFineTuningJobRequest: CreateFineTuningJobRequest;
}

export interface GetFineTuningJobRequest {
    id: string;
}

export interface ListFineTuningJobEventsRequest {
    id: string;
    after?: string;
    limit?: number;
}

export interface ListFineTuningJobsRequest {
    after?: string;
    limit?: number;
}

export interface RetrieveFileRequest {
    id: string;
}

/**
 * 
 */
export class FineTuningApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelFineTuningJob without sending the request
     */
    async cancelFineTuningJobRequestOpts(requestParameters: CancelFineTuningJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelFineTuningJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fine_tuning/jobs/{id}/cancel`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel a fine-tuning job (OpenAI-compatible)
     */
    async cancelFineTuningJobRaw(requestParameters: CancelFineTuningJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FineTuningJob>> {
        const requestOptions = await this.cancelFineTuningJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FineTuningJobFromJSON(jsonValue));
    }

    /**
     * Cancel a fine-tuning job (OpenAI-compatible)
     */
    async cancelFineTuningJob(requestParameters: CancelFineTuningJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FineTuningJob> {
        const response = await this.cancelFineTuningJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createFile without sending the request
     */
    async createFileRequestOpts(requestParameters: CreateFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['purpose'] == null) {
            throw new runtime.RequiredError(
                'purpose',
                'Required parameter "purpose" was null or undefined when calling createFile().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling createFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['purpose'] != null) {
            formParams.append('purpose', requestParameters['purpose'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/files`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Upload a fine-tuning dataset file (OpenAI-compatible)
     */
    async createFileRaw(requestParameters: CreateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileObject>> {
        const requestOptions = await this.createFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileObjectFromJSON(jsonValue));
    }

    /**
     * Upload a fine-tuning dataset file (OpenAI-compatible)
     */
    async createFile(requestParameters: CreateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileObject> {
        const response = await this.createFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createFineTuningJob without sending the request
     */
    async createFineTuningJobRequestOpts(requestParameters: CreateFineTuningJobOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createFineTuningJobRequest'] == null) {
            throw new runtime.RequiredError(
                'createFineTuningJobRequest',
                'Required parameter "createFineTuningJobRequest" was null or undefined when calling createFineTuningJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fine_tuning/jobs`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFineTuningJobRequestToJSON(requestParameters['createFineTuningJobRequest']),
        };
    }

    /**
     * Create a managed fine-tuning job (OpenAI-compatible)
     */
    async createFineTuningJobRaw(requestParameters: CreateFineTuningJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FineTuningJob>> {
        const requestOptions = await this.createFineTuningJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FineTuningJobFromJSON(jsonValue));
    }

    /**
     * Create a managed fine-tuning job (OpenAI-compatible)
     */
    async createFineTuningJob(requestParameters: CreateFineTuningJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FineTuningJob> {
        const response = await this.createFineTuningJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFineTuningJob without sending the request
     */
    async getFineTuningJobRequestOpts(requestParameters: GetFineTuningJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFineTuningJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fine_tuning/jobs/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a fine-tuning job (OpenAI-compatible)
     */
    async getFineTuningJobRaw(requestParameters: GetFineTuningJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FineTuningJob>> {
        const requestOptions = await this.getFineTuningJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FineTuningJobFromJSON(jsonValue));
    }

    /**
     * Retrieve a fine-tuning job (OpenAI-compatible)
     */
    async getFineTuningJob(requestParameters: GetFineTuningJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FineTuningJob> {
        const response = await this.getFineTuningJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFineTuningJobEvents without sending the request
     */
    async listFineTuningJobEventsRequestOpts(requestParameters: ListFineTuningJobEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listFineTuningJobEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fine_tuning/jobs/{id}/events`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List fine-tuning job events (OpenAI-compatible)
     */
    async listFineTuningJobEventsRaw(requestParameters: ListFineTuningJobEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FineTuningJobEventList>> {
        const requestOptions = await this.listFineTuningJobEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FineTuningJobEventListFromJSON(jsonValue));
    }

    /**
     * List fine-tuning job events (OpenAI-compatible)
     */
    async listFineTuningJobEvents(requestParameters: ListFineTuningJobEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FineTuningJobEventList> {
        const response = await this.listFineTuningJobEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFineTuningJobs without sending the request
     */
    async listFineTuningJobsRequestOpts(requestParameters: ListFineTuningJobsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fine_tuning/jobs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List fine-tuning jobs (OpenAI-compatible)
     */
    async listFineTuningJobsRaw(requestParameters: ListFineTuningJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FineTuningJobList>> {
        const requestOptions = await this.listFineTuningJobsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FineTuningJobListFromJSON(jsonValue));
    }

    /**
     * List fine-tuning jobs (OpenAI-compatible)
     */
    async listFineTuningJobs(requestParameters: ListFineTuningJobsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FineTuningJobList> {
        const response = await this.listFineTuningJobsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retrieveFile without sending the request
     */
    async retrieveFileRequestOpts(requestParameters: RetrieveFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling retrieveFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/files/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the metadata for one of your uploaded files. The lookup is scoped to the organization the API key belongs to: a file id that does not exist and one that belongs to another organization both return the same 404, so this route cannot be used to probe for other tenants\' ids.  Use it to check that a `training_file` is present and usable BEFORE creating a fine-tuning job — the create path performs the identical ownership check, so a file this route returns is a file that create will accept.
     * Retrieve a file (OpenAI-compatible)
     */
    async retrieveFileRaw(requestParameters: RetrieveFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileObject>> {
        const requestOptions = await this.retrieveFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileObjectFromJSON(jsonValue));
    }

    /**
     * Returns the metadata for one of your uploaded files. The lookup is scoped to the organization the API key belongs to: a file id that does not exist and one that belongs to another organization both return the same 404, so this route cannot be used to probe for other tenants\' ids.  Use it to check that a `training_file` is present and usable BEFORE creating a fine-tuning job — the create path performs the identical ownership check, so a file this route returns is a file that create will accept.
     * Retrieve a file (OpenAI-compatible)
     */
    async retrieveFile(requestParameters: RetrieveFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileObject> {
        const response = await this.retrieveFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateFilePurposeEnum = {
    FineTune: 'fine-tune'
} as const;
export type CreateFilePurposeEnum = typeof CreateFilePurposeEnum[keyof typeof CreateFilePurposeEnum];
