/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GPUTypePage,
    GPUTypePageFromJSON,
    GPUTypePageToJSON,
} from '../models/GPUTypePage';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface ListGpuTypesRequest {
    cursor?: string;
    limit?: number;
}

/**
 * 
 */
export class GpuTypesApi extends runtime.BaseAPI {

    /**
     * Creates request options for listGpuTypes without sending the request
     */
    async listGpuTypesRequestOpts(requestParameters: ListGpuTypesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gpu-types`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List available GPU types (no auth required)
     */
    async listGpuTypesRaw(requestParameters: ListGpuTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GPUTypePage>> {
        const requestOptions = await this.listGpuTypesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GPUTypePageFromJSON(jsonValue));
    }

    /**
     * List available GPU types (no auth required)
     */
    async listGpuTypes(requestParameters: ListGpuTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GPUTypePage> {
        const response = await this.listGpuTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
