/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChatCompletionRequest,
    ChatCompletionRequestFromJSON,
    ChatCompletionRequestToJSON,
} from '../models/ChatCompletionRequest';
import {
    type ChatCompletionResponse,
    ChatCompletionResponseFromJSON,
    ChatCompletionResponseToJSON,
} from '../models/ChatCompletionResponse';
import {
    type EmbeddingsRequest,
    EmbeddingsRequestFromJSON,
    EmbeddingsRequestToJSON,
} from '../models/EmbeddingsRequest';
import {
    type EmbeddingsResponse,
    EmbeddingsResponseFromJSON,
    EmbeddingsResponseToJSON,
} from '../models/EmbeddingsResponse';
import {
    type ImagesGenerationsRequest,
    ImagesGenerationsRequestFromJSON,
    ImagesGenerationsRequestToJSON,
} from '../models/ImagesGenerationsRequest';
import {
    type ImagesResponse,
    ImagesResponseFromJSON,
    ImagesResponseToJSON,
} from '../models/ImagesResponse';
import {
    type Model,
    ModelFromJSON,
    ModelToJSON,
} from '../models/Model';
import {
    type ModelList,
    ModelListFromJSON,
    ModelListToJSON,
} from '../models/ModelList';
import {
    type OpenAIErrorEnvelope,
    OpenAIErrorEnvelopeFromJSON,
    OpenAIErrorEnvelopeToJSON,
} from '../models/OpenAIErrorEnvelope';
import {
    type VideoCreateRequest,
    VideoCreateRequestFromJSON,
    VideoCreateRequestToJSON,
} from '../models/VideoCreateRequest';
import {
    type VideoJob,
    VideoJobFromJSON,
    VideoJobToJSON,
} from '../models/VideoJob';
import {
    type VideoList,
    VideoListFromJSON,
    VideoListToJSON,
} from '../models/VideoList';

export interface CancelVideoRequest {
    id: string;
}

export interface CreateChatCompletionRequest {
    chatCompletionRequest: ChatCompletionRequest;
}

export interface CreateEmbeddingsRequest {
    embeddingsRequest: EmbeddingsRequest;
}

export interface CreateImageRequest {
    imagesGenerationsRequest: ImagesGenerationsRequest;
    idempotencyKey?: string;
}

export interface CreateVideoRequest {
    videoCreateRequest: VideoCreateRequest;
    idempotencyKey?: string;
}

export interface GetModelRequest {
    id: string;
}

export interface GetVideoRequest {
    id: string;
}

export interface GetVideoContentRequest {
    id: string;
}

export interface ListModelsRequest {
    modality?: ListModelsModalityEnum;
}

export interface ListVideosRequest {
    after?: string;
    limit?: number;
}

/**
 * 
 */
export class InferenceApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelVideo without sending the request
     */
    async cancelVideoRequestOpts(requestParameters: CancelVideoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/videos/{id}/cancel`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel a video generation job
     */
    async cancelVideoRaw(requestParameters: CancelVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoJob>> {
        const requestOptions = await this.cancelVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoJobFromJSON(jsonValue));
    }

    /**
     * Cancel a video generation job
     */
    async cancelVideo(requestParameters: CancelVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoJob> {
        const response = await this.cancelVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createChatCompletion without sending the request
     */
    async createChatCompletionRequestOpts(requestParameters: CreateChatCompletionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chatCompletionRequest'] == null) {
            throw new runtime.RequiredError(
                'chatCompletionRequest',
                'Required parameter "chatCompletionRequest" was null or undefined when calling createChatCompletion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/completions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatCompletionRequestToJSON(requestParameters['chatCompletionRequest']),
        };
    }

    /**
     * Create a chat completion (OpenAI-compatible)
     */
    async createChatCompletionRaw(requestParameters: CreateChatCompletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatCompletionResponse>> {
        const requestOptions = await this.createChatCompletionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatCompletionResponseFromJSON(jsonValue));
    }

    /**
     * Create a chat completion (OpenAI-compatible)
     */
    async createChatCompletion(requestParameters: CreateChatCompletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatCompletionResponse> {
        const response = await this.createChatCompletionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEmbeddings without sending the request
     */
    async createEmbeddingsRequestOpts(requestParameters: CreateEmbeddingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['embeddingsRequest'] == null) {
            throw new runtime.RequiredError(
                'embeddingsRequest',
                'Required parameter "embeddingsRequest" was null or undefined when calling createEmbeddings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/embeddings`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmbeddingsRequestToJSON(requestParameters['embeddingsRequest']),
        };
    }

    /**
     * Synchronous text embeddings. Accepts a single string or an array of up to 2048 strings, bounded so the response stays under 64 MiB (about 680 inputs at 4096 dimensions; fewer at a larger `dimensions` value) — over-limit requests are rejected with 400 before any processing. Returns one float vector per input, in request order. Billed on the upstream\'s reported prompt tokens at the model\'s listed input rate, rounded up to the next whole cent per request; an embeddings call emits no completion tokens, so `usage` carries `prompt_tokens` and `total_tokens` only. `encoding_format` accepts only `float` — a value of `base64` is rejected with `unsupported_parameter`. A chat model id on this route returns 404 `model_not_found`: the id is valid, but not on this surface.
     * Create embeddings (OpenAI-compatible)
     */
    async createEmbeddingsRaw(requestParameters: CreateEmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmbeddingsResponse>> {
        const requestOptions = await this.createEmbeddingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmbeddingsResponseFromJSON(jsonValue));
    }

    /**
     * Synchronous text embeddings. Accepts a single string or an array of up to 2048 strings, bounded so the response stays under 64 MiB (about 680 inputs at 4096 dimensions; fewer at a larger `dimensions` value) — over-limit requests are rejected with 400 before any processing. Returns one float vector per input, in request order. Billed on the upstream\'s reported prompt tokens at the model\'s listed input rate, rounded up to the next whole cent per request; an embeddings call emits no completion tokens, so `usage` carries `prompt_tokens` and `total_tokens` only. `encoding_format` accepts only `float` — a value of `base64` is rejected with `unsupported_parameter`. A chat model id on this route returns 404 `model_not_found`: the id is valid, but not on this surface.
     * Create embeddings (OpenAI-compatible)
     */
    async createEmbeddings(requestParameters: CreateEmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmbeddingsResponse> {
        const response = await this.createEmbeddingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createImage without sending the request
     */
    async createImageRequestOpts(requestParameters: CreateImageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imagesGenerationsRequest'] == null) {
            throw new runtime.RequiredError(
                'imagesGenerationsRequest',
                'Required parameter "imagesGenerationsRequest" was null or undefined when calling createImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/images/generations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImagesGenerationsRequestToJSON(requestParameters['imagesGenerationsRequest']),
        };
    }

    /**
     * Synchronous text-to-image generation. Returns base64-encoded images only (`response_format` is restricted to `b64_json`); a value of `url` is rejected with `invalid_request_error` until S3-backed URL delivery lands. Pass an `Idempotency-Key` header to make a retried request replay the original response without a second charge.
     * Create image (OpenAI-compatible)
     */
    async createImageRaw(requestParameters: CreateImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImagesResponse>> {
        const requestOptions = await this.createImageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImagesResponseFromJSON(jsonValue));
    }

    /**
     * Synchronous text-to-image generation. Returns base64-encoded images only (`response_format` is restricted to `b64_json`); a value of `url` is rejected with `invalid_request_error` until S3-backed URL delivery lands. Pass an `Idempotency-Key` header to make a retried request replay the original response without a second charge.
     * Create image (OpenAI-compatible)
     */
    async createImage(requestParameters: CreateImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImagesResponse> {
        const response = await this.createImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createVideo without sending the request
     */
    async createVideoRequestOpts(requestParameters: CreateVideoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'videoCreateRequest',
                'Required parameter "videoCreateRequest" was null or undefined when calling createVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/videos`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoCreateRequestToJSON(requestParameters['videoCreateRequest']),
        };
    }

    /**
     * Submit an asynchronous text-to-video generation job. Returns a job object with status `queued`; poll GET /videos/{id} until `completed`, then stream the result from GET /videos/{id}/content. Pass an `Idempotency-Key` header to make a retried request replay the original response without a second charge.
     * Create a video generation job (async)
     */
    async createVideoRaw(requestParameters: CreateVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoJob>> {
        const requestOptions = await this.createVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoJobFromJSON(jsonValue));
    }

    /**
     * Submit an asynchronous text-to-video generation job. Returns a job object with status `queued`; poll GET /videos/{id} until `completed`, then stream the result from GET /videos/{id}/content. Pass an `Idempotency-Key` header to make a retried request replay the original response without a second charge.
     * Create a video generation job (async)
     */
    async createVideo(requestParameters: CreateVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoJob> {
        const response = await this.createVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModel without sending the request
     */
    async getModelRequestOpts(requestParameters: GetModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/models/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific model (OpenAI-compatible)
     */
    async getModelRaw(requestParameters: GetModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model>> {
        const requestOptions = await this.getModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelFromJSON(jsonValue));
    }

    /**
     * Get a specific model (OpenAI-compatible)
     */
    async getModel(requestParameters: GetModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model> {
        const response = await this.getModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideo without sending the request
     */
    async getVideoRequestOpts(requestParameters: GetVideoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/videos/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a video generation job
     */
    async getVideoRaw(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoJob>> {
        const requestOptions = await this.getVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoJobFromJSON(jsonValue));
    }

    /**
     * Get a video generation job
     */
    async getVideo(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoJob> {
        const response = await this.getVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideoContent without sending the request
     */
    async getVideoContentRequestOpts(requestParameters: GetVideoContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVideoContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/videos/{id}/content`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Streams the generated MP4 for a completed job. Returns 410 Gone once the artifact has expired (24h retention).
     * Download a completed video artifact
     */
    async getVideoContentRaw(requestParameters: GetVideoContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getVideoContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Streams the generated MP4 for a completed job. Returns 410 Gone once the artifact has expired (24h retention).
     * Download a completed video artifact
     */
    async getVideoContent(requestParameters: GetVideoContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getVideoContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listModels without sending the request
     */
    async listModelsRequestOpts(requestParameters: ListModelsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['modality'] != null) {
            queryParameters['modality'] = requestParameters['modality'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/models`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List available models (OpenAI-compatible)
     */
    async listModelsRaw(requestParameters: ListModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelList>> {
        const requestOptions = await this.listModelsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelListFromJSON(jsonValue));
    }

    /**
     * List available models (OpenAI-compatible)
     */
    async listModels(requestParameters: ListModelsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelList> {
        const response = await this.listModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listVideos without sending the request
     */
    async listVideosRequestOpts(requestParameters: ListVideosRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/videos`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List video generation jobs
     */
    async listVideosRaw(requestParameters: ListVideosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoList>> {
        const requestOptions = await this.listVideosRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoListFromJSON(jsonValue));
    }

    /**
     * List video generation jobs
     */
    async listVideos(requestParameters: ListVideosRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoList> {
        const response = await this.listVideosRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListModelsModalityEnum = {
    Chat: 'chat',
    Image: 'image',
    Video: 'video',
    Embedding: 'embedding'
} as const;
export type ListModelsModalityEnum = typeof ListModelsModalityEnum[keyof typeof ListModelsModalityEnum];
