/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateInstanceRequest,
    CreateInstanceRequestFromJSON,
    CreateInstanceRequestToJSON,
} from '../models/CreateInstanceRequest';
import {
    type Instance,
    InstanceFromJSON,
    InstanceToJSON,
} from '../models/Instance';
import {
    type InstancePage,
    InstancePageFromJSON,
    InstancePageToJSON,
} from '../models/InstancePage';
import {
    type Operation,
    OperationFromJSON,
    OperationToJSON,
} from '../models/Operation';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type UpdateInstanceRequest,
    UpdateInstanceRequestFromJSON,
    UpdateInstanceRequestToJSON,
} from '../models/UpdateInstanceRequest';

export interface CreateInstanceOperationRequest {
    createInstanceRequest: CreateInstanceRequest;
    idempotencyKey?: string;
}

export interface DeleteInstanceRequest {
    id: string;
    idempotencyKey?: string;
}

export interface GetInstanceRequest {
    id: string;
}

export interface ListInstancesRequest {
    cursor?: string;
    limit?: number;
    status?: ListInstancesStatusEnum;
}

export interface UpdateInstanceOperationRequest {
    id: string;
    updateInstanceRequest: UpdateInstanceRequest;
    idempotencyKey?: string;
}

/**
 * 
 */
export class InstancesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createInstance without sending the request
     */
    async createInstanceRequestOpts(requestParameters: CreateInstanceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createInstanceRequest'] == null) {
            throw new runtime.RequiredError(
                'createInstanceRequest',
                'Required parameter "createInstanceRequest" was null or undefined when calling createInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/instances`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInstanceRequestToJSON(requestParameters['createInstanceRequest']),
        };
    }

    /**
     * Create an instance (async — returns 202 + Operation-Id header)
     */
    async createInstanceRaw(requestParameters: CreateInstanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Operation>> {
        const requestOptions = await this.createInstanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperationFromJSON(jsonValue));
    }

    /**
     * Create an instance (async — returns 202 + Operation-Id header)
     */
    async createInstance(requestParameters: CreateInstanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Operation> {
        const response = await this.createInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteInstance without sending the request
     */
    async deleteInstanceRequestOpts(requestParameters: DeleteInstanceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/instances/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Members can terminate only instances they created; organization admins can terminate any instance in the organization.
     * Terminate an instance (idempotent)
     */
    async deleteInstanceRaw(requestParameters: DeleteInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Operation>> {
        const requestOptions = await this.deleteInstanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperationFromJSON(jsonValue));
    }

    /**
     * Members can terminate only instances they created; organization admins can terminate any instance in the organization.
     * Terminate an instance (idempotent)
     */
    async deleteInstance(requestParameters: DeleteInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Operation> {
        const response = await this.deleteInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInstance without sending the request
     */
    async getInstanceRequestOpts(requestParameters: GetInstanceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/instances/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get an instance
     */
    async getInstanceRaw(requestParameters: GetInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Instance>> {
        const requestOptions = await this.getInstanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceFromJSON(jsonValue));
    }

    /**
     * Get an instance
     */
    async getInstance(requestParameters: GetInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Instance> {
        const response = await this.getInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listInstances without sending the request
     */
    async listInstancesRequestOpts(requestParameters: ListInstancesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/instances`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists the organization\'s instances. By default terminated instances are excluded; pass status=terminated for the history or status=all for everything.
     * List instances
     */
    async listInstancesRaw(requestParameters: ListInstancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstancePage>> {
        const requestOptions = await this.listInstancesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstancePageFromJSON(jsonValue));
    }

    /**
     * Lists the organization\'s instances. By default terminated instances are excluded; pass status=terminated for the history or status=all for everything.
     * List instances
     */
    async listInstances(requestParameters: ListInstancesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstancePage> {
        const response = await this.listInstancesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateInstance without sending the request
     */
    async updateInstanceRequestOpts(requestParameters: UpdateInstanceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateInstance().'
            );
        }

        if (requestParameters['updateInstanceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateInstanceRequest',
                'Required parameter "updateInstanceRequest" was null or undefined when calling updateInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/instances/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateInstanceRequestToJSON(requestParameters['updateInstanceRequest']),
        };
    }

    /**
     * Update an instance (rename only in v1)
     */
    async updateInstanceRaw(requestParameters: UpdateInstanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Instance>> {
        const requestOptions = await this.updateInstanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceFromJSON(jsonValue));
    }

    /**
     * Update an instance (rename only in v1)
     */
    async updateInstance(requestParameters: UpdateInstanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Instance> {
        const response = await this.updateInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListInstancesStatusEnum = {
    Allocating: 'allocating',
    Starting: 'starting',
    Running: 'running',
    Stopping: 'stopping',
    Stopped: 'stopped',
    Terminated: 'terminated',
    Error: 'error',
    All: 'all'
} as const;
export type ListInstancesStatusEnum = typeof ListInstancesStatusEnum[keyof typeof ListInstancesStatusEnum];
