/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PricingPage,
    PricingPageFromJSON,
    PricingPageToJSON,
} from '../models/PricingPage';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface ListPricingRequest {
    cursor?: string;
    limit?: number;
    gpuType?: string;
    region?: string;
    tier?: ListPricingTierEnum;
    includeUnavailable?: boolean;
}

/**
 * 
 */
export class PricingApi extends runtime.BaseAPI {

    /**
     * Creates request options for listPricing without sending the request
     */
    async listPricingRequestOpts(requestParameters: ListPricingRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['gpuType'] != null) {
            queryParameters['gpu_type'] = requestParameters['gpuType'];
        }

        if (requestParameters['region'] != null) {
            queryParameters['region'] = requestParameters['region'];
        }

        if (requestParameters['tier'] != null) {
            queryParameters['tier'] = requestParameters['tier'];
        }

        if (requestParameters['includeUnavailable'] != null) {
            queryParameters['include_unavailable'] = requestParameters['includeUnavailable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pricing`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists every distinct offer (gpu_type, gpu_count, region, tier, price, boot class). Customer-identical offers are merged with availability summed. Offers with zero availability are omitted unless include_unavailable=true.
     * List pricing per GPU type + region (no auth required)
     */
    async listPricingRaw(requestParameters: ListPricingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PricingPage>> {
        const requestOptions = await this.listPricingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PricingPageFromJSON(jsonValue));
    }

    /**
     * Lists every distinct offer (gpu_type, gpu_count, region, tier, price, boot class). Customer-identical offers are merged with availability summed. Offers with zero availability are omitted unless include_unavailable=true.
     * List pricing per GPU type + region (no auth required)
     */
    async listPricing(requestParameters: ListPricingRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PricingPage> {
        const response = await this.listPricingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListPricingTierEnum = {
    Spot: 'spot',
    OnDemand: 'on_demand'
} as const;
export type ListPricingTierEnum = typeof ListPricingTierEnum[keyof typeof ListPricingTierEnum];
