/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateRegistryCredentialRequest,
    CreateRegistryCredentialRequestFromJSON,
    CreateRegistryCredentialRequestToJSON,
} from '../models/CreateRegistryCredentialRequest';
import {
    type ListRegistryCredentials200Response,
    ListRegistryCredentials200ResponseFromJSON,
    ListRegistryCredentials200ResponseToJSON,
} from '../models/ListRegistryCredentials200Response';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type RegistryCredential,
    RegistryCredentialFromJSON,
    RegistryCredentialToJSON,
} from '../models/RegistryCredential';

export interface CreateRegistryCredentialOperationRequest {
    createRegistryCredentialRequest: CreateRegistryCredentialRequest;
}

export interface DeleteRegistryCredentialRequest {
    id: string;
}

/**
 * 
 */
export class RegistryCredentialsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createRegistryCredential without sending the request
     */
    async createRegistryCredentialRequestOpts(requestParameters: CreateRegistryCredentialOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createRegistryCredentialRequest'] == null) {
            throw new runtime.RequiredError(
                'createRegistryCredentialRequest',
                'Required parameter "createRegistryCredentialRequest" was null or undefined when calling createRegistryCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/registry-credentials`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRegistryCredentialRequestToJSON(requestParameters['createRegistryCredentialRequest']),
        };
    }

    /**
     * Stores a private-registry login for pulling private custom images. The password crosses the wire exactly once — here — and is encrypted at rest; no read ever returns it. Reference the returned id from `registry_credential_id` on instance creation. The credential\'s registry host must obey the same rules as image references (no localhost/private addresses); username and password must not contain whitespace. Duplicate names return 409 `name_taken`.
     * Store a registry credential
     */
    async createRegistryCredentialRaw(requestParameters: CreateRegistryCredentialOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegistryCredential>> {
        const requestOptions = await this.createRegistryCredentialRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegistryCredentialFromJSON(jsonValue));
    }

    /**
     * Stores a private-registry login for pulling private custom images. The password crosses the wire exactly once — here — and is encrypted at rest; no read ever returns it. Reference the returned id from `registry_credential_id` on instance creation. The credential\'s registry host must obey the same rules as image references (no localhost/private addresses); username and password must not contain whitespace. Duplicate names return 409 `name_taken`.
     * Store a registry credential
     */
    async createRegistryCredential(requestParameters: CreateRegistryCredentialOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegistryCredential> {
        const response = await this.createRegistryCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteRegistryCredential without sending the request
     */
    async deleteRegistryCredentialRequestOpts(requestParameters: DeleteRegistryCredentialRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRegistryCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/registry-credentials/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a registry credential
     */
    async deleteRegistryCredentialRaw(requestParameters: DeleteRegistryCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteRegistryCredentialRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a registry credential
     */
    async deleteRegistryCredential(requestParameters: DeleteRegistryCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRegistryCredentialRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listRegistryCredentials without sending the request
     */
    async listRegistryCredentialsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/registry-credentials`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists the organization\'s stored private-registry logins for custom-image launches. Passwords are never returned by any read. 503 when the feature is not enabled on this environment.
     * List registry credentials
     */
    async listRegistryCredentialsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRegistryCredentials200Response>> {
        const requestOptions = await this.listRegistryCredentialsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRegistryCredentials200ResponseFromJSON(jsonValue));
    }

    /**
     * Lists the organization\'s stored private-registry logins for custom-image launches. Passwords are never returned by any read. 503 when the feature is not enabled on this environment.
     * List registry credentials
     */
    async listRegistryCredentials(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRegistryCredentials200Response> {
        const response = await this.listRegistryCredentialsRaw(initOverrides);
        return await response.value();
    }

}
