/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateSshKeyRequest,
    CreateSshKeyRequestFromJSON,
    CreateSshKeyRequestToJSON,
} from '../models/CreateSshKeyRequest';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type SSHKey,
    SSHKeyFromJSON,
    SSHKeyToJSON,
} from '../models/SSHKey';
import {
    type SSHKeyPage,
    SSHKeyPageFromJSON,
    SSHKeyPageToJSON,
} from '../models/SSHKeyPage';

export interface CreateSshKeyOperationRequest {
    createSshKeyRequest: CreateSshKeyRequest;
    idempotencyKey?: string;
}

export interface DeleteSshKeyRequest {
    id: string;
}

export interface GetSshKeyRequest {
    id: string;
}

export interface ListSshKeysRequest {
    cursor?: string;
    limit?: number;
}

/**
 * 
 */
export class SshKeysApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSshKey without sending the request
     */
    async createSshKeyRequestOpts(requestParameters: CreateSshKeyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSshKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'createSshKeyRequest',
                'Required parameter "createSshKeyRequest" was null or undefined when calling createSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ssh-keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSshKeyRequestToJSON(requestParameters['createSshKeyRequest']),
        };
    }

    /**
     * Create an SSH key
     */
    async createSshKeyRaw(requestParameters: CreateSshKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSHKey>> {
        const requestOptions = await this.createSshKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SSHKeyFromJSON(jsonValue));
    }

    /**
     * Create an SSH key
     */
    async createSshKey(requestParameters: CreateSshKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSHKey> {
        const response = await this.createSshKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSshKey without sending the request
     */
    async deleteSshKeyRequestOpts(requestParameters: DeleteSshKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ssh-keys/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an SSH key (idempotent — 404 on already-gone per D-07)
     */
    async deleteSshKeyRaw(requestParameters: DeleteSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSshKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an SSH key (idempotent — 404 on already-gone per D-07)
     */
    async deleteSshKey(requestParameters: DeleteSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSshKeyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getSshKey without sending the request
     */
    async getSshKeyRequestOpts(requestParameters: GetSshKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ssh-keys/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get an SSH key
     */
    async getSshKeyRaw(requestParameters: GetSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSHKey>> {
        const requestOptions = await this.getSshKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SSHKeyFromJSON(jsonValue));
    }

    /**
     * Get an SSH key
     */
    async getSshKey(requestParameters: GetSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSHKey> {
        const response = await this.getSshKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSshKeys without sending the request
     */
    async listSshKeysRequestOpts(requestParameters: ListSshKeysRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ssh-keys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the SSH keys owned by the user the API key was minted by. Org-wide key visibility is an admin capability in the dashboard.
     * List SSH keys
     */
    async listSshKeysRaw(requestParameters: ListSshKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSHKeyPage>> {
        const requestOptions = await this.listSshKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SSHKeyPageFromJSON(jsonValue));
    }

    /**
     * Returns the SSH keys owned by the user the API key was minted by. Org-wide key visibility is an admin capability in the dashboard.
     * List SSH keys
     */
    async listSshKeys(requestParameters: ListSshKeysRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSHKeyPage> {
        const response = await this.listSshKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
