/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateWebhookEndpointRequest,
    CreateWebhookEndpointRequestFromJSON,
    CreateWebhookEndpointRequestToJSON,
} from '../models/CreateWebhookEndpointRequest';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type WebhookEndpoint,
    WebhookEndpointFromJSON,
    WebhookEndpointToJSON,
} from '../models/WebhookEndpoint';
import {
    type WebhookEndpointPage,
    WebhookEndpointPageFromJSON,
    WebhookEndpointPageToJSON,
} from '../models/WebhookEndpointPage';

export interface CreateWebhookEndpointOperationRequest {
    createWebhookEndpointRequest: CreateWebhookEndpointRequest;
    idempotencyKey?: string;
}

export interface DeleteWebhookEndpointRequest {
    id: string;
}

export interface GetWebhookEndpointRequest {
    id: string;
}

export interface ListWebhookEndpointsRequest {
    cursor?: string;
    limit?: number;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Creates request options for createWebhookEndpoint without sending the request
     */
    async createWebhookEndpointRequestOpts(requestParameters: CreateWebhookEndpointOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWebhookEndpointRequest'] == null) {
            throw new runtime.RequiredError(
                'createWebhookEndpointRequest',
                'Required parameter "createWebhookEndpointRequest" was null or undefined when calling createWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/webhook-endpoints`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookEndpointRequestToJSON(requestParameters['createWebhookEndpointRequest']),
        };
    }

    /**
     * Create a webhook endpoint
     */
    async createWebhookEndpointRaw(requestParameters: CreateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpoint>> {
        const requestOptions = await this.createWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointFromJSON(jsonValue));
    }

    /**
     * Create a webhook endpoint
     */
    async createWebhookEndpoint(requestParameters: CreateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpoint> {
        const response = await this.createWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWebhookEndpoint without sending the request
     */
    async deleteWebhookEndpointRequestOpts(requestParameters: DeleteWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/webhook-endpoints/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a webhook endpoint
     */
    async deleteWebhookEndpointRaw(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a webhook endpoint
     */
    async deleteWebhookEndpoint(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWebhookEndpointRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getWebhookEndpoint without sending the request
     */
    async getWebhookEndpointRequestOpts(requestParameters: GetWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/webhook-endpoints/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a webhook endpoint
     */
    async getWebhookEndpointRaw(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpoint>> {
        const requestOptions = await this.getWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointFromJSON(jsonValue));
    }

    /**
     * Get a webhook endpoint
     */
    async getWebhookEndpoint(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpoint> {
        const response = await this.getWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookEndpoints without sending the request
     */
    async listWebhookEndpointsRequestOpts(requestParameters: ListWebhookEndpointsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/webhook-endpoints`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List webhook endpoints
     */
    async listWebhookEndpointsRaw(requestParameters: ListWebhookEndpointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointPage>> {
        const requestOptions = await this.listWebhookEndpointsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointPageFromJSON(jsonValue));
    }

    /**
     * List webhook endpoints
     */
    async listWebhookEndpoints(requestParameters: ListWebhookEndpointsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointPage> {
        const response = await this.listWebhookEndpointsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
