/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Usage } from './Usage';
import {
    UsageFromJSON,
    UsageFromJSONTyped,
    UsageToJSON,
    UsageToJSONTyped,
} from './Usage';
import type { ChatChoice } from './ChatChoice';
import {
    ChatChoiceFromJSON,
    ChatChoiceFromJSONTyped,
    ChatChoiceToJSON,
    ChatChoiceToJSONTyped,
} from './ChatChoice';

/**
 * 
 * @export
 * @interface ChatCompletionResponse
 */
export interface ChatCompletionResponse {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    id: string;
    /**
     * 
     * @type {ChatCompletionResponseObjectEnum}
     * @memberof ChatCompletionResponse
     */
    object: ChatCompletionResponseObjectEnum;
    /**
     * Unix timestamp (seconds).
     * @type {number}
     * @memberof ChatCompletionResponse
     */
    created: number;
    /**
     * Canonical (gpuai/...) model id, NEVER the upstream HF path.
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    model: string;
    /**
     * 
     * @type {Array<ChatChoice>}
     * @memberof ChatCompletionResponse
     */
    choices: Array<ChatChoice>;
    /**
     * 
     * @type {Usage}
     * @memberof ChatCompletionResponse
     */
    usage: Usage;
}


/**
 * @export
 */
export const ChatCompletionResponseObjectEnum = {
    ChatCompletion: 'chat.completion'
} as const;
export type ChatCompletionResponseObjectEnum = typeof ChatCompletionResponseObjectEnum[keyof typeof ChatCompletionResponseObjectEnum];


/**
 * Check if a given object implements the ChatCompletionResponse interface.
 */
export function instanceOfChatCompletionResponse(value: object): value is ChatCompletionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'chat.completion') return false;
    
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    return true;
}

export function ChatCompletionResponseFromJSON(json: any): ChatCompletionResponse {
    return ChatCompletionResponseFromJSONTyped(json, false);
}

export function ChatCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'created': json['created'],
        'model': json['model'],
        'choices': ((json['choices'] as Array<any>).map(ChatChoiceFromJSON)),
        'usage': UsageFromJSON(json['usage']),
    };
}

export function ChatCompletionResponseToJSON(json: any): ChatCompletionResponse {
    return ChatCompletionResponseToJSONTyped(json, false);
}

export function ChatCompletionResponseToJSONTyped(value?: ChatCompletionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'model': value['model'],
        'choices': ((value['choices'] as Array<any>).map(ChatChoiceToJSON)),
        'usage': UsageToJSON(value['usage']),
    };
}

