/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';
import type { StreamOptions } from './StreamOptions';
import {
    StreamOptionsFromJSON,
    StreamOptionsFromJSONTyped,
    StreamOptionsToJSON,
    StreamOptionsToJSONTyped,
} from './StreamOptions';

/**
 * 
 * @export
 * @interface ChatCompletionRequest
 */
export interface ChatCompletionRequest {
    /**
     * Canonical model id, e.g. "gpuai/qwen2.5-7b-instruct".
     * @type {string}
     * @memberof ChatCompletionRequest
     */
    model: string;
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof ChatCompletionRequest
     */
    messages: Array<ChatMessage>;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionRequest
     */
    temperature?: number;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionRequest
     */
    maxTokens?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ChatCompletionRequest
     */
    stream?: boolean;
    /**
     * 
     * @type {StreamOptions}
     * @memberof ChatCompletionRequest
     */
    streamOptions?: StreamOptions;
}

/**
 * Check if a given object implements the ChatCompletionRequest interface.
 */
export function instanceOfChatCompletionRequest(value: object): value is ChatCompletionRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ChatCompletionRequestFromJSON(json: any): ChatCompletionRequest {
    return ChatCompletionRequestFromJSONTyped(json, false);
}

export function ChatCompletionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'messages': ((json['messages'] as Array<any>).map(ChatMessageFromJSON)),
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'maxTokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'stream': json['stream'] == null ? undefined : json['stream'],
        'streamOptions': json['stream_options'] == null ? undefined : StreamOptionsFromJSON(json['stream_options']),
    };
}

export function ChatCompletionRequestToJSON(json: any): ChatCompletionRequest {
    return ChatCompletionRequestToJSONTyped(json, false);
}

export function ChatCompletionRequestToJSONTyped(value?: ChatCompletionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'messages': ((value['messages'] as Array<any>).map(ChatMessageToJSON)),
        'temperature': value['temperature'],
        'max_tokens': value['maxTokens'],
        'stream': value['stream'],
        'stream_options': StreamOptionsToJSON(value['streamOptions']),
    };
}

