/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface ChatChoice
 */
export interface ChatChoice {
    /**
     * 
     * @type {number}
     * @memberof ChatChoice
     */
    index?: number;
    /**
     * 
     * @type {ChatMessage}
     * @memberof ChatChoice
     */
    message?: ChatMessage;
    /**
     * 
     * @type {ChatChoiceFinishReasonEnum}
     * @memberof ChatChoice
     */
    finishReason?: ChatChoiceFinishReasonEnum;
}


/**
 * @export
 */
export const ChatChoiceFinishReasonEnum = {
    Stop: 'stop',
    Length: 'length',
    ContentFilter: 'content_filter',
    ToolCalls: 'tool_calls'
} as const;
export type ChatChoiceFinishReasonEnum = typeof ChatChoiceFinishReasonEnum[keyof typeof ChatChoiceFinishReasonEnum];


/**
 * Check if a given object implements the ChatChoice interface.
 */
export function instanceOfChatChoice(value: object): value is ChatChoice {
    return true;
}

export function ChatChoiceFromJSON(json: any): ChatChoice {
    return ChatChoiceFromJSONTyped(json, false);
}

export function ChatChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatChoice {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'message': json['message'] == null ? undefined : ChatMessageFromJSON(json['message']),
        'finishReason': json['finish_reason'] == null ? undefined : json['finish_reason'],
    };
}

export function ChatChoiceToJSON(json: any): ChatChoice {
    return ChatChoiceToJSONTyped(json, false);
}

export function ChatChoiceToJSONTyped(value?: ChatChoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'message': ChatMessageToJSON(value['message']),
        'finish_reason': value['finishReason'],
    };
}

