/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One organization's Community Cloud supplier profile (ONBD-01).
 * @export
 * @interface CommunitySupplier
 */
export interface CommunitySupplier {
    /**
     * 
     * @type {string}
     * @memberof CommunitySupplier
     */
    supplierId: string;
    /**
     * 
     * @type {string}
     * @memberof CommunitySupplier
     */
    orgId: string;
    /**
     * 
     * @type {CommunitySupplierStatusEnum}
     * @memberof CommunitySupplier
     */
    status: CommunitySupplierStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof CommunitySupplier
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommunitySupplier
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const CommunitySupplierStatusEnum = {
    Active: 'active',
    Suspended: 'suspended'
} as const;
export type CommunitySupplierStatusEnum = typeof CommunitySupplierStatusEnum[keyof typeof CommunitySupplierStatusEnum];


/**
 * Check if a given object implements the CommunitySupplier interface.
 */
export function instanceOfCommunitySupplier(value: object): value is CommunitySupplier {
    if ((!('supplierId' in (value as Record<string, any>)) && !('supplier_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['supplierId'] === undefined && (value as Record<string, any>)['supplier_id'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function CommunitySupplierFromJSON(json: any): CommunitySupplier {
    return CommunitySupplierFromJSONTyped(json, false);
}

export function CommunitySupplierFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunitySupplier {
    if (json == null) {
        return json;
    }
    return {
        
        'supplierId': json['supplier_id'],
        'orgId': json['org_id'],
        'status': json['status'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CommunitySupplierToJSON(json: any): CommunitySupplier {
    return CommunitySupplierToJSONTyped(json, false);
}

export function CommunitySupplierToJSONTyped(value?: CommunitySupplier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supplier_id': value['supplierId'],
        'org_id': value['orgId'],
        'status': value['status'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

