/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityEarningsEntry
 */
export interface CommunityEarningsEntry {
    /**
     * 
     * @type {string}
     * @memberof CommunityEarningsEntry
     */
    ledgerId: string;
    /**
     * 
     * @type {string}
     * @memberof CommunityEarningsEntry
     */
    machineId: string;
    /**
     * 
     * @type {string}
     * @memberof CommunityEarningsEntry
     */
    instanceId: string;
    /**
     * 
     * @type {number}
     * @memberof CommunityEarningsEntry
     */
    amountCents: number;
    /**
     * 
     * @type {Date}
     * @memberof CommunityEarningsEntry
     */
    accruedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof CommunityEarningsEntry
     */
    paid: boolean;
}

/**
 * Check if a given object implements the CommunityEarningsEntry interface.
 */
export function instanceOfCommunityEarningsEntry(value: object): value is CommunityEarningsEntry {
    if ((!('ledgerId' in (value as Record<string, any>)) && !('ledger_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['ledgerId'] === undefined && (value as Record<string, any>)['ledger_id'] === undefined)) return false;
    if ((!('machineId' in (value as Record<string, any>)) && !('machine_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['machineId'] === undefined && (value as Record<string, any>)['machine_id'] === undefined)) return false;
    if ((!('instanceId' in (value as Record<string, any>)) && !('instance_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['instanceId'] === undefined && (value as Record<string, any>)['instance_id'] === undefined)) return false;
    if ((!('amountCents' in (value as Record<string, any>)) && !('amount_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['amountCents'] === undefined && (value as Record<string, any>)['amount_cents'] === undefined)) return false;
    if ((!('accruedAt' in (value as Record<string, any>)) && !('accrued_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['accruedAt'] === undefined && (value as Record<string, any>)['accrued_at'] === undefined)) return false;
    if (!('paid' in value) || value['paid'] === undefined) return false;
    return true;
}

export function CommunityEarningsEntryFromJSON(json: any): CommunityEarningsEntry {
    return CommunityEarningsEntryFromJSONTyped(json, false);
}

export function CommunityEarningsEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityEarningsEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'ledgerId': json['ledger_id'],
        'machineId': json['machine_id'],
        'instanceId': json['instance_id'],
        'amountCents': json['amount_cents'],
        'accruedAt': (new Date(json['accrued_at'])),
        'paid': json['paid'],
    };
}

export function CommunityEarningsEntryToJSON(json: any): CommunityEarningsEntry {
    return CommunityEarningsEntryToJSONTyped(json, false);
}

export function CommunityEarningsEntryToJSONTyped(value?: CommunityEarningsEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ledger_id': value['ledgerId'],
        'machine_id': value['machineId'],
        'instance_id': value['instanceId'],
        'amount_cents': value['amountCents'],
        'accrued_at': value['accruedAt'].toISOString(),
        'paid': value['paid'],
    };
}

