/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunityEarningsEntry } from './CommunityEarningsEntry';
import {
    CommunityEarningsEntryFromJSON,
    CommunityEarningsEntryFromJSONTyped,
    CommunityEarningsEntryToJSON,
    CommunityEarningsEntryToJSONTyped,
} from './CommunityEarningsEntry';

/**
 * 
 * @export
 * @interface CommunityEarnings
 */
export interface CommunityEarnings {
    /**
     * Lifetime accrued earnings in cents.
     * @type {number}
     * @memberof CommunityEarnings
     */
    accruedCents: number;
    /**
     * Accrued but not yet paid out, in cents.
     * @type {number}
     * @memberof CommunityEarnings
     */
    unpaidCents: number;
    /**
     * 
     * @type {Array<CommunityEarningsEntry>}
     * @memberof CommunityEarnings
     */
    entries: Array<CommunityEarningsEntry>;
}

/**
 * Check if a given object implements the CommunityEarnings interface.
 */
export function instanceOfCommunityEarnings(value: object): value is CommunityEarnings {
    if ((!('accruedCents' in (value as Record<string, any>)) && !('accrued_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['accruedCents'] === undefined && (value as Record<string, any>)['accrued_cents'] === undefined)) return false;
    if ((!('unpaidCents' in (value as Record<string, any>)) && !('unpaid_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['unpaidCents'] === undefined && (value as Record<string, any>)['unpaid_cents'] === undefined)) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function CommunityEarningsFromJSON(json: any): CommunityEarnings {
    return CommunityEarningsFromJSONTyped(json, false);
}

export function CommunityEarningsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityEarnings {
    if (json == null) {
        return json;
    }
    return {
        
        'accruedCents': json['accrued_cents'],
        'unpaidCents': json['unpaid_cents'],
        'entries': ((json['entries'] as Array<any>).map(CommunityEarningsEntryFromJSON)),
    };
}

export function CommunityEarningsToJSON(json: any): CommunityEarnings {
    return CommunityEarningsToJSONTyped(json, false);
}

export function CommunityEarningsToJSONTyped(value?: CommunityEarnings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accrued_cents': value['accruedCents'],
        'unpaid_cents': value['unpaidCents'],
        'entries': ((value['entries'] as Array<any>).map(CommunityEarningsEntryToJSON)),
    };
}

