/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The terminal status a machine reached after a delist. `draining` means it was occupied and the existing rental keeps running (never killed); `delisted` means it was idle and left supply immediately.
 * @export
 * @interface CommunityMachineDelistResult
 */
export interface CommunityMachineDelistResult {
    /**
     * 
     * @type {string}
     * @memberof CommunityMachineDelistResult
     */
    machineId: string;
    /**
     * 
     * @type {CommunityMachineDelistResultStatusEnum}
     * @memberof CommunityMachineDelistResult
     */
    status: CommunityMachineDelistResultStatusEnum;
}


/**
 * @export
 */
export const CommunityMachineDelistResultStatusEnum = {
    Draining: 'draining',
    Delisted: 'delisted'
} as const;
export type CommunityMachineDelistResultStatusEnum = typeof CommunityMachineDelistResultStatusEnum[keyof typeof CommunityMachineDelistResultStatusEnum];


/**
 * Check if a given object implements the CommunityMachineDelistResult interface.
 */
export function instanceOfCommunityMachineDelistResult(value: object): value is CommunityMachineDelistResult {
    if ((!('machineId' in (value as Record<string, any>)) && !('machine_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['machineId'] === undefined && (value as Record<string, any>)['machine_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CommunityMachineDelistResultFromJSON(json: any): CommunityMachineDelistResult {
    return CommunityMachineDelistResultFromJSONTyped(json, false);
}

export function CommunityMachineDelistResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityMachineDelistResult {
    if (json == null) {
        return json;
    }
    return {
        
        'machineId': json['machine_id'],
        'status': json['status'],
    };
}

export function CommunityMachineDelistResultToJSON(json: any): CommunityMachineDelistResult {
    return CommunityMachineDelistResultToJSONTyped(json, false);
}

export function CommunityMachineDelistResultToJSONTyped(value?: CommunityMachineDelistResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_id': value['machineId'],
        'status': value['status'],
    };
}

