/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A self-declared Community Cloud machine. Spec fields are optional and unverified until Phase 57. The enrollment token hash is never serialized.
 * @export
 * @interface CommunityMachine
 */
export interface CommunityMachine {
    /**
     * 
     * @type {string}
     * @memberof CommunityMachine
     */
    machineId: string;
    /**
     * 
     * @type {string}
     * @memberof CommunityMachine
     */
    supplierId: string;
    /**
     * 
     * @type {string}
     * @memberof CommunityMachine
     */
    gpuType?: string;
    /**
     * 
     * @type {number}
     * @memberof CommunityMachine
     */
    gpuCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CommunityMachine
     */
    vramPerGpuGb?: number;
    /**
     * 
     * @type {number}
     * @memberof CommunityMachine
     */
    pricePerHour?: number;
    /**
     * 
     * @type {string}
     * @memberof CommunityMachine
     */
    region?: string;
    /**
     * Supplier-chosen rental model. on_demand = guaranteed whole-node capacity; spot = cheaper interruptible capacity. Defaults to on_demand. Becomes the catalog offering's tier.
     * @type {CommunityMachineTierEnum}
     * @memberof CommunityMachine
     */
    tier?: CommunityMachineTierEnum;
    /**
     * 
     * @type {CommunityMachineStatusEnum}
     * @memberof CommunityMachine
     */
    status: CommunityMachineStatusEnum;
    /**
     * 
     * @type {CommunityMachineVerificationStatusEnum}
     * @memberof CommunityMachine
     */
    verificationStatus: CommunityMachineVerificationStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof CommunityMachine
     */
    lastHeartbeatAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommunityMachine
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CommunityMachineTierEnum = {
    OnDemand: 'on_demand',
    Spot: 'spot'
} as const;
export type CommunityMachineTierEnum = typeof CommunityMachineTierEnum[keyof typeof CommunityMachineTierEnum];

/**
 * @export
 */
export const CommunityMachineStatusEnum = {
    PendingVerification: 'pending_verification',
    Listed: 'listed',
    Delisted: 'delisted',
    Suspended: 'suspended'
} as const;
export type CommunityMachineStatusEnum = typeof CommunityMachineStatusEnum[keyof typeof CommunityMachineStatusEnum];

/**
 * @export
 */
export const CommunityMachineVerificationStatusEnum = {
    Unverified: 'unverified',
    Verified: 'verified',
    Failed: 'failed'
} as const;
export type CommunityMachineVerificationStatusEnum = typeof CommunityMachineVerificationStatusEnum[keyof typeof CommunityMachineVerificationStatusEnum];


/**
 * Check if a given object implements the CommunityMachine interface.
 */
export function instanceOfCommunityMachine(value: object): value is CommunityMachine {
    if ((!('machineId' in (value as Record<string, any>)) && !('machine_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['machineId'] === undefined && (value as Record<string, any>)['machine_id'] === undefined)) return false;
    if ((!('supplierId' in (value as Record<string, any>)) && !('supplier_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['supplierId'] === undefined && (value as Record<string, any>)['supplier_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('verificationStatus' in (value as Record<string, any>)) && !('verification_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['verificationStatus'] === undefined && (value as Record<string, any>)['verification_status'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function CommunityMachineFromJSON(json: any): CommunityMachine {
    return CommunityMachineFromJSONTyped(json, false);
}

export function CommunityMachineFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityMachine {
    if (json == null) {
        return json;
    }
    return {
        
        'machineId': json['machine_id'],
        'supplierId': json['supplier_id'],
        'gpuType': json['gpu_type'] == null ? undefined : json['gpu_type'],
        'gpuCount': json['gpu_count'] == null ? undefined : json['gpu_count'],
        'vramPerGpuGb': json['vram_per_gpu_gb'] == null ? undefined : json['vram_per_gpu_gb'],
        'pricePerHour': json['price_per_hour'] == null ? undefined : json['price_per_hour'],
        'region': json['region'] == null ? undefined : json['region'],
        'tier': json['tier'] == null ? undefined : json['tier'],
        'status': json['status'],
        'verificationStatus': json['verification_status'],
        'lastHeartbeatAt': json['last_heartbeat_at'] == null ? undefined : (new Date(json['last_heartbeat_at'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function CommunityMachineToJSON(json: any): CommunityMachine {
    return CommunityMachineToJSONTyped(json, false);
}

export function CommunityMachineToJSONTyped(value?: CommunityMachine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_id': value['machineId'],
        'supplier_id': value['supplierId'],
        'gpu_type': value['gpuType'],
        'gpu_count': value['gpuCount'],
        'vram_per_gpu_gb': value['vramPerGpuGb'],
        'price_per_hour': value['pricePerHour'],
        'region': value['region'],
        'tier': value['tier'],
        'status': value['status'],
        'verification_status': value['verificationStatus'],
        'last_heartbeat_at': value['lastHeartbeatAt'] == null ? value['lastHeartbeatAt'] : value['lastHeartbeatAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
    };
}

