/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFineTuningJobRequestGpuai
 */
export interface CreateFineTuningJobRequestGpuai {
    /**
     * 
     * @type {number}
     * @memberof CreateFineTuningJobRequestGpuai
     */
    maxBudgetUsd?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateFineTuningJobRequestGpuai
     */
    gpuPreference?: string;
}

/**
 * Check if a given object implements the CreateFineTuningJobRequestGpuai interface.
 */
export function instanceOfCreateFineTuningJobRequestGpuai(value: object): value is CreateFineTuningJobRequestGpuai {
    return true;
}

export function CreateFineTuningJobRequestGpuaiFromJSON(json: any): CreateFineTuningJobRequestGpuai {
    return CreateFineTuningJobRequestGpuaiFromJSONTyped(json, false);
}

export function CreateFineTuningJobRequestGpuaiFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFineTuningJobRequestGpuai {
    if (json == null) {
        return json;
    }
    return {
        
        'maxBudgetUsd': json['max_budget_usd'] == null ? undefined : json['max_budget_usd'],
        'gpuPreference': json['gpu_preference'] == null ? undefined : json['gpu_preference'],
    };
}

export function CreateFineTuningJobRequestGpuaiToJSON(json: any): CreateFineTuningJobRequestGpuai {
    return CreateFineTuningJobRequestGpuaiToJSONTyped(json, false);
}

export function CreateFineTuningJobRequestGpuaiToJSONTyped(value?: CreateFineTuningJobRequestGpuai | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_budget_usd': value['maxBudgetUsd'],
        'gpu_preference': value['gpuPreference'],
    };
}

