/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSshKeyRequest
 */
export interface CreateSshKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSshKeyRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSshKeyRequest
     */
    publicKey: string;
}

/**
 * Check if a given object implements the CreateSshKeyRequest interface.
 */
export function instanceOfCreateSshKeyRequest(value: object): value is CreateSshKeyRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('publicKey' in (value as Record<string, any>)) && !('public_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['publicKey'] === undefined && (value as Record<string, any>)['public_key'] === undefined)) return false;
    return true;
}

export function CreateSshKeyRequestFromJSON(json: any): CreateSshKeyRequest {
    return CreateSshKeyRequestFromJSONTyped(json, false);
}

export function CreateSshKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSshKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'publicKey': json['public_key'],
    };
}

export function CreateSshKeyRequestToJSON(json: any): CreateSshKeyRequest {
    return CreateSshKeyRequestToJSONTyped(json, false);
}

export function CreateSshKeyRequestToJSONTyped(value?: CreateSshKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'public_key': value['publicKey'],
    };
}

