/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInstanceRequestPortsInner
 */
export interface CreateInstanceRequestPortsInner {
    /**
     * 
     * @type {number}
     * @memberof CreateInstanceRequestPortsInner
     */
    port: number;
    /**
     * 
     * @type {CreateInstanceRequestPortsInnerProtocolEnum}
     * @memberof CreateInstanceRequestPortsInner
     */
    protocol: CreateInstanceRequestPortsInnerProtocolEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CreateInstanceRequestPortsInner
     */
    primary?: boolean;
}


/**
 * @export
 */
export const CreateInstanceRequestPortsInnerProtocolEnum = {
    Http: 'http',
    Tcp: 'tcp'
} as const;
export type CreateInstanceRequestPortsInnerProtocolEnum = typeof CreateInstanceRequestPortsInnerProtocolEnum[keyof typeof CreateInstanceRequestPortsInnerProtocolEnum];


/**
 * Check if a given object implements the CreateInstanceRequestPortsInner interface.
 */
export function instanceOfCreateInstanceRequestPortsInner(value: object): value is CreateInstanceRequestPortsInner {
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    return true;
}

export function CreateInstanceRequestPortsInnerFromJSON(json: any): CreateInstanceRequestPortsInner {
    return CreateInstanceRequestPortsInnerFromJSONTyped(json, false);
}

export function CreateInstanceRequestPortsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInstanceRequestPortsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'port': json['port'],
        'protocol': json['protocol'],
        'primary': json['primary'] == null ? undefined : json['primary'],
    };
}

export function CreateInstanceRequestPortsInnerToJSON(json: any): CreateInstanceRequestPortsInner {
    return CreateInstanceRequestPortsInnerToJSONTyped(json, false);
}

export function CreateInstanceRequestPortsInnerToJSONTyped(value?: CreateInstanceRequestPortsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'port': value['port'],
        'protocol': value['protocol'],
        'primary': value['primary'],
    };
}

