/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookEndpointRequest
 */
export interface CreateWebhookEndpointRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpointRequest
     */
    url: string;
    /**
     * 
     * @type {Array<CreateWebhookEndpointRequestEventTypesEnum>}
     * @memberof CreateWebhookEndpointRequest
     */
    eventTypes: Array<CreateWebhookEndpointRequestEventTypesEnum>;
}


/**
 * @export
 */
export const CreateWebhookEndpointRequestEventTypesEnum = {
    InstanceCreating: 'instance.creating',
    InstanceRunning: 'instance.running',
    InstanceTerminated: 'instance.terminated',
    InstanceFailed: 'instance.failed',
    VideoCompleted: 'video.completed',
    VideoFailed: 'video.failed'
} as const;
export type CreateWebhookEndpointRequestEventTypesEnum = typeof CreateWebhookEndpointRequestEventTypesEnum[keyof typeof CreateWebhookEndpointRequestEventTypesEnum];


/**
 * Check if a given object implements the CreateWebhookEndpointRequest interface.
 */
export function instanceOfCreateWebhookEndpointRequest(value: object): value is CreateWebhookEndpointRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    if ((!('eventTypes' in (value as Record<string, any>)) && !('event_types' in (value as Record<string, any>))) || ((value as Record<string, any>)['eventTypes'] === undefined && (value as Record<string, any>)['event_types'] === undefined)) return false;
    return true;
}

export function CreateWebhookEndpointRequestFromJSON(json: any): CreateWebhookEndpointRequest {
    return CreateWebhookEndpointRequestFromJSONTyped(json, false);
}

export function CreateWebhookEndpointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookEndpointRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'eventTypes': json['event_types'],
    };
}

export function CreateWebhookEndpointRequestToJSON(json: any): CreateWebhookEndpointRequest {
    return CreateWebhookEndpointRequestToJSONTyped(json, false);
}

export function CreateWebhookEndpointRequestToJSONTyped(value?: CreateWebhookEndpointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'event_types': value['eventTypes'],
    };
}

