/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCryptoDepositRequest
 */
export interface CreateCryptoDepositRequest {
    /**
     * Amount to deposit in USD cents. Must be at least the configured minimum (500 = $5.00 by default).
     * 
     * @type {number}
     * @memberof CreateCryptoDepositRequest
     */
    amountCents: number;
    /**
     * 
     * @type {CreateCryptoDepositRequestChainEnum}
     * @memberof CreateCryptoDepositRequest
     */
    chain: CreateCryptoDepositRequestChainEnum;
    /**
     * 
     * @type {CreateCryptoDepositRequestAssetEnum}
     * @memberof CreateCryptoDepositRequest
     */
    asset: CreateCryptoDepositRequestAssetEnum;
}


/**
 * @export
 */
export const CreateCryptoDepositRequestChainEnum = {
    Ethereum: 'ethereum',
    Base: 'base',
    Arbitrum: 'arbitrum',
    Polygon: 'polygon',
    Solana: 'solana'
} as const;
export type CreateCryptoDepositRequestChainEnum = typeof CreateCryptoDepositRequestChainEnum[keyof typeof CreateCryptoDepositRequestChainEnum];

/**
 * @export
 */
export const CreateCryptoDepositRequestAssetEnum = {
    Usdc: 'usdc',
    Usdt: 'usdt'
} as const;
export type CreateCryptoDepositRequestAssetEnum = typeof CreateCryptoDepositRequestAssetEnum[keyof typeof CreateCryptoDepositRequestAssetEnum];


/**
 * Check if a given object implements the CreateCryptoDepositRequest interface.
 */
export function instanceOfCreateCryptoDepositRequest(value: object): value is CreateCryptoDepositRequest {
    if ((!('amountCents' in (value as Record<string, any>)) && !('amount_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['amountCents'] === undefined && (value as Record<string, any>)['amount_cents'] === undefined)) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('asset' in value) || value['asset'] === undefined) return false;
    return true;
}

export function CreateCryptoDepositRequestFromJSON(json: any): CreateCryptoDepositRequest {
    return CreateCryptoDepositRequestFromJSONTyped(json, false);
}

export function CreateCryptoDepositRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCryptoDepositRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'chain': json['chain'],
        'asset': json['asset'],
    };
}

export function CreateCryptoDepositRequestToJSON(json: any): CreateCryptoDepositRequest {
    return CreateCryptoDepositRequestToJSONTyped(json, false);
}

export function CreateCryptoDepositRequestToJSONTyped(value?: CreateCryptoDepositRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'chain': value['chain'],
        'asset': value['asset'],
    };
}

