/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFineTuningJobRequestMethodLora
 */
export interface CreateFineTuningJobRequestMethodLora {
    /**
     * 
     * @type {number}
     * @memberof CreateFineTuningJobRequestMethodLora
     */
    loraR?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateFineTuningJobRequestMethodLora
     */
    loraAlpha?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateFineTuningJobRequestMethodLora
     */
    loraDropout?: number;
}

/**
 * Check if a given object implements the CreateFineTuningJobRequestMethodLora interface.
 */
export function instanceOfCreateFineTuningJobRequestMethodLora(value: object): value is CreateFineTuningJobRequestMethodLora {
    return true;
}

export function CreateFineTuningJobRequestMethodLoraFromJSON(json: any): CreateFineTuningJobRequestMethodLora {
    return CreateFineTuningJobRequestMethodLoraFromJSONTyped(json, false);
}

export function CreateFineTuningJobRequestMethodLoraFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFineTuningJobRequestMethodLora {
    if (json == null) {
        return json;
    }
    return {
        
        'loraR': json['lora_r'] == null ? undefined : json['lora_r'],
        'loraAlpha': json['lora_alpha'] == null ? undefined : json['lora_alpha'],
        'loraDropout': json['lora_dropout'] == null ? undefined : json['lora_dropout'],
    };
}

export function CreateFineTuningJobRequestMethodLoraToJSON(json: any): CreateFineTuningJobRequestMethodLora {
    return CreateFineTuningJobRequestMethodLoraToJSONTyped(json, false);
}

export function CreateFineTuningJobRequestMethodLoraToJSONTyped(value?: CreateFineTuningJobRequestMethodLora | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lora_r': value['loraR'],
        'lora_alpha': value['loraAlpha'],
        'lora_dropout': value['loraDropout'],
    };
}

