/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFineTuningJobRequestGpuai } from './CreateFineTuningJobRequestGpuai';
import {
    CreateFineTuningJobRequestGpuaiFromJSON,
    CreateFineTuningJobRequestGpuaiFromJSONTyped,
    CreateFineTuningJobRequestGpuaiToJSON,
    CreateFineTuningJobRequestGpuaiToJSONTyped,
} from './CreateFineTuningJobRequestGpuai';
import type { CreateFineTuningJobRequestMethod } from './CreateFineTuningJobRequestMethod';
import {
    CreateFineTuningJobRequestMethodFromJSON,
    CreateFineTuningJobRequestMethodFromJSONTyped,
    CreateFineTuningJobRequestMethodToJSON,
    CreateFineTuningJobRequestMethodToJSONTyped,
} from './CreateFineTuningJobRequestMethod';

/**
 * Request body for POST /fine_tuning/jobs. The `method` object carries the Axolotl LoRA/QLoRA hyperparameters; `gpuai` is a native extension for the optional budget cap and GPU preference. The backing training environment (image, GPU provider) is an internal orchestration detail and is intentionally absent from this schema (privacy-by-omission, D6).
 * @export
 * @interface CreateFineTuningJobRequest
 */
export interface CreateFineTuningJobRequest {
    /**
     * An operator-curated tunable base model id.
     * @type {string}
     * @memberof CreateFineTuningJobRequest
     */
    model: string;
    /**
     * The id of a previously uploaded file (purpose=fine-tune).
     * @type {string}
     * @memberof CreateFineTuningJobRequest
     */
    trainingFile: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFineTuningJobRequest
     */
    suffix?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateFineTuningJobRequest
     */
    seed?: number;
    /**
     * 
     * @type {CreateFineTuningJobRequestMethod}
     * @memberof CreateFineTuningJobRequest
     */
    method: CreateFineTuningJobRequestMethod;
    /**
     * 
     * @type {CreateFineTuningJobRequestGpuai}
     * @memberof CreateFineTuningJobRequest
     */
    gpuai?: CreateFineTuningJobRequestGpuai;
}

/**
 * Check if a given object implements the CreateFineTuningJobRequest interface.
 */
export function instanceOfCreateFineTuningJobRequest(value: object): value is CreateFineTuningJobRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if ((!('trainingFile' in (value as Record<string, any>)) && !('training_file' in (value as Record<string, any>))) || ((value as Record<string, any>)['trainingFile'] === undefined && (value as Record<string, any>)['training_file'] === undefined)) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    return true;
}

export function CreateFineTuningJobRequestFromJSON(json: any): CreateFineTuningJobRequest {
    return CreateFineTuningJobRequestFromJSONTyped(json, false);
}

export function CreateFineTuningJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFineTuningJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'trainingFile': json['training_file'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'method': CreateFineTuningJobRequestMethodFromJSON(json['method']),
        'gpuai': json['gpuai'] == null ? undefined : CreateFineTuningJobRequestGpuaiFromJSON(json['gpuai']),
    };
}

export function CreateFineTuningJobRequestToJSON(json: any): CreateFineTuningJobRequest {
    return CreateFineTuningJobRequestToJSONTyped(json, false);
}

export function CreateFineTuningJobRequestToJSONTyped(value?: CreateFineTuningJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'training_file': value['trainingFile'],
        'suffix': value['suffix'],
        'seed': value['seed'],
        'method': CreateFineTuningJobRequestMethodToJSON(value['method']),
        'gpuai': CreateFineTuningJobRequestGpuaiToJSON(value['gpuai']),
    };
}

