/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateInstanceRequestPortsInner } from './CreateInstanceRequestPortsInner';
import {
    CreateInstanceRequestPortsInnerFromJSON,
    CreateInstanceRequestPortsInnerFromJSONTyped,
    CreateInstanceRequestPortsInnerToJSON,
    CreateInstanceRequestPortsInnerToJSONTyped,
} from './CreateInstanceRequestPortsInner';

/**
 * 
 * @export
 * @interface CreateInstanceRequest
 */
export interface CreateInstanceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    gpuType: string;
    /**
     * 
     * @type {number}
     * @memberof CreateInstanceRequest
     */
    gpuCount: number;
    /**
     * 
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    region?: string;
    /**
     * 
     * @type {CreateInstanceRequestTierEnum}
     * @memberof CreateInstanceRequest
     */
    tier: CreateInstanceRequestTierEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateInstanceRequest
     */
    sshKeyIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    name?: string;
    /**
     * maximum acceptable whole-instance hourly price (catalog price)
     * @type {number}
     * @memberof CreateInstanceRequest
     */
    maxPricePerHour?: number;
    /**
     * The retail $/hr the caller displayed to the user before launch. A catalog row is a quote, not a booking, and pinning an offering fixes which machine is placed but not its rate. If the launch-time price exceeds this by more than $0.01 the launch fails with `price_changed` carrying the new price instead of proceeding at the higher price; omit to accept the launch-time price (previous behavior). Refusal only — it is never read as consent, so it can neither raise what you are charged nor widen what may be bought on your behalf. Use max_price_per_hour to bound spend.
     * @type {number}
     * @memberof CreateInstanceRequest
     */
    viewedPricePerHour?: number;
    /**
     * Deploy a curated application template (e.g. comfyui, vllm). When set, gpu_type may be omitted — the cheapest eligible GPU is auto-selected. For templates serving a Hugging Face model via env.MODEL (vllm, sglang), the model's published weights size is checked against the GPU's VRAM at submit time: an oversized model on an explicit gpu_type returns 422 `model_too_large` (auto-select instead raises its VRAM floor to the estimate, and 422s only when no available GPU fits). Gated/private/unknown repos are never blocked — the deploy proceeds and the 202 carries a `warnings` entry. Separately, an explicit gpu_type whose VRAM is below the template's own `min_vram_gb` returns 422 `gpu_vram_too_small`, naming the floor, the type's VRAM and the compatible GPU types. Auto-select is unaffected — it already filters by the floor.
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    templateId?: string;
    /**
     * Launch environment. Omit for the provider default (the GPU.ai Certified Image where supported). Accepted values: `certified` (the GPU.ai Certified base image), `certified:<framework>` (a framework layer — see GET /v1/environments for the roster, e.g. `certified:pytorch`), `certified:<framework>@<version>` (a specific framework version, e.g. `certified:pytorch@2.13`), `raw_vm` (root VM, provider default OS), `raw_vm:<os>` (root VM with a chosen OS, e.g. `raw_vm:ubuntu-24.04`), or `provider_template` (the provider's own image). A well-formed value the placed machine can't serve returns 422 `environment_unavailable`.
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    environment?: string;
    /**
     * Pin the launch to one exact offering (from GET /v1/pricing) so the engine never substitutes a pricier one. If that offering is gone, the launch fails explicitly rather than silently placing elsewhere.
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    offeringId?: string;
    /**
     * Requested instance filesystem size in GB. Omit for the platform default (100 GB), which never narrows placement. Setting it is a hard requirement: placement narrows to capacity that can honor it (see `disk_configurable` on GET /v1/pricing), and a request no offering of the gpu_type can honor returns 422 `disk_unavailable` rather than launching with a different size. When the launch also pins an exact `offering_id`, a disk_gb larger than that offering's displayed `storage_gb` returns 422 `disk_exceeds_offering` rather than launching with a clamped filesystem. Disk beyond the included allowance (100 GB) is billed at the offering's `disk_price_per_gb_hour` (GET /v1/pricing), folded into the instance's single hourly rate. Bounds: at least 10, at most the platform ceiling (currently 1000) — outside them returns 422 `validation_failed`.
     * @type {number}
     * @memberof CreateInstanceRequest
     */
    diskGb?: number;
    /**
     * Environment variables. With `template_id`: per-deploy overrides — only keys the template marks user_overridable are accepted (others 422), and secret values are redacted from operation metadata. With `image`: plain container env vars — keys must be POSIX names and the platform's reserved namespace (`PUBLIC_KEY`, `GPUAI_*`) is refused (422).
     * @type {{ [key: string]: string; }}
     * @memberof CreateInstanceRequest
     */
    env?: { [key: string]: string; };
    /**
     * Launch from your own container image, e.g. `pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel` or `ghcr.io/acme/trainer:v1`. The image must be publicly pullable (private registries are not yet supported) and provide linux/amd64 — both are verified synchronously before anything is provisioned: an unknown image returns 422 `image_unavailable` and a registry outage 502 `registry_unreachable`, with no operation created and nothing billed. The launch is pinned to the exact manifest digest verified, so a tag re-push cannot change what boots. After SSH/tunnel setup the image's own ENTRYPOINT/CMD is started (its output is in /var/log/gpuai-entrypoint.log on the instance); an image with neither is a plain SSH environment. Placement prefers container-native capacity (the image runs natively; SSH lands inside it) and falls back to VM capacity (the image runs as a container beside the host's SSH — inspect with `docker logs gpuai-workload`); private images stay container-native. A gpu_type with no capable capacity returns 422 `image_unavailable`. Mutually exclusive with `template_id` and `environment` (422). A malformed reference (bad charset, localhost/private-IP registry) returns 400.
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    image?: string;
    /**
     * Stored registry-credential id (POST /v1/registry-credentials) for pulling a PRIVATE `image`. The credential's registry must match the image's registry (422 otherwise); wrong logins fail the pre-flight with 422 `image_unavailable` before anything is provisioned. Requires `image`.
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    registryCredentialId?: string;
    /**
     * Override the image's ENTRYPOINT (docker semantics — also drops the image CMD unless `cmd` is given). Omit to use the image's own. At most 32 arguments / 4KB. Requires `image`.
     * @type {Array<string>}
     * @memberof CreateInstanceRequest
     */
    entrypoint?: Array<string>;
    /**
     * Override the image's CMD. Omit to use the image's own (or none, when `entrypoint` is overridden). Requires `image`.
     * @type {Array<string>}
     * @memberof CreateInstanceRequest
     */
    cmd?: Array<string>;
    /**
     * Container ports to expose on a custom-image launch (at most 10; port 22 is reserved). At most one entry may be `primary` — it must be http and is served at the instance's app URL (`https://<id>.apps.gpu.ai`) behind the per-instance basic-auth login. Requires `image`.
     * @type {Array<CreateInstanceRequestPortsInner>}
     * @memberof CreateInstanceRequest
     */
    ports?: Array<CreateInstanceRequestPortsInner>;
}


/**
 * @export
 */
export const CreateInstanceRequestTierEnum = {
    Spot: 'spot',
    OnDemand: 'on_demand'
} as const;
export type CreateInstanceRequestTierEnum = typeof CreateInstanceRequestTierEnum[keyof typeof CreateInstanceRequestTierEnum];


/**
 * Check if a given object implements the CreateInstanceRequest interface.
 */
export function instanceOfCreateInstanceRequest(value: object): value is CreateInstanceRequest {
    if ((!('gpuType' in (value as Record<string, any>)) && !('gpu_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuType'] === undefined && (value as Record<string, any>)['gpu_type'] === undefined)) return false;
    if ((!('gpuCount' in (value as Record<string, any>)) && !('gpu_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuCount'] === undefined && (value as Record<string, any>)['gpu_count'] === undefined)) return false;
    if (!('tier' in value) || value['tier'] === undefined) return false;
    return true;
}

export function CreateInstanceRequestFromJSON(json: any): CreateInstanceRequest {
    return CreateInstanceRequestFromJSONTyped(json, false);
}

export function CreateInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInstanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'gpuType': json['gpu_type'],
        'gpuCount': json['gpu_count'],
        'region': json['region'] == null ? undefined : json['region'],
        'tier': json['tier'],
        'sshKeyIds': json['ssh_key_ids'] == null ? undefined : json['ssh_key_ids'],
        'name': json['name'] == null ? undefined : json['name'],
        'maxPricePerHour': json['max_price_per_hour'] == null ? undefined : json['max_price_per_hour'],
        'viewedPricePerHour': json['viewed_price_per_hour'] == null ? undefined : json['viewed_price_per_hour'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'environment': json['environment'] == null ? undefined : json['environment'],
        'offeringId': json['offering_id'] == null ? undefined : json['offering_id'],
        'diskGb': json['disk_gb'] == null ? undefined : json['disk_gb'],
        'env': json['env'] == null ? undefined : json['env'],
        'image': json['image'] == null ? undefined : json['image'],
        'registryCredentialId': json['registry_credential_id'] == null ? undefined : json['registry_credential_id'],
        'entrypoint': json['entrypoint'] == null ? undefined : json['entrypoint'],
        'cmd': json['cmd'] == null ? undefined : json['cmd'],
        'ports': json['ports'] == null ? undefined : ((json['ports'] as Array<any>).map(CreateInstanceRequestPortsInnerFromJSON)),
    };
}

export function CreateInstanceRequestToJSON(json: any): CreateInstanceRequest {
    return CreateInstanceRequestToJSONTyped(json, false);
}

export function CreateInstanceRequestToJSONTyped(value?: CreateInstanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gpu_type': value['gpuType'],
        'gpu_count': value['gpuCount'],
        'region': value['region'],
        'tier': value['tier'],
        'ssh_key_ids': value['sshKeyIds'],
        'name': value['name'],
        'max_price_per_hour': value['maxPricePerHour'],
        'viewed_price_per_hour': value['viewedPricePerHour'],
        'template_id': value['templateId'],
        'environment': value['environment'],
        'offering_id': value['offeringId'],
        'disk_gb': value['diskGb'],
        'env': value['env'],
        'image': value['image'],
        'registry_credential_id': value['registryCredentialId'],
        'entrypoint': value['entrypoint'],
        'cmd': value['cmd'],
        'ports': value['ports'] == null ? undefined : ((value['ports'] as Array<any>).map(CreateInstanceRequestPortsInnerToJSON)),
    };
}

