/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFineTuningJobRequestMethodLora } from './CreateFineTuningJobRequestMethodLora';
import {
    CreateFineTuningJobRequestMethodLoraFromJSON,
    CreateFineTuningJobRequestMethodLoraFromJSONTyped,
    CreateFineTuningJobRequestMethodLoraToJSON,
    CreateFineTuningJobRequestMethodLoraToJSONTyped,
} from './CreateFineTuningJobRequestMethodLora';

/**
 * 
 * @export
 * @interface CreateFineTuningJobRequestMethod
 */
export interface CreateFineTuningJobRequestMethod {
    /**
     * 
     * @type {CreateFineTuningJobRequestMethodTypeEnum}
     * @memberof CreateFineTuningJobRequestMethod
     */
    type: CreateFineTuningJobRequestMethodTypeEnum;
    /**
     * 
     * @type {CreateFineTuningJobRequestMethodLora}
     * @memberof CreateFineTuningJobRequestMethod
     */
    lora?: CreateFineTuningJobRequestMethodLora;
}


/**
 * @export
 */
export const CreateFineTuningJobRequestMethodTypeEnum = {
    Lora: 'lora',
    Qlora: 'qlora'
} as const;
export type CreateFineTuningJobRequestMethodTypeEnum = typeof CreateFineTuningJobRequestMethodTypeEnum[keyof typeof CreateFineTuningJobRequestMethodTypeEnum];


/**
 * Check if a given object implements the CreateFineTuningJobRequestMethod interface.
 */
export function instanceOfCreateFineTuningJobRequestMethod(value: object): value is CreateFineTuningJobRequestMethod {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateFineTuningJobRequestMethodFromJSON(json: any): CreateFineTuningJobRequestMethod {
    return CreateFineTuningJobRequestMethodFromJSONTyped(json, false);
}

export function CreateFineTuningJobRequestMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFineTuningJobRequestMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'lora': json['lora'] == null ? undefined : CreateFineTuningJobRequestMethodLoraFromJSON(json['lora']),
    };
}

export function CreateFineTuningJobRequestMethodToJSON(json: any): CreateFineTuningJobRequestMethod {
    return CreateFineTuningJobRequestMethodToJSONTyped(json, false);
}

export function CreateFineTuningJobRequestMethodToJSONTyped(value?: CreateFineTuningJobRequestMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'lora': CreateFineTuningJobRequestMethodLoraToJSON(value['lora']),
    };
}

