/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A stablecoin deposit. Mirrors the Go DTO field for field. Like that struct, this schema deliberately has NO payment-processor property — the processor is an implementation detail and is structurally absent from the customer contract, not merely filtered out.
 * 
 * @export
 * @interface CryptoDeposit
 */
export interface CryptoDeposit {
    /**
     * 
     * @type {string}
     * @memberof CryptoDeposit
     */
    depositId: string;
    /**
     * Lifecycle state: created, detected, confirming, settled, screening, held_screening, credited, credited_underpaid, credited_overpaid, expired, expired_received, failed, failed_screening.
     * 
     * @type {string}
     * @memberof CryptoDeposit
     */
    status: string;
    /**
     * 
     * @type {CryptoDepositChainEnum}
     * @memberof CryptoDeposit
     */
    chain: CryptoDepositChainEnum;
    /**
     * 
     * @type {CryptoDepositAssetEnum}
     * @memberof CryptoDeposit
     */
    asset: CryptoDepositAssetEnum;
    /**
     * The address to send funds to. Unique to this deposit.
     * @type {string}
     * @memberof CryptoDeposit
     */
    payAddress?: string;
    /**
     * The exact token amount to send, as a decimal string (never a number — the value must not round-trip through a float).
     * 
     * @type {string}
     * @memberof CryptoDeposit
     */
    payAmount?: string;
    /**
     * The amount requested, in USD cents. Never the settled or credited value.
     * @type {number}
     * @memberof CryptoDeposit
     */
    amountUsdCents: number;
    /**
     * USD cents actually credited to the balance. Absent until credited.
     * @type {number}
     * @memberof CryptoDeposit
     */
    creditedCents?: number;
    /**
     * 
     * @type {string}
     * @memberof CryptoDeposit
     */
    txHash?: string;
    /**
     * RFC3339 UTC. After this, send nothing to pay_address.
     * @type {Date}
     * @memberof CryptoDeposit
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CryptoDeposit
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CryptoDepositChainEnum = {
    Ethereum: 'ethereum',
    Base: 'base',
    Arbitrum: 'arbitrum',
    Polygon: 'polygon',
    Solana: 'solana'
} as const;
export type CryptoDepositChainEnum = typeof CryptoDepositChainEnum[keyof typeof CryptoDepositChainEnum];

/**
 * @export
 */
export const CryptoDepositAssetEnum = {
    Usdc: 'usdc',
    Usdt: 'usdt'
} as const;
export type CryptoDepositAssetEnum = typeof CryptoDepositAssetEnum[keyof typeof CryptoDepositAssetEnum];


/**
 * Check if a given object implements the CryptoDeposit interface.
 */
export function instanceOfCryptoDeposit(value: object): value is CryptoDeposit {
    if ((!('depositId' in (value as Record<string, any>)) && !('deposit_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['depositId'] === undefined && (value as Record<string, any>)['deposit_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('asset' in value) || value['asset'] === undefined) return false;
    if ((!('amountUsdCents' in (value as Record<string, any>)) && !('amount_usd_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['amountUsdCents'] === undefined && (value as Record<string, any>)['amount_usd_cents'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function CryptoDepositFromJSON(json: any): CryptoDeposit {
    return CryptoDepositFromJSONTyped(json, false);
}

export function CryptoDepositFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoDeposit {
    if (json == null) {
        return json;
    }
    return {
        
        'depositId': json['deposit_id'],
        'status': json['status'],
        'chain': json['chain'],
        'asset': json['asset'],
        'payAddress': json['pay_address'] == null ? undefined : json['pay_address'],
        'payAmount': json['pay_amount'] == null ? undefined : json['pay_amount'],
        'amountUsdCents': json['amount_usd_cents'],
        'creditedCents': json['credited_cents'] == null ? undefined : json['credited_cents'],
        'txHash': json['tx_hash'] == null ? undefined : json['tx_hash'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function CryptoDepositToJSON(json: any): CryptoDeposit {
    return CryptoDepositToJSONTyped(json, false);
}

export function CryptoDepositToJSONTyped(value?: CryptoDeposit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deposit_id': value['depositId'],
        'status': value['status'],
        'chain': value['chain'],
        'asset': value['asset'],
        'pay_address': value['payAddress'],
        'pay_amount': value['payAmount'],
        'amount_usd_cents': value['amountUsdCents'],
        'credited_cents': value['creditedCents'],
        'tx_hash': value['txHash'],
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
    };
}

