/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type EmbeddingsRequestInput
 * Text to embed: either a single string or an array of up to 2048 strings. Token-id arrays are not supported. The per-request ceiling is bounded so the response stays under 64 MiB — about 680 inputs at 4096 dimensions, fewer at a larger `dimensions` value; an over-limit batch is rejected with 400 invalid_request_error whose message states the limit, before any processing.
 * @export
 */
export type EmbeddingsRequestInput = Array<string> | string;

export function EmbeddingsRequestInputFromJSON(json: any): EmbeddingsRequestInput {
    return EmbeddingsRequestInputFromJSONTyped(json, false);
}

export function EmbeddingsRequestInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingsRequestInput {
    if (json == null) {
        return json;
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'string')) {
            return json;
        }
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function EmbeddingsRequestInputToJSON(json: any): any {
    return EmbeddingsRequestInputToJSONTyped(json, false);
}

export function EmbeddingsRequestInputToJSONTyped(value?: EmbeddingsRequestInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'string')) {
            return value;
        }
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

