/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Embedding } from './Embedding';
import {
    EmbeddingFromJSON,
    EmbeddingFromJSONTyped,
    EmbeddingToJSON,
    EmbeddingToJSONTyped,
} from './Embedding';
import type { EmbeddingsUsage } from './EmbeddingsUsage';
import {
    EmbeddingsUsageFromJSON,
    EmbeddingsUsageFromJSONTyped,
    EmbeddingsUsageToJSON,
    EmbeddingsUsageToJSONTyped,
} from './EmbeddingsUsage';

/**
 * 
 * @export
 * @interface EmbeddingsResponse
 */
export interface EmbeddingsResponse {
    /**
     * 
     * @type {EmbeddingsResponseObjectEnum}
     * @memberof EmbeddingsResponse
     */
    object: EmbeddingsResponseObjectEnum;
    /**
     * 
     * @type {Array<Embedding>}
     * @memberof EmbeddingsResponse
     */
    data: Array<Embedding>;
    /**
     * Canonical (gpuai/...) model id, NEVER the upstream identifier.
     * @type {string}
     * @memberof EmbeddingsResponse
     */
    model: string;
    /**
     * 
     * @type {EmbeddingsUsage}
     * @memberof EmbeddingsResponse
     */
    usage: EmbeddingsUsage;
}


/**
 * @export
 */
export const EmbeddingsResponseObjectEnum = {
    List: 'list'
} as const;
export type EmbeddingsResponseObjectEnum = typeof EmbeddingsResponseObjectEnum[keyof typeof EmbeddingsResponseObjectEnum];


/**
 * Check if a given object implements the EmbeddingsResponse interface.
 */
export function instanceOfEmbeddingsResponse(value: object): value is EmbeddingsResponse {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'list') return false;
    
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    return true;
}

export function EmbeddingsResponseFromJSON(json: any): EmbeddingsResponse {
    return EmbeddingsResponseFromJSONTyped(json, false);
}

export function EmbeddingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(EmbeddingFromJSON)),
        'model': json['model'],
        'usage': EmbeddingsUsageFromJSON(json['usage']),
    };
}

export function EmbeddingsResponseToJSON(json: any): EmbeddingsResponse {
    return EmbeddingsResponseToJSONTyped(json, false);
}

export function EmbeddingsResponseToJSONTyped(value?: EmbeddingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(EmbeddingToJSON)),
        'model': value['model'],
        'usage': EmbeddingsUsageToJSON(value['usage']),
    };
}

