/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmbeddingsRequestInput } from './EmbeddingsRequestInput';
import {
    EmbeddingsRequestInputFromJSON,
    EmbeddingsRequestInputFromJSONTyped,
    EmbeddingsRequestInputToJSON,
    EmbeddingsRequestInputToJSONTyped,
} from './EmbeddingsRequestInput';

/**
 * 
 * @export
 * @interface EmbeddingsRequest
 */
export interface EmbeddingsRequest {
    /**
     * Canonical embedding model id, e.g. "gpuai/qwen3-embedding-8b".
     * @type {string}
     * @memberof EmbeddingsRequest
     */
    model: string;
    /**
     * 
     * @type {EmbeddingsRequestInput}
     * @memberof EmbeddingsRequest
     */
    input: EmbeddingsRequestInput;
    /**
     * Only "float" is supported. A value of "base64" is rejected with invalid_request_error / unsupported_parameter.
     * @type {EmbeddingsRequestEncodingFormatEnum}
     * @memberof EmbeddingsRequest
     */
    encodingFormat?: EmbeddingsRequestEncodingFormatEnum;
    /**
     * Requested output dimensionality, for models that support truncated (Matryoshka) embeddings. Passed through to the model when set.
     * @type {number}
     * @memberof EmbeddingsRequest
     */
    dimensions?: number;
    /**
     * Opaque end-user identifier for abuse tracing. Optional.
     * @type {string}
     * @memberof EmbeddingsRequest
     */
    user?: string;
}


/**
 * @export
 */
export const EmbeddingsRequestEncodingFormatEnum = {
    Float: 'float'
} as const;
export type EmbeddingsRequestEncodingFormatEnum = typeof EmbeddingsRequestEncodingFormatEnum[keyof typeof EmbeddingsRequestEncodingFormatEnum];


/**
 * Check if a given object implements the EmbeddingsRequest interface.
 */
export function instanceOfEmbeddingsRequest(value: object): value is EmbeddingsRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function EmbeddingsRequestFromJSON(json: any): EmbeddingsRequest {
    return EmbeddingsRequestFromJSONTyped(json, false);
}

export function EmbeddingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'input': EmbeddingsRequestInputFromJSON(json['input']),
        'encodingFormat': json['encoding_format'] == null ? undefined : json['encoding_format'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function EmbeddingsRequestToJSON(json: any): EmbeddingsRequest {
    return EmbeddingsRequestToJSONTyped(json, false);
}

export function EmbeddingsRequestToJSONTyped(value?: EmbeddingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'input': EmbeddingsRequestInputToJSON(value['input']),
        'encoding_format': value['encodingFormat'],
        'dimensions': value['dimensions'],
        'user': value['user'],
    };
}

