/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Embedding
 */
export interface Embedding {
    /**
     * 
     * @type {EmbeddingObjectEnum}
     * @memberof Embedding
     */
    object: EmbeddingObjectEnum;
    /**
     * The embedding vector as 32-bit floats.
     * @type {Array<number>}
     * @memberof Embedding
     */
    embedding: Array<number>;
    /**
     * Position of this vector's input in the request.
     * @type {number}
     * @memberof Embedding
     */
    index: number;
}


/**
 * @export
 */
export const EmbeddingObjectEnum = {
    Embedding: 'embedding'
} as const;
export type EmbeddingObjectEnum = typeof EmbeddingObjectEnum[keyof typeof EmbeddingObjectEnum];


/**
 * Check if a given object implements the Embedding interface.
 */
export function instanceOfEmbedding(value: object): value is Embedding {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'embedding') return false;
    
    if (!('embedding' in value) || value['embedding'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    return true;
}

export function EmbeddingFromJSON(json: any): Embedding {
    return EmbeddingFromJSONTyped(json, false);
}

export function EmbeddingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Embedding {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'embedding': json['embedding'],
        'index': json['index'],
    };
}

export function EmbeddingToJSON(json: any): Embedding {
    return EmbeddingToJSONTyped(json, false);
}

export function EmbeddingToJSONTyped(value?: Embedding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'embedding': value['embedding'],
        'index': value['index'],
    };
}

