/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IncludeItem } from './IncludeItem';
import {
    IncludeItemFromJSON,
    IncludeItemFromJSONTyped,
    IncludeItemToJSON,
    IncludeItemToJSONTyped,
} from './IncludeItem';
import type { VMImage } from './VMImage';
import {
    VMImageFromJSON,
    VMImageFromJSONTyped,
    VMImageToJSON,
    VMImageToJSONTyped,
} from './VMImage';
import type { FrameworkVersion } from './FrameworkVersion';
import {
    FrameworkVersionFromJSON,
    FrameworkVersionFromJSONTyped,
    FrameworkVersionToJSON,
    FrameworkVersionToJSONTyped,
} from './FrameworkVersion';

/**
 * The launch environment catalog (GET /v1/environments).
 * @export
 * @interface Environments
 */
export interface Environments {
    /**
     * Certified framework ids whose images are fully published — the `certified:<framework>` options.
     * @type {Array<string>}
     * @memberof Environments
     */
    frameworks: Array<string>;
    /**
     * The version picker roster: framework id → selectable versions (the `certified:<framework>@<version>` grammar). A framework absent here has one build per CUDA variant. `variant` is the CUDA variant a version targets — only offerings whose GPU maps to it can run it.
     * @type {{ [key: string]: Array<FrameworkVersion>; }}
     * @memberof Environments
     */
    versions: { [key: string]: Array<FrameworkVersion>; };
    /**
     * "What's included" software lists: framework id (roster ids plus "base") → CUDA variant ("cuda128"/"cuda124") → components.
     * @type {{ [key: string]: { [key: string]: Array<IncludeItem>; }; }}
     * @memberof Environments
     */
    includes: { [key: string]: { [key: string]: Array<IncludeItem>; }; };
    /**
     * The raw-VM OS catalog (the `raw_vm:<os>` grammar), keyed by os id.
     * @type {{ [key: string]: VMImage; }}
     * @memberof Environments
     */
    vmImages: { [key: string]: VMImage; };
}

/**
 * Check if a given object implements the Environments interface.
 */
export function instanceOfEnvironments(value: object): value is Environments {
    if (!('frameworks' in value) || value['frameworks'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    if (!('includes' in value) || value['includes'] === undefined) return false;
    if ((!('vmImages' in (value as Record<string, any>)) && !('vm_images' in (value as Record<string, any>))) || ((value as Record<string, any>)['vmImages'] === undefined && (value as Record<string, any>)['vm_images'] === undefined)) return false;
    return true;
}

export function EnvironmentsFromJSON(json: any): Environments {
    return EnvironmentsFromJSONTyped(json, false);
}

export function EnvironmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Environments {
    if (json == null) {
        return json;
    }
    return {
        
        'frameworks': json['frameworks'],
        'versions': json['versions'],
        'includes': json['includes'],
        'vmImages': (mapValues(json['vm_images'], VMImageFromJSON)),
    };
}

export function EnvironmentsToJSON(json: any): Environments {
    return EnvironmentsToJSONTyped(json, false);
}

export function EnvironmentsToJSONTyped(value?: Environments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'frameworks': value['frameworks'],
        'versions': value['versions'],
        'includes': value['includes'],
        'vm_images': (mapValues(value['vmImages'], VMImageToJSON)),
    };
}

