/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An uploaded file object. The storage location is an internal detail and is intentionally absent from this schema (privacy-by-omission, D6).
 * @export
 * @interface FileObject
 */
export interface FileObject {
    /**
     * 
     * @type {string}
     * @memberof FileObject
     */
    id: string;
    /**
     * 
     * @type {FileObjectObjectEnum}
     * @memberof FileObject
     */
    object: FileObjectObjectEnum;
    /**
     * 
     * @type {number}
     * @memberof FileObject
     */
    bytes: number;
    /**
     * Unix timestamp (seconds).
     * @type {number}
     * @memberof FileObject
     */
    createdAt: number;
    /**
     * 
     * @type {string}
     * @memberof FileObject
     */
    filename: string;
    /**
     * 
     * @type {FileObjectPurposeEnum}
     * @memberof FileObject
     */
    purpose: FileObjectPurposeEnum;
}


/**
 * @export
 */
export const FileObjectObjectEnum = {
    File: 'file'
} as const;
export type FileObjectObjectEnum = typeof FileObjectObjectEnum[keyof typeof FileObjectObjectEnum];

/**
 * @export
 */
export const FileObjectPurposeEnum = {
    FineTune: 'fine-tune'
} as const;
export type FileObjectPurposeEnum = typeof FileObjectPurposeEnum[keyof typeof FileObjectPurposeEnum];


/**
 * Check if a given object implements the FileObject interface.
 */
export function instanceOfFileObject(value: object): value is FileObject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'file') return false;
    
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (value['purpose'] !== 'fine-tune') return false;
    
    return true;
}

export function FileObjectFromJSON(json: any): FileObject {
    return FileObjectFromJSONTyped(json, false);
}

export function FileObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'bytes': json['bytes'],
        'createdAt': json['created_at'],
        'filename': json['filename'],
        'purpose': json['purpose'],
    };
}

export function FileObjectToJSON(json: any): FileObject {
    return FileObjectToJSONTyped(json, false);
}

export function FileObjectToJSONTyped(value?: FileObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'bytes': value['bytes'],
        'created_at': value['createdAt'],
        'filename': value['filename'],
        'purpose': value['purpose'],
    };
}

