/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FineTuningJobEvent } from './FineTuningJobEvent';
import {
    FineTuningJobEventFromJSON,
    FineTuningJobEventFromJSONTyped,
    FineTuningJobEventToJSON,
    FineTuningJobEventToJSONTyped,
} from './FineTuningJobEvent';

/**
 * 
 * @export
 * @interface FineTuningJobEventList
 */
export interface FineTuningJobEventList {
    /**
     * 
     * @type {FineTuningJobEventListObjectEnum}
     * @memberof FineTuningJobEventList
     */
    object: FineTuningJobEventListObjectEnum;
    /**
     * 
     * @type {Array<FineTuningJobEvent>}
     * @memberof FineTuningJobEventList
     */
    data: Array<FineTuningJobEvent>;
    /**
     * 
     * @type {boolean}
     * @memberof FineTuningJobEventList
     */
    hasMore: boolean;
}


/**
 * @export
 */
export const FineTuningJobEventListObjectEnum = {
    List: 'list'
} as const;
export type FineTuningJobEventListObjectEnum = typeof FineTuningJobEventListObjectEnum[keyof typeof FineTuningJobEventListObjectEnum];


/**
 * Check if a given object implements the FineTuningJobEventList interface.
 */
export function instanceOfFineTuningJobEventList(value: object): value is FineTuningJobEventList {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'list') return false;
    
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('hasMore' in (value as Record<string, any>)) && !('has_more' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasMore'] === undefined && (value as Record<string, any>)['has_more'] === undefined)) return false;
    return true;
}

export function FineTuningJobEventListFromJSON(json: any): FineTuningJobEventList {
    return FineTuningJobEventListFromJSONTyped(json, false);
}

export function FineTuningJobEventListFromJSONTyped(json: any, ignoreDiscriminator: boolean): FineTuningJobEventList {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(FineTuningJobEventFromJSON)),
        'hasMore': json['has_more'],
    };
}

export function FineTuningJobEventListToJSON(json: any): FineTuningJobEventList {
    return FineTuningJobEventListToJSONTyped(json, false);
}

export function FineTuningJobEventListToJSONTyped(value?: FineTuningJobEventList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(FineTuningJobEventToJSON)),
        'has_more': value['hasMore'],
    };
}

