/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FineTuningJobMethod } from './FineTuningJobMethod';
import {
    FineTuningJobMethodFromJSON,
    FineTuningJobMethodFromJSONTyped,
    FineTuningJobMethodToJSON,
    FineTuningJobMethodToJSONTyped,
} from './FineTuningJobMethod';
import type { FineTuningJobError } from './FineTuningJobError';
import {
    FineTuningJobErrorFromJSON,
    FineTuningJobErrorFromJSONTyped,
    FineTuningJobErrorToJSON,
    FineTuningJobErrorToJSONTyped,
} from './FineTuningJobError';

/**
 * The fine-tuning job object. `status` is the COLLAPSED public enum (the rich internal states are hidden). `result_files` are freshly-presigned, short-lived download URLs regenerated per read. No backing-provider identity is present (D6).
 * @export
 * @interface FineTuningJob
 */
export interface FineTuningJob {
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    id: string;
    /**
     * 
     * @type {FineTuningJobObjectEnum}
     * @memberof FineTuningJob
     */
    object: FineTuningJobObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    model: string;
    /**
     * Unix timestamp (seconds) at creation.
     * @type {number}
     * @memberof FineTuningJob
     */
    createdAt: number;
    /**
     * Unix timestamp (seconds) at terminal state; null until terminal.
     * @type {number}
     * @memberof FineTuningJob
     */
    finishedAt?: number;
    /**
     * Null in this release (catalog auto-serve is a later phase).
     * @type {string}
     * @memberof FineTuningJob
     */
    fineTunedModel?: string;
    /**
     * 
     * @type {FineTuningJobStatusEnum}
     * @memberof FineTuningJob
     */
    status: FineTuningJobStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    trainingFile: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FineTuningJob
     */
    resultFiles: Array<string>;
    /**
     * 
     * @type {FineTuningJobError}
     * @memberof FineTuningJob
     */
    error?: FineTuningJobError;
    /**
     * 
     * @type {FineTuningJobMethod}
     * @memberof FineTuningJob
     */
    method?: FineTuningJobMethod;
    /**
     * 
     * @type {number}
     * @memberof FineTuningJob
     */
    seed?: number;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    suffix?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof FineTuningJob
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const FineTuningJobObjectEnum = {
    FineTuningJob: 'fine_tuning.job'
} as const;
export type FineTuningJobObjectEnum = typeof FineTuningJobObjectEnum[keyof typeof FineTuningJobObjectEnum];

/**
 * @export
 */
export const FineTuningJobStatusEnum = {
    Validating: 'validating',
    Queued: 'queued',
    Running: 'running',
    Succeeded: 'succeeded',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type FineTuningJobStatusEnum = typeof FineTuningJobStatusEnum[keyof typeof FineTuningJobStatusEnum];


/**
 * Check if a given object implements the FineTuningJob interface.
 */
export function instanceOfFineTuningJob(value: object): value is FineTuningJob {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'fine_tuning.job') return false;
    
    if (!('model' in value) || value['model'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('trainingFile' in (value as Record<string, any>)) && !('training_file' in (value as Record<string, any>))) || ((value as Record<string, any>)['trainingFile'] === undefined && (value as Record<string, any>)['training_file'] === undefined)) return false;
    if ((!('resultFiles' in (value as Record<string, any>)) && !('result_files' in (value as Record<string, any>))) || ((value as Record<string, any>)['resultFiles'] === undefined && (value as Record<string, any>)['result_files'] === undefined)) return false;
    return true;
}

export function FineTuningJobFromJSON(json: any): FineTuningJob {
    return FineTuningJobFromJSONTyped(json, false);
}

export function FineTuningJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): FineTuningJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'model': json['model'],
        'createdAt': json['created_at'],
        'finishedAt': json['finished_at'] == null ? undefined : json['finished_at'],
        'fineTunedModel': json['fine_tuned_model'] == null ? undefined : json['fine_tuned_model'],
        'status': json['status'],
        'trainingFile': json['training_file'],
        'resultFiles': json['result_files'],
        'error': json['error'] == null ? undefined : FineTuningJobErrorFromJSON(json['error']),
        'method': json['method'] == null ? undefined : FineTuningJobMethodFromJSON(json['method']),
        'seed': json['seed'] == null ? undefined : json['seed'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function FineTuningJobToJSON(json: any): FineTuningJob {
    return FineTuningJobToJSONTyped(json, false);
}

export function FineTuningJobToJSONTyped(value?: FineTuningJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'model': value['model'],
        'created_at': value['createdAt'],
        'finished_at': value['finishedAt'],
        'fine_tuned_model': value['fineTunedModel'],
        'status': value['status'],
        'training_file': value['trainingFile'],
        'result_files': value['resultFiles'],
        'error': FineTuningJobErrorToJSON(value['error']),
        'method': FineTuningJobMethodToJSON(value['method']),
        'seed': value['seed'],
        'suffix': value['suffix'],
        'metadata': value['metadata'],
    };
}

