/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FineTuningJob } from './FineTuningJob';
import {
    FineTuningJobFromJSON,
    FineTuningJobFromJSONTyped,
    FineTuningJobToJSON,
    FineTuningJobToJSONTyped,
} from './FineTuningJob';

/**
 * 
 * @export
 * @interface FineTuningJobList
 */
export interface FineTuningJobList {
    /**
     * 
     * @type {FineTuningJobListObjectEnum}
     * @memberof FineTuningJobList
     */
    object: FineTuningJobListObjectEnum;
    /**
     * 
     * @type {Array<FineTuningJob>}
     * @memberof FineTuningJobList
     */
    data: Array<FineTuningJob>;
    /**
     * 
     * @type {boolean}
     * @memberof FineTuningJobList
     */
    hasMore: boolean;
}


/**
 * @export
 */
export const FineTuningJobListObjectEnum = {
    List: 'list'
} as const;
export type FineTuningJobListObjectEnum = typeof FineTuningJobListObjectEnum[keyof typeof FineTuningJobListObjectEnum];


/**
 * Check if a given object implements the FineTuningJobList interface.
 */
export function instanceOfFineTuningJobList(value: object): value is FineTuningJobList {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'list') return false;
    
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('hasMore' in (value as Record<string, any>)) && !('has_more' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasMore'] === undefined && (value as Record<string, any>)['has_more'] === undefined)) return false;
    return true;
}

export function FineTuningJobListFromJSON(json: any): FineTuningJobList {
    return FineTuningJobListFromJSONTyped(json, false);
}

export function FineTuningJobListFromJSONTyped(json: any, ignoreDiscriminator: boolean): FineTuningJobList {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(FineTuningJobFromJSON)),
        'hasMore': json['has_more'],
    };
}

export function FineTuningJobListToJSON(json: any): FineTuningJobList {
    return FineTuningJobListToJSONTyped(json, false);
}

export function FineTuningJobListToJSONTyped(value?: FineTuningJobList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(FineTuningJobToJSON)),
        'has_more': value['hasMore'],
    };
}

