/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFineTuningJobRequestMethodLora } from './CreateFineTuningJobRequestMethodLora';
import {
    CreateFineTuningJobRequestMethodLoraFromJSON,
    CreateFineTuningJobRequestMethodLoraFromJSONTyped,
    CreateFineTuningJobRequestMethodLoraToJSON,
    CreateFineTuningJobRequestMethodLoraToJSONTyped,
} from './CreateFineTuningJobRequestMethodLora';

/**
 * 
 * @export
 * @interface FineTuningJobMethod
 */
export interface FineTuningJobMethod {
    /**
     * 
     * @type {FineTuningJobMethodTypeEnum}
     * @memberof FineTuningJobMethod
     */
    type?: FineTuningJobMethodTypeEnum;
    /**
     * 
     * @type {CreateFineTuningJobRequestMethodLora}
     * @memberof FineTuningJobMethod
     */
    lora?: CreateFineTuningJobRequestMethodLora;
}


/**
 * @export
 */
export const FineTuningJobMethodTypeEnum = {
    Lora: 'lora',
    Qlora: 'qlora'
} as const;
export type FineTuningJobMethodTypeEnum = typeof FineTuningJobMethodTypeEnum[keyof typeof FineTuningJobMethodTypeEnum];


/**
 * Check if a given object implements the FineTuningJobMethod interface.
 */
export function instanceOfFineTuningJobMethod(value: object): value is FineTuningJobMethod {
    return true;
}

export function FineTuningJobMethodFromJSON(json: any): FineTuningJobMethod {
    return FineTuningJobMethodFromJSONTyped(json, false);
}

export function FineTuningJobMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): FineTuningJobMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'lora': json['lora'] == null ? undefined : CreateFineTuningJobRequestMethodLoraFromJSON(json['lora']),
    };
}

export function FineTuningJobMethodToJSON(json: any): FineTuningJobMethod {
    return FineTuningJobMethodToJSONTyped(json, false);
}

export function FineTuningJobMethodToJSONTyped(value?: FineTuningJobMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'lora': CreateFineTuningJobRequestMethodLoraToJSON(value['lora']),
    };
}

