/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FineTuningJobEvent
 */
export interface FineTuningJobEvent {
    /**
     * 
     * @type {string}
     * @memberof FineTuningJobEvent
     */
    id: string;
    /**
     * 
     * @type {FineTuningJobEventObjectEnum}
     * @memberof FineTuningJobEvent
     */
    object: FineTuningJobEventObjectEnum;
    /**
     * Unix timestamp (seconds).
     * @type {number}
     * @memberof FineTuningJobEvent
     */
    createdAt: number;
    /**
     * 
     * @type {FineTuningJobEventLevelEnum}
     * @memberof FineTuningJobEvent
     */
    level: FineTuningJobEventLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJobEvent
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJobEvent
     */
    type?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof FineTuningJobEvent
     */
    data?: { [key: string]: any; };
}


/**
 * @export
 */
export const FineTuningJobEventObjectEnum = {
    FineTuningJobEvent: 'fine_tuning.job.event'
} as const;
export type FineTuningJobEventObjectEnum = typeof FineTuningJobEventObjectEnum[keyof typeof FineTuningJobEventObjectEnum];

/**
 * @export
 */
export const FineTuningJobEventLevelEnum = {
    Info: 'info',
    Warn: 'warn',
    Error: 'error'
} as const;
export type FineTuningJobEventLevelEnum = typeof FineTuningJobEventLevelEnum[keyof typeof FineTuningJobEventLevelEnum];


/**
 * Check if a given object implements the FineTuningJobEvent interface.
 */
export function instanceOfFineTuningJobEvent(value: object): value is FineTuningJobEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'fine_tuning.job.event') return false;
    
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function FineTuningJobEventFromJSON(json: any): FineTuningJobEvent {
    return FineTuningJobEventFromJSONTyped(json, false);
}

export function FineTuningJobEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): FineTuningJobEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'createdAt': json['created_at'],
        'level': json['level'],
        'message': json['message'],
        'type': json['type'] == null ? undefined : json['type'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function FineTuningJobEventToJSON(json: any): FineTuningJobEvent {
    return FineTuningJobEventToJSONTyped(json, false);
}

export function FineTuningJobEventToJSONTyped(value?: FineTuningJobEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created_at': value['createdAt'],
        'level': value['level'],
        'message': value['message'],
        'type': value['type'],
        'data': value['data'],
    };
}

