/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FineTuningJobError
 */
export interface FineTuningJobError {
    /**
     * 
     * @type {string}
     * @memberof FineTuningJobError
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJobError
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJobError
     */
    param?: string;
}

/**
 * Check if a given object implements the FineTuningJobError interface.
 */
export function instanceOfFineTuningJobError(value: object): value is FineTuningJobError {
    return true;
}

export function FineTuningJobErrorFromJSON(json: any): FineTuningJobError {
    return FineTuningJobErrorFromJSONTyped(json, false);
}

export function FineTuningJobErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FineTuningJobError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'param': json['param'] == null ? undefined : json['param'],
    };
}

export function FineTuningJobErrorToJSON(json: any): FineTuningJobError {
    return FineTuningJobErrorToJSONTyped(json, false);
}

export function FineTuningJobErrorToJSONTyped(value?: FineTuningJobError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'param': value['param'],
    };
}

