/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FrameworkVersion
 */
export interface FrameworkVersion {
    /**
     * The version token used in `certified:<framework>@<id>`.
     * @type {string}
     * @memberof FrameworkVersion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FrameworkVersion
     */
    label: string;
    /**
     * CUDA variant this version targets (cuda128/cuda124).
     * @type {string}
     * @memberof FrameworkVersion
     */
    variant: string;
    /**
     * Preselected in the picker (at most one per framework).
     * @type {boolean}
     * @memberof FrameworkVersion
     */
    _default?: boolean;
}

/**
 * Check if a given object implements the FrameworkVersion interface.
 */
export function instanceOfFrameworkVersion(value: object): value is FrameworkVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('variant' in value) || value['variant'] === undefined) return false;
    return true;
}

export function FrameworkVersionFromJSON(json: any): FrameworkVersion {
    return FrameworkVersionFromJSONTyped(json, false);
}

export function FrameworkVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrameworkVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'variant': json['variant'],
        '_default': json['default'] == null ? undefined : json['default'],
    };
}

export function FrameworkVersionToJSON(json: any): FrameworkVersion {
    return FrameworkVersionToJSONTyped(json, false);
}

export function FrameworkVersionToJSONTyped(value?: FrameworkVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'variant': value['variant'],
        'default': value['_default'],
    };
}

