/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GPUType } from './GPUType';
import {
    GPUTypeFromJSON,
    GPUTypeFromJSONTyped,
    GPUTypeToJSON,
    GPUTypeToJSONTyped,
} from './GPUType';

/**
 * 
 * @export
 * @interface GPUTypePage
 */
export interface GPUTypePage {
    /**
     * 
     * @type {Array<GPUType>}
     * @memberof GPUTypePage
     */
    data: Array<GPUType>;
    /**
     * 
     * @type {string}
     * @memberof GPUTypePage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the GPUTypePage interface.
 */
export function instanceOfGPUTypePage(value: object): value is GPUTypePage {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function GPUTypePageFromJSON(json: any): GPUTypePage {
    return GPUTypePageFromJSONTyped(json, false);
}

export function GPUTypePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GPUTypePage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GPUTypeFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function GPUTypePageToJSON(json: any): GPUTypePage {
    return GPUTypePageToJSONTyped(json, false);
}

export function GPUTypePageToJSONTyped(value?: GPUTypePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(GPUTypeToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

