/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GPUType
 */
export interface GPUType {
    /**
     * 
     * @type {string}
     * @memberof GPUType
     */
    gpuType: string;
    /**
     * 
     * @type {number}
     * @memberof GPUType
     */
    vramGb: number;
    /**
     * Representative host vCPU count for this GPU model. Unlike vram_gb (the minimum across the model's current offerings — the value every launch of the model can honor) this varies per offering, so it is the first-sighting/typical value; GET /v1/pricing carries the exact per-offering spec. 0 marks a spec the upstream did not report.
     * @type {number}
     * @memberof GPUType
     */
    cpuCores?: number;
    /**
     * Representative host RAM (GB) for this GPU model; varies per offering — see cpu_cores. 0 marks an unreported spec.
     * @type {number}
     * @memberof GPUType
     */
    ramGb?: number;
    /**
     * Representative host storage (GB) for this GPU model; varies per offering — see cpu_cores. 0 marks an unreported spec.
     * @type {number}
     * @memberof GPUType
     */
    storageGb?: number;
    /**
     * Representative instance filesystem size (GB) a launch of this model receives — the platform default where the upstream honors a configured size, otherwise the machine's reported disk; varies per offering — see cpu_cores. 0 marks an unreported disk (unknown, not zero). GET /v1/pricing carries the exact per-offering value.
     * @type {number}
     * @memberof GPUType
     */
    instanceDiskGb?: number;
    /**
     * true when at least one offering of this model accepts a custom disk_gb at launch (an OR across offerings — requesting disk_gb narrows placement to the capable capacity).
     * @type {boolean}
     * @memberof GPUType
     */
    diskConfigurable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GPUType
     */
    architecture?: string;
}

/**
 * Check if a given object implements the GPUType interface.
 */
export function instanceOfGPUType(value: object): value is GPUType {
    if ((!('gpuType' in (value as Record<string, any>)) && !('gpu_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuType'] === undefined && (value as Record<string, any>)['gpu_type'] === undefined)) return false;
    if ((!('vramGb' in (value as Record<string, any>)) && !('vram_gb' in (value as Record<string, any>))) || ((value as Record<string, any>)['vramGb'] === undefined && (value as Record<string, any>)['vram_gb'] === undefined)) return false;
    return true;
}

export function GPUTypeFromJSON(json: any): GPUType {
    return GPUTypeFromJSONTyped(json, false);
}

export function GPUTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GPUType {
    if (json == null) {
        return json;
    }
    return {
        
        'gpuType': json['gpu_type'],
        'vramGb': json['vram_gb'],
        'cpuCores': json['cpu_cores'] == null ? undefined : json['cpu_cores'],
        'ramGb': json['ram_gb'] == null ? undefined : json['ram_gb'],
        'storageGb': json['storage_gb'] == null ? undefined : json['storage_gb'],
        'instanceDiskGb': json['instance_disk_gb'] == null ? undefined : json['instance_disk_gb'],
        'diskConfigurable': json['disk_configurable'] == null ? undefined : json['disk_configurable'],
        'architecture': json['architecture'] == null ? undefined : json['architecture'],
    };
}

export function GPUTypeToJSON(json: any): GPUType {
    return GPUTypeToJSONTyped(json, false);
}

export function GPUTypeToJSONTyped(value?: GPUType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gpu_type': value['gpuType'],
        'vram_gb': value['vramGb'],
        'cpu_cores': value['cpuCores'],
        'ram_gb': value['ramGb'],
        'storage_gb': value['storageGb'],
        'instance_disk_gb': value['instanceDiskGb'],
        'disk_configurable': value['diskConfigurable'],
        'architecture': value['architecture'],
    };
}

