/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImagesResponseUsage
 */
export interface ImagesResponseUsage {
    /**
     * Number of images generated (the billable unit).
     * @type {number}
     * @memberof ImagesResponseUsage
     */
    imageCount: number;
}

/**
 * Check if a given object implements the ImagesResponseUsage interface.
 */
export function instanceOfImagesResponseUsage(value: object): value is ImagesResponseUsage {
    if ((!('imageCount' in (value as Record<string, any>)) && !('image_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['imageCount'] === undefined && (value as Record<string, any>)['image_count'] === undefined)) return false;
    return true;
}

export function ImagesResponseUsageFromJSON(json: any): ImagesResponseUsage {
    return ImagesResponseUsageFromJSONTyped(json, false);
}

export function ImagesResponseUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesResponseUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'imageCount': json['image_count'],
    };
}

export function ImagesResponseUsageToJSON(json: any): ImagesResponseUsage {
    return ImagesResponseUsageToJSONTyped(json, false);
}

export function ImagesResponseUsageToJSONTyped(value?: ImagesResponseUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_count': value['imageCount'],
    };
}

