/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImagesResponseDataInner } from './ImagesResponseDataInner';
import {
    ImagesResponseDataInnerFromJSON,
    ImagesResponseDataInnerFromJSONTyped,
    ImagesResponseDataInnerToJSON,
    ImagesResponseDataInnerToJSONTyped,
} from './ImagesResponseDataInner';
import type { ImagesResponseUsage } from './ImagesResponseUsage';
import {
    ImagesResponseUsageFromJSON,
    ImagesResponseUsageFromJSONTyped,
    ImagesResponseUsageToJSON,
    ImagesResponseUsageToJSONTyped,
} from './ImagesResponseUsage';

/**
 * 
 * @export
 * @interface ImagesResponse
 */
export interface ImagesResponse {
    /**
     * Unix timestamp (seconds) when the response was created.
     * @type {number}
     * @memberof ImagesResponse
     */
    created: number;
    /**
     * 
     * @type {Array<ImagesResponseDataInner>}
     * @memberof ImagesResponse
     */
    data: Array<ImagesResponseDataInner>;
    /**
     * 
     * @type {ImagesResponseUsage}
     * @memberof ImagesResponse
     */
    usage: ImagesResponseUsage;
}

/**
 * Check if a given object implements the ImagesResponse interface.
 */
export function instanceOfImagesResponse(value: object): value is ImagesResponse {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    return true;
}

export function ImagesResponseFromJSON(json: any): ImagesResponse {
    return ImagesResponseFromJSONTyped(json, false);
}

export function ImagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'data': ((json['data'] as Array<any>).map(ImagesResponseDataInnerFromJSON)),
        'usage': ImagesResponseUsageFromJSON(json['usage']),
    };
}

export function ImagesResponseToJSON(json: any): ImagesResponse {
    return ImagesResponseToJSONTyped(json, false);
}

export function ImagesResponseToJSONTyped(value?: ImagesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'data': ((value['data'] as Array<any>).map(ImagesResponseDataInnerToJSON)),
        'usage': ImagesResponseUsageToJSON(value['usage']),
    };
}

