/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImagesResponseDataInner
 */
export interface ImagesResponseDataInner {
    /**
     * Base64-encoded image bytes.
     * @type {string}
     * @memberof ImagesResponseDataInner
     */
    b64Json: string;
}

/**
 * Check if a given object implements the ImagesResponseDataInner interface.
 */
export function instanceOfImagesResponseDataInner(value: object): value is ImagesResponseDataInner {
    if ((!('b64Json' in (value as Record<string, any>)) && !('b64_json' in (value as Record<string, any>))) || ((value as Record<string, any>)['b64Json'] === undefined && (value as Record<string, any>)['b64_json'] === undefined)) return false;
    return true;
}

export function ImagesResponseDataInnerFromJSON(json: any): ImagesResponseDataInner {
    return ImagesResponseDataInnerFromJSONTyped(json, false);
}

export function ImagesResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'b64Json': json['b64_json'],
    };
}

export function ImagesResponseDataInnerToJSON(json: any): ImagesResponseDataInner {
    return ImagesResponseDataInnerToJSONTyped(json, false);
}

export function ImagesResponseDataInnerToJSONTyped(value?: ImagesResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'b64_json': value['b64Json'],
    };
}

