/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImagesGenerationsRequest
 */
export interface ImagesGenerationsRequest {
    /**
     * Customer-facing image model id (e.g. gpuai/flux.1-schnell) or alias.
     * @type {string}
     * @memberof ImagesGenerationsRequest
     */
    model: string;
    /**
     * Text description of the image(s) to generate.
     * @type {string}
     * @memberof ImagesGenerationsRequest
     */
    prompt: string;
    /**
     * Number of images to generate. Defaults to 1.
     * @type {number}
     * @memberof ImagesGenerationsRequest
     */
    n?: number;
    /**
     * Output image dimensions as WxH (e.g. 1024x1024).
     * @type {string}
     * @memberof ImagesGenerationsRequest
     */
    size?: string;
    /**
     * Only b64_json is supported. A value of "url" is rejected with invalid_request_error until S3-backed URL delivery lands.
     * @type {ImagesGenerationsRequestResponseFormatEnum}
     * @memberof ImagesGenerationsRequest
     */
    responseFormat?: ImagesGenerationsRequestResponseFormatEnum;
}


/**
 * @export
 */
export const ImagesGenerationsRequestResponseFormatEnum = {
    B64Json: 'b64_json'
} as const;
export type ImagesGenerationsRequestResponseFormatEnum = typeof ImagesGenerationsRequestResponseFormatEnum[keyof typeof ImagesGenerationsRequestResponseFormatEnum];


/**
 * Check if a given object implements the ImagesGenerationsRequest interface.
 */
export function instanceOfImagesGenerationsRequest(value: object): value is ImagesGenerationsRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function ImagesGenerationsRequestFromJSON(json: any): ImagesGenerationsRequest {
    return ImagesGenerationsRequestFromJSONTyped(json, false);
}

export function ImagesGenerationsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesGenerationsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'prompt': json['prompt'],
        'n': json['n'] == null ? undefined : json['n'],
        'size': json['size'] == null ? undefined : json['size'],
        'responseFormat': json['response_format'] == null ? undefined : json['response_format'],
    };
}

export function ImagesGenerationsRequestToJSON(json: any): ImagesGenerationsRequest {
    return ImagesGenerationsRequestToJSONTyped(json, false);
}

export function ImagesGenerationsRequestToJSONTyped(value?: ImagesGenerationsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'prompt': value['prompt'],
        'n': value['n'],
        'size': value['size'],
        'response_format': value['responseFormat'],
    };
}

