/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncludeItem
 */
export interface IncludeItem {
    /**
     * 
     * @type {string}
     * @memberof IncludeItem
     */
    name: string;
    /**
     * Resolved build version; absent for unpinned components (e.g. git).
     * @type {string}
     * @memberof IncludeItem
     */
    version?: string;
}

/**
 * Check if a given object implements the IncludeItem interface.
 */
export function instanceOfIncludeItem(value: object): value is IncludeItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function IncludeItemFromJSON(json: any): IncludeItem {
    return IncludeItemFromJSONTyped(json, false);
}

export function IncludeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncludeItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function IncludeItemToJSON(json: any): IncludeItem {
    return IncludeItemToJSONTyped(json, false);
}

export function IncludeItemToJSONTyped(value?: IncludeItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
    };
}

