/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstanceConnection
 */
export interface InstanceConnection {
    /**
     * 
     * @type {string}
     * @memberof InstanceConnection
     */
    hostname?: string;
    /**
     * 
     * @type {number}
     * @memberof InstanceConnection
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof InstanceConnection
     */
    sshCommand?: string;
    /**
     * HTTPS URL of the deployed application (template instances only), e.g. https://gpu-abcd1234.apps.gpu.ai.
     * @type {string}
     * @memberof InstanceConnection
     */
    appUrl?: string;
    /**
     * HTTP Basic Auth username for app_url and terminal_url. Present on instances provisioned after the credential-persistence change; older deploys omit it (their credential was only surfaced once at deploy time).
     * @type {string}
     * @memberof InstanceConnection
     */
    appUser?: string;
    /**
     * HTTP Basic Auth password for app_url and terminal_url. Same availability as app_user. Treat as a secret.
     * @type {string}
     * @memberof InstanceConnection
     */
    appPassword?: string;
    /**
     * HTTPS URL of the browser web console (a shell on the instance, no SSH key required), e.g. https://gpu-abcd1234-term.apps.gpu.ai. Guarded by the same app_user/app_password login. Present only on running instances provisioned with the console.
     * @type {string}
     * @memberof InstanceConnection
     */
    terminalUrl?: string;
}

/**
 * Check if a given object implements the InstanceConnection interface.
 */
export function instanceOfInstanceConnection(value: object): value is InstanceConnection {
    return true;
}

export function InstanceConnectionFromJSON(json: any): InstanceConnection {
    return InstanceConnectionFromJSONTyped(json, false);
}

export function InstanceConnectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceConnection {
    if (json == null) {
        return json;
    }
    return {
        
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'port': json['port'] == null ? undefined : json['port'],
        'sshCommand': json['ssh_command'] == null ? undefined : json['ssh_command'],
        'appUrl': json['app_url'] == null ? undefined : json['app_url'],
        'appUser': json['app_user'] == null ? undefined : json['app_user'],
        'appPassword': json['app_password'] == null ? undefined : json['app_password'],
        'terminalUrl': json['terminal_url'] == null ? undefined : json['terminal_url'],
    };
}

export function InstanceConnectionToJSON(json: any): InstanceConnection {
    return InstanceConnectionToJSONTyped(json, false);
}

export function InstanceConnectionToJSONTyped(value?: InstanceConnection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostname': value['hostname'],
        'port': value['port'],
        'ssh_command': value['sshCommand'],
        'app_url': value['appUrl'],
        'app_user': value['appUser'],
        'app_password': value['appPassword'],
        'terminal_url': value['terminalUrl'],
    };
}

