/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Instance } from './Instance';
import {
    InstanceFromJSON,
    InstanceFromJSONTyped,
    InstanceToJSON,
    InstanceToJSONTyped,
} from './Instance';

/**
 * 
 * @export
 * @interface InstancePage
 */
export interface InstancePage {
    /**
     * 
     * @type {Array<Instance>}
     * @memberof InstancePage
     */
    data: Array<Instance>;
    /**
     * 
     * @type {string}
     * @memberof InstancePage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the InstancePage interface.
 */
export function instanceOfInstancePage(value: object): value is InstancePage {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function InstancePageFromJSON(json: any): InstancePage {
    return InstancePageFromJSONTyped(json, false);
}

export function InstancePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstancePage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(InstanceFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function InstancePageToJSON(json: any): InstancePage {
    return InstancePageToJSONTyped(json, false);
}

export function InstancePageToJSONTyped(value?: InstancePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(InstanceToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

