/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstanceConnection } from './InstanceConnection';
import {
    InstanceConnectionFromJSON,
    InstanceConnectionFromJSONTyped,
    InstanceConnectionToJSON,
    InstanceConnectionToJSONTyped,
} from './InstanceConnection';

/**
 * 
 * @export
 * @interface Instance
 */
export interface Instance {
    /**
     * 
     * @type {string}
     * @memberof Instance
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Instance
     */
    name?: string;
    /**
     * Customer-facing lifecycle status. "allocating" = the GPU is still being acquired from the provider (slow-boot capacity such as baremetal can take ~15 min); "starting" = the node exists and is booting; "running" = ready to use. "unreachable" = the platform's tunnel probe has confirmed the SSH path is down while the machine may still be up: the instance is NOT usable right now, billing for the confirmed-dead window is auto-credited back, and the instance either recovers to "running" on its own or is failed after a grace window. It is a degraded reading of a running instance, not a separate lifecycle state — see unreachable_since.
     * @type {InstanceStatusEnum}
     * @memberof Instance
     */
    status: InstanceStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Instance
     */
    gpuType: string;
    /**
     * 
     * @type {number}
     * @memberof Instance
     */
    gpuCount: number;
    /**
     * 
     * @type {string}
     * @memberof Instance
     */
    region: string;
    /**
     * 
     * @type {InstanceTierEnum}
     * @memberof Instance
     */
    tier: InstanceTierEnum;
    /**
     * hourly rate for the whole instance — covers all gpu_count GPUs
     * @type {number}
     * @memberof Instance
     */
    pricePerHour: number;
    /**
     * 
     * @type {InstanceConnection}
     * @memberof Instance
     */
    connection?: InstanceConnection;
    /**
     * Instance filesystem size in GB that the platform configured for this launch. Present only where the placed capacity honors a configured disk size; absent means the machine's disk is provider-determined (its own flavor volume).
     * @type {number}
     * @memberof Instance
     */
    diskGb?: number;
    /**
     * The customer-supplied container image this instance was launched from, digest-pinned at verification time (e.g. `ghcr.io/acme/trainer:v1@sha256:…`). Present only on custom-image launches; template and certified launches never expose their images here.
     * @type {string}
     * @memberof Instance
     */
    image?: string;
    /**
     * Why the instance is in the error state, e.g. "provisioning stalled: the instance started but never became reachable". Present only on errored instances.
     * @type {string}
     * @memberof Instance
     */
    statusReason?: string;
    /**
     * 
     * @type {Date}
     * @memberof Instance
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Instance
     */
    readyAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Instance
     */
    terminatedAt?: Date;
    /**
     * Last time the platform verified the SSH path to this instance end-to-end through the tunnel. Absent means the instance has not been probed yet (freshly launched, or no tunnel) — it does NOT mean unreachable. An instance whose status is still "running" while this timestamp stops advancing is one whose SSH has died even though the machine is up.
     * @type {Date}
     * @memberof Instance
     */
    lastReachableAt?: Date;
    /**
     * Start of the confirmed tunnel outage the instance is currently in. Present exactly when status is "unreachable", absent otherwise. It is the timestamp the auto-credit for the dead window is computed from, so a ledger credit can be reconciled against it.
     * @type {Date}
     * @memberof Instance
     */
    unreachableSince?: Date;
}


/**
 * @export
 */
export const InstanceStatusEnum = {
    Allocating: 'allocating',
    Starting: 'starting',
    Running: 'running',
    Stopping: 'stopping',
    Stopped: 'stopped',
    Terminated: 'terminated',
    Unreachable: 'unreachable',
    Error: 'error'
} as const;
export type InstanceStatusEnum = typeof InstanceStatusEnum[keyof typeof InstanceStatusEnum];

/**
 * @export
 */
export const InstanceTierEnum = {
    Spot: 'spot',
    OnDemand: 'on_demand'
} as const;
export type InstanceTierEnum = typeof InstanceTierEnum[keyof typeof InstanceTierEnum];


/**
 * Check if a given object implements the Instance interface.
 */
export function instanceOfInstance(value: object): value is Instance {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('gpuType' in (value as Record<string, any>)) && !('gpu_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuType'] === undefined && (value as Record<string, any>)['gpu_type'] === undefined)) return false;
    if ((!('gpuCount' in (value as Record<string, any>)) && !('gpu_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuCount'] === undefined && (value as Record<string, any>)['gpu_count'] === undefined)) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if ((!('pricePerHour' in (value as Record<string, any>)) && !('price_per_hour' in (value as Record<string, any>))) || ((value as Record<string, any>)['pricePerHour'] === undefined && (value as Record<string, any>)['price_per_hour'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function InstanceFromJSON(json: any): Instance {
    return InstanceFromJSONTyped(json, false);
}

export function InstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Instance {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'],
        'gpuType': json['gpu_type'],
        'gpuCount': json['gpu_count'],
        'region': json['region'],
        'tier': json['tier'],
        'pricePerHour': json['price_per_hour'],
        'connection': json['connection'] == null ? undefined : InstanceConnectionFromJSON(json['connection']),
        'diskGb': json['disk_gb'] == null ? undefined : json['disk_gb'],
        'image': json['image'] == null ? undefined : json['image'],
        'statusReason': json['status_reason'] == null ? undefined : json['status_reason'],
        'createdAt': (new Date(json['created_at'])),
        'readyAt': json['ready_at'] == null ? undefined : (new Date(json['ready_at'])),
        'terminatedAt': json['terminated_at'] == null ? undefined : (new Date(json['terminated_at'])),
        'lastReachableAt': json['last_reachable_at'] == null ? undefined : (new Date(json['last_reachable_at'])),
        'unreachableSince': json['unreachable_since'] == null ? undefined : (new Date(json['unreachable_since'])),
    };
}

export function InstanceToJSON(json: any): Instance {
    return InstanceToJSONTyped(json, false);
}

export function InstanceToJSONTyped(value?: Instance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
        'gpu_type': value['gpuType'],
        'gpu_count': value['gpuCount'],
        'region': value['region'],
        'tier': value['tier'],
        'price_per_hour': value['pricePerHour'],
        'connection': InstanceConnectionToJSON(value['connection']),
        'disk_gb': value['diskGb'],
        'image': value['image'],
        'status_reason': value['statusReason'],
        'created_at': value['createdAt'].toISOString(),
        'ready_at': value['readyAt'] == null ? value['readyAt'] : value['readyAt'].toISOString(),
        'terminated_at': value['terminatedAt'] == null ? value['terminatedAt'] : value['terminatedAt'].toISOString(),
        'last_reachable_at': value['lastReachableAt'] == null ? value['lastReachableAt'] : value['lastReachableAt'].toISOString(),
        'unreachable_since': value['unreachableSince'] == null ? value['unreachableSince'] : value['unreachableSince'].toISOString(),
    };
}

