/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegistryCredential } from './RegistryCredential';
import {
    RegistryCredentialFromJSON,
    RegistryCredentialFromJSONTyped,
    RegistryCredentialToJSON,
    RegistryCredentialToJSONTyped,
} from './RegistryCredential';

/**
 * 
 * @export
 * @interface ListRegistryCredentials200Response
 */
export interface ListRegistryCredentials200Response {
    /**
     * 
     * @type {Array<RegistryCredential>}
     * @memberof ListRegistryCredentials200Response
     */
    data?: Array<RegistryCredential>;
}

/**
 * Check if a given object implements the ListRegistryCredentials200Response interface.
 */
export function instanceOfListRegistryCredentials200Response(value: object): value is ListRegistryCredentials200Response {
    return true;
}

export function ListRegistryCredentials200ResponseFromJSON(json: any): ListRegistryCredentials200Response {
    return ListRegistryCredentials200ResponseFromJSONTyped(json, false);
}

export function ListRegistryCredentials200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRegistryCredentials200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RegistryCredentialFromJSON)),
    };
}

export function ListRegistryCredentials200ResponseToJSON(json: any): ListRegistryCredentials200Response {
    return ListRegistryCredentials200ResponseToJSONTyped(json, false);
}

export function ListRegistryCredentials200ResponseToJSONTyped(value?: ListRegistryCredentials200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RegistryCredentialToJSON)),
    };
}

