/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CryptoDeposit } from './CryptoDeposit';
import {
    CryptoDepositFromJSON,
    CryptoDepositFromJSONTyped,
    CryptoDepositToJSON,
    CryptoDepositToJSONTyped,
} from './CryptoDeposit';

/**
 * 
 * @export
 * @interface ListDeposits200Response
 */
export interface ListDeposits200Response {
    /**
     * 
     * @type {Array<CryptoDeposit>}
     * @memberof ListDeposits200Response
     */
    deposits: Array<CryptoDeposit>;
}

/**
 * Check if a given object implements the ListDeposits200Response interface.
 */
export function instanceOfListDeposits200Response(value: object): value is ListDeposits200Response {
    if (!('deposits' in value) || value['deposits'] === undefined) return false;
    return true;
}

export function ListDeposits200ResponseFromJSON(json: any): ListDeposits200Response {
    return ListDeposits200ResponseFromJSONTyped(json, false);
}

export function ListDeposits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDeposits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'deposits': ((json['deposits'] as Array<any>).map(CryptoDepositFromJSON)),
    };
}

export function ListDeposits200ResponseToJSON(json: any): ListDeposits200Response {
    return ListDeposits200ResponseToJSONTyped(json, false);
}

export function ListDeposits200ResponseToJSONTyped(value?: ListDeposits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deposits': ((value['deposits'] as Array<any>).map(CryptoDepositToJSON)),
    };
}

