/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupplierMachineView } from './SupplierMachineView';
import {
    SupplierMachineViewFromJSON,
    SupplierMachineViewFromJSONTyped,
    SupplierMachineViewToJSON,
    SupplierMachineViewToJSONTyped,
} from './SupplierMachineView';

/**
 * 
 * @export
 * @interface ListCommunityMachines200Response
 */
export interface ListCommunityMachines200Response {
    /**
     * 
     * @type {Array<SupplierMachineView>}
     * @memberof ListCommunityMachines200Response
     */
    machines: Array<SupplierMachineView>;
}

/**
 * Check if a given object implements the ListCommunityMachines200Response interface.
 */
export function instanceOfListCommunityMachines200Response(value: object): value is ListCommunityMachines200Response {
    if (!('machines' in value) || value['machines'] === undefined) return false;
    return true;
}

export function ListCommunityMachines200ResponseFromJSON(json: any): ListCommunityMachines200Response {
    return ListCommunityMachines200ResponseFromJSONTyped(json, false);
}

export function ListCommunityMachines200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCommunityMachines200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'machines': ((json['machines'] as Array<any>).map(SupplierMachineViewFromJSON)),
    };
}

export function ListCommunityMachines200ResponseToJSON(json: any): ListCommunityMachines200Response {
    return ListCommunityMachines200ResponseToJSONTyped(json, false);
}

export function ListCommunityMachines200ResponseToJSONTyped(value?: ListCommunityMachines200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machines': ((value['machines'] as Array<any>).map(SupplierMachineViewToJSON)),
    };
}

