/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelPricing } from './ModelPricing';
import {
    ModelPricingFromJSON,
    ModelPricingFromJSONTyped,
    ModelPricingToJSON,
    ModelPricingToJSONTyped,
} from './ModelPricing';
import type { ModelParametersInner } from './ModelParametersInner';
import {
    ModelParametersInnerFromJSON,
    ModelParametersInnerFromJSONTyped,
    ModelParametersInnerToJSON,
    ModelParametersInnerToJSONTyped,
} from './ModelParametersInner';

/**
 * 
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    id: string;
    /**
     * 
     * @type {ModelObjectEnum}
     * @memberof Model
     */
    object: ModelObjectEnum;
    /**
     * 
     * @type {number}
     * @memberof Model
     */
    created?: number;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    ownedBy: string;
    /**
     * Model creator/organization (e.g. "Meta", "Qwen", "Black Forest Labs").
     * @type {string}
     * @memberof Model
     */
    author?: string;
    /**
     * 
     * @type {ModelModalityEnum}
     * @memberof Model
     */
    modality: ModelModalityEnum;
    /**
     * Browse-facing category; mirrors modality (chat/image/video).
     * @type {string}
     * @memberof Model
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof Model
     */
    contextLength?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model
     */
    supportedParameters?: Array<string>;
    /**
     * Typed parameter descriptors for media (image/video) models — name, type, enum/bounds/default. Playgrounds render input forms from these.
     * @type {Array<ModelParametersInner>}
     * @memberof Model
     */
    parameters?: Array<ModelParametersInner>;
    /**
     * 
     * @type {ModelPricing}
     * @memberof Model
     */
    pricing: ModelPricing;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model
     */
    aliases?: Array<string>;
    /**
     * Whether this model can be used as the base of a managed fine-tuning job. The tunable allowlist is operator-curated and much narrower than the serving catalog, so this is false for almost every model. Absent means false.
     * @type {boolean}
     * @memberof Model
     */
    fineTunable?: boolean;
    /**
     * The exact id to send as `model` when creating a fine-tuning job for this entry. Present only when `fine_tunable` is true, and deliberately distinct from `id`: the allowlist matches the customer-facing base id (e.g. `qwen2.5-7b-instruct`), which a served model normally carries as an alias rather than as its namespaced catalog id.
     * @type {string}
     * @memberof Model
     */
    fineTuneBaseModel?: string;
    /**
     * 
     * @type {ModelStatusEnum}
     * @memberof Model
     */
    status: ModelStatusEnum;
}


/**
 * @export
 */
export const ModelObjectEnum = {
    Model: 'model'
} as const;
export type ModelObjectEnum = typeof ModelObjectEnum[keyof typeof ModelObjectEnum];

/**
 * @export
 */
export const ModelModalityEnum = {
    Chat: 'chat',
    Image: 'image',
    Video: 'video'
} as const;
export type ModelModalityEnum = typeof ModelModalityEnum[keyof typeof ModelModalityEnum];

/**
 * @export
 */
export const ModelStatusEnum = {
    Active: 'active',
    ComingSoon: 'coming_soon',
    Deprecated: 'deprecated'
} as const;
export type ModelStatusEnum = typeof ModelStatusEnum[keyof typeof ModelStatusEnum];


/**
 * Check if a given object implements the Model interface.
 */
export function instanceOfModel(value: object): value is Model {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'model') return false;
    
    if ((!('ownedBy' in (value as Record<string, any>)) && !('owned_by' in (value as Record<string, any>))) || ((value as Record<string, any>)['ownedBy'] === undefined && (value as Record<string, any>)['owned_by'] === undefined)) return false;
    if (!('modality' in value) || value['modality'] === undefined) return false;
    if (!('pricing' in value) || value['pricing'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ModelFromJSON(json: any): Model {
    return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'created': json['created'] == null ? undefined : json['created'],
        'ownedBy': json['owned_by'],
        'author': json['author'] == null ? undefined : json['author'],
        'modality': json['modality'],
        'category': json['category'] == null ? undefined : json['category'],
        'contextLength': json['context_length'] == null ? undefined : json['context_length'],
        'supportedParameters': json['supported_parameters'] == null ? undefined : json['supported_parameters'],
        'parameters': json['parameters'] == null ? undefined : ((json['parameters'] as Array<any>).map(ModelParametersInnerFromJSON)),
        'pricing': ModelPricingFromJSON(json['pricing']),
        'aliases': json['aliases'] == null ? undefined : json['aliases'],
        'fineTunable': json['fine_tunable'] == null ? undefined : json['fine_tunable'],
        'fineTuneBaseModel': json['fine_tune_base_model'] == null ? undefined : json['fine_tune_base_model'],
        'status': json['status'],
    };
}

export function ModelToJSON(json: any): Model {
    return ModelToJSONTyped(json, false);
}

export function ModelToJSONTyped(value?: Model | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'owned_by': value['ownedBy'],
        'author': value['author'],
        'modality': value['modality'],
        'category': value['category'],
        'context_length': value['contextLength'],
        'supported_parameters': value['supportedParameters'],
        'parameters': value['parameters'] == null ? undefined : ((value['parameters'] as Array<any>).map(ModelParametersInnerToJSON)),
        'pricing': ModelPricingToJSON(value['pricing']),
        'aliases': value['aliases'],
        'fine_tunable': value['fineTunable'],
        'fine_tune_base_model': value['fineTuneBaseModel'],
        'status': value['status'],
    };
}

