/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelPricing
 */
export interface ModelPricing {
    /**
     * 
     * @type {string}
     * @memberof ModelPricing
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelPricing
     */
    inputPer1mTokensCents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelPricing
     */
    outputPer1mTokensCents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelPricing
     */
    perImageCents?: number;
    /**
     * Exact per-image rate in micro-cents (1e-6 cent). Prefer this for image models — per_image_cents rounds sub-cent prices to 0.
     * @type {number}
     * @memberof ModelPricing
     */
    perImageMicrocents?: number;
    /**
     * Price per output megapixel in micro-cents (1e-6 cent) for image models metered per megapixel. Mutually exclusive with the per-image fields.
     * @type {number}
     * @memberof ModelPricing
     */
    perMpxlMicrocents?: number;
    /**
     * Representative per-clip price in micro-cents (1e-6 cent) for video models — a "from" price taken from the provider's published example rate.
     * @type {number}
     * @memberof ModelPricing
     */
    perVideoMicrocents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelPricing
     */
    perVideoSecondCents?: number;
    /**
     * Exact per-second-of-output-video rate in micro-cents (1e-6 cent). Prefer this for video models.
     * @type {number}
     * @memberof ModelPricing
     */
    perVideoSecondMicrocents?: number;
}

/**
 * Check if a given object implements the ModelPricing interface.
 */
export function instanceOfModelPricing(value: object): value is ModelPricing {
    return true;
}

export function ModelPricingFromJSON(json: any): ModelPricing {
    return ModelPricingFromJSONTyped(json, false);
}

export function ModelPricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelPricing {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'inputPer1mTokensCents': json['input_per_1m_tokens_cents'] == null ? undefined : json['input_per_1m_tokens_cents'],
        'outputPer1mTokensCents': json['output_per_1m_tokens_cents'] == null ? undefined : json['output_per_1m_tokens_cents'],
        'perImageCents': json['per_image_cents'] == null ? undefined : json['per_image_cents'],
        'perImageMicrocents': json['per_image_microcents'] == null ? undefined : json['per_image_microcents'],
        'perMpxlMicrocents': json['per_mpxl_microcents'] == null ? undefined : json['per_mpxl_microcents'],
        'perVideoMicrocents': json['per_video_microcents'] == null ? undefined : json['per_video_microcents'],
        'perVideoSecondCents': json['per_video_second_cents'] == null ? undefined : json['per_video_second_cents'],
        'perVideoSecondMicrocents': json['per_video_second_microcents'] == null ? undefined : json['per_video_second_microcents'],
    };
}

export function ModelPricingToJSON(json: any): ModelPricing {
    return ModelPricingToJSONTyped(json, false);
}

export function ModelPricingToJSONTyped(value?: ModelPricing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'input_per_1m_tokens_cents': value['inputPer1mTokensCents'],
        'output_per_1m_tokens_cents': value['outputPer1mTokensCents'],
        'per_image_cents': value['perImageCents'],
        'per_image_microcents': value['perImageMicrocents'],
        'per_mpxl_microcents': value['perMpxlMicrocents'],
        'per_video_microcents': value['perVideoMicrocents'],
        'per_video_second_cents': value['perVideoSecondCents'],
        'per_video_second_microcents': value['perVideoSecondMicrocents'],
    };
}

