/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelParametersInner
 */
export interface ModelParametersInner {
    /**
     * 
     * @type {string}
     * @memberof ModelParametersInner
     */
    name: string;
    /**
     * 
     * @type {ModelParametersInnerTypeEnum}
     * @memberof ModelParametersInner
     */
    type: ModelParametersInnerTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelParametersInner
     */
    _enum?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ModelParametersInner
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelParametersInner
     */
    max?: number;
    /**
     * 
     * @type {any}
     * @memberof ModelParametersInner
     */
    _default?: any | null;
}


/**
 * @export
 */
export const ModelParametersInnerTypeEnum = {
    Enum: 'enum',
    Int: 'int',
    String: 'string',
    Bool: 'bool'
} as const;
export type ModelParametersInnerTypeEnum = typeof ModelParametersInnerTypeEnum[keyof typeof ModelParametersInnerTypeEnum];


/**
 * Check if a given object implements the ModelParametersInner interface.
 */
export function instanceOfModelParametersInner(value: object): value is ModelParametersInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ModelParametersInnerFromJSON(json: any): ModelParametersInner {
    return ModelParametersInnerFromJSONTyped(json, false);
}

export function ModelParametersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelParametersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        '_enum': json['enum'] == null ? undefined : json['enum'],
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
        '_default': json['default'] === undefined ? undefined : json['default'] === null ? null : json['default'],
    };
}

export function ModelParametersInnerToJSON(json: any): ModelParametersInner {
    return ModelParametersInnerToJSONTyped(json, false);
}

export function ModelParametersInnerToJSONTyped(value?: ModelParametersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'enum': value['_enum'],
        'min': value['min'],
        'max': value['max'],
        'default': value['_default'],
    };
}

