/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Model } from './Model';
import {
    ModelFromJSON,
    ModelFromJSONTyped,
    ModelToJSON,
    ModelToJSONTyped,
} from './Model';

/**
 * 
 * @export
 * @interface ModelList
 */
export interface ModelList {
    /**
     * 
     * @type {ModelListObjectEnum}
     * @memberof ModelList
     */
    object: ModelListObjectEnum;
    /**
     * 
     * @type {Array<Model>}
     * @memberof ModelList
     */
    data: Array<Model>;
}


/**
 * @export
 */
export const ModelListObjectEnum = {
    List: 'list'
} as const;
export type ModelListObjectEnum = typeof ModelListObjectEnum[keyof typeof ModelListObjectEnum];


/**
 * Check if a given object implements the ModelList interface.
 */
export function instanceOfModelList(value: object): value is ModelList {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'list') return false;
    
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ModelListFromJSON(json: any): ModelList {
    return ModelListFromJSONTyped(json, false);
}

export function ModelListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelList {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(ModelFromJSON)),
    };
}

export function ModelListToJSON(json: any): ModelList {
    return ModelListToJSONTyped(json, false);
}

export function ModelListToJSONTyped(value?: ModelList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(ModelToJSON)),
    };
}

