/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenAIErrorEnvelopeError } from './OpenAIErrorEnvelopeError';
import {
    OpenAIErrorEnvelopeErrorFromJSON,
    OpenAIErrorEnvelopeErrorFromJSONTyped,
    OpenAIErrorEnvelopeErrorToJSON,
    OpenAIErrorEnvelopeErrorToJSONTyped,
} from './OpenAIErrorEnvelopeError';

/**
 * 
 * @export
 * @interface OpenAIErrorEnvelope
 */
export interface OpenAIErrorEnvelope {
    /**
     * 
     * @type {OpenAIErrorEnvelopeError}
     * @memberof OpenAIErrorEnvelope
     */
    error: OpenAIErrorEnvelopeError;
}

/**
 * Check if a given object implements the OpenAIErrorEnvelope interface.
 */
export function instanceOfOpenAIErrorEnvelope(value: object): value is OpenAIErrorEnvelope {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function OpenAIErrorEnvelopeFromJSON(json: any): OpenAIErrorEnvelope {
    return OpenAIErrorEnvelopeFromJSONTyped(json, false);
}

export function OpenAIErrorEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenAIErrorEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'error': OpenAIErrorEnvelopeErrorFromJSON(json['error']),
    };
}

export function OpenAIErrorEnvelopeToJSON(json: any): OpenAIErrorEnvelope {
    return OpenAIErrorEnvelopeToJSONTyped(json, false);
}

export function OpenAIErrorEnvelopeToJSONTyped(value?: OpenAIErrorEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': OpenAIErrorEnvelopeErrorToJSON(value['error']),
    };
}

