/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenAIErrorEnvelopeError
 */
export interface OpenAIErrorEnvelopeError {
    /**
     * 
     * @type {string}
     * @memberof OpenAIErrorEnvelopeError
     */
    message: string;
    /**
     * OpenAI error class (e.g. invalid_request_error, authentication_error, billing_error).
     * @type {string}
     * @memberof OpenAIErrorEnvelopeError
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof OpenAIErrorEnvelopeError
     */
    param?: string;
    /**
     * Stable machine-readable error code.
     * @type {string}
     * @memberof OpenAIErrorEnvelopeError
     */
    code: string;
}

/**
 * Check if a given object implements the OpenAIErrorEnvelopeError interface.
 */
export function instanceOfOpenAIErrorEnvelopeError(value: object): value is OpenAIErrorEnvelopeError {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function OpenAIErrorEnvelopeErrorFromJSON(json: any): OpenAIErrorEnvelopeError {
    return OpenAIErrorEnvelopeErrorFromJSONTyped(json, false);
}

export function OpenAIErrorEnvelopeErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenAIErrorEnvelopeError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'type': json['type'],
        'param': json['param'] == null ? undefined : json['param'],
        'code': json['code'],
    };
}

export function OpenAIErrorEnvelopeErrorToJSON(json: any): OpenAIErrorEnvelopeError {
    return OpenAIErrorEnvelopeErrorToJSONTyped(json, false);
}

export function OpenAIErrorEnvelopeErrorToJSONTyped(value?: OpenAIErrorEnvelopeError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'type': value['type'],
        'param': value['param'],
        'code': value['code'],
    };
}

