/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Terminal-success payload. Carries the per-instance web-access coordinates — app_url for template deploys, terminal_url for instances provisioned with the browser web console, and the basic-auth username shared by both. The basic-auth PASSWORD is never included here — retrieve it via GET /instances/{id}?include=credentials (connection.app_password).
 * @export
 * @interface OperationResult
 */
export interface OperationResult {
    /**
     * 
     * @type {string}
     * @memberof OperationResult
     */
    appUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationResult
     */
    terminalUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationResult
     */
    appBasicAuthUser?: string;
}

/**
 * Check if a given object implements the OperationResult interface.
 */
export function instanceOfOperationResult(value: object): value is OperationResult {
    return true;
}

export function OperationResultFromJSON(json: any): OperationResult {
    return OperationResultFromJSONTyped(json, false);
}

export function OperationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'appUrl': json['app_url'] == null ? undefined : json['app_url'],
        'terminalUrl': json['terminal_url'] == null ? undefined : json['terminal_url'],
        'appBasicAuthUser': json['app_basic_auth_user'] == null ? undefined : json['app_basic_auth_user'],
    };
}

export function OperationResultToJSON(json: any): OperationResult {
    return OperationResultToJSONTyped(json, false);
}

export function OperationResultToJSONTyped(value?: OperationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_url': value['appUrl'],
        'terminal_url': value['terminalUrl'],
        'app_basic_auth_user': value['appBasicAuthUser'],
    };
}

