/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationError
 */
export interface OperationError {
    /**
     * 
     * @type {string}
     * @memberof OperationError
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationError
     */
    detail?: string;
}

/**
 * Check if a given object implements the OperationError interface.
 */
export function instanceOfOperationError(value: object): value is OperationError {
    return true;
}

export function OperationErrorFromJSON(json: any): OperationError {
    return OperationErrorFromJSONTyped(json, false);
}

export function OperationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function OperationErrorToJSON(json: any): OperationError {
    return OperationErrorToJSONTyped(json, false);
}

export function OperationErrorToJSONTyped(value?: OperationError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

