/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperationResult } from './OperationResult';
import {
    OperationResultFromJSON,
    OperationResultFromJSONTyped,
    OperationResultToJSON,
    OperationResultToJSONTyped,
} from './OperationResult';
import type { OperationError } from './OperationError';
import {
    OperationErrorFromJSON,
    OperationErrorFromJSONTyped,
    OperationErrorToJSON,
    OperationErrorToJSONTyped,
} from './OperationError';

/**
 * 
 * @export
 * @interface Operation
 */
export interface Operation {
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    operationId: string;
    /**
     * 
     * @type {OperationKindEnum}
     * @memberof Operation
     */
    kind: OperationKindEnum;
    /**
     * 
     * @type {OperationStateEnum}
     * @memberof Operation
     */
    state: OperationStateEnum;
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    resourceId?: string;
    /**
     * 
     * @type {OperationError}
     * @memberof Operation
     */
    error?: OperationError;
    /**
     * 
     * @type {OperationResult}
     * @memberof Operation
     */
    result?: OperationResult;
    /**
     * 
     * @type {Date}
     * @memberof Operation
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Operation
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Operation
     */
    completedAt?: Date;
    /**
     * Create-time advisories, present only on the synchronous 202 from POST /instances (never on GET /operations/{id} polls) — e.g. the model-size guard failing open because a template deploy's MODEL is a gated or unknown Hugging Face repo whose size could not be verified.
     * @type {Array<string>}
     * @memberof Operation
     */
    warnings?: Array<string>;
}


/**
 * @export
 */
export const OperationKindEnum = {
    InstanceCreate: 'instance.create',
    InstanceDelete: 'instance.delete'
} as const;
export type OperationKindEnum = typeof OperationKindEnum[keyof typeof OperationKindEnum];

/**
 * @export
 */
export const OperationStateEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Succeeded: 'succeeded',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type OperationStateEnum = typeof OperationStateEnum[keyof typeof OperationStateEnum];


/**
 * Check if a given object implements the Operation interface.
 */
export function instanceOfOperation(value: object): value is Operation {
    if ((!('operationId' in (value as Record<string, any>)) && !('operation_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['operationId'] === undefined && (value as Record<string, any>)['operation_id'] === undefined)) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function OperationFromJSON(json: any): Operation {
    return OperationFromJSONTyped(json, false);
}

export function OperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation {
    if (json == null) {
        return json;
    }
    return {
        
        'operationId': json['operation_id'],
        'kind': json['kind'],
        'state': json['state'],
        'resourceId': json['resource_id'] == null ? undefined : json['resource_id'],
        'error': json['error'] == null ? undefined : OperationErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : OperationResultFromJSON(json['result']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
    };
}

export function OperationToJSON(json: any): Operation {
    return OperationToJSONTyped(json, false);
}

export function OperationToJSONTyped(value?: Operation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation_id': value['operationId'],
        'kind': value['kind'],
        'state': value['state'],
        'resource_id': value['resourceId'],
        'error': OperationErrorToJSON(value['error']),
        'result': OperationResultToJSON(value['result']),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'warnings': value['warnings'],
    };
}

