/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Pricing
 */
export interface Pricing {
    /**
     * 
     * @type {string}
     * @memberof Pricing
     */
    gpuType: string;
    /**
     * number of GPUs in the listed configuration
     * @type {number}
     * @memberof Pricing
     */
    gpuCount: number;
    /**
     * host vCPU count for this offering, tied to the shown (cheapest) price. 0 marks an unreported spec.
     * @type {number}
     * @memberof Pricing
     */
    cpuCores?: number;
    /**
     * host RAM (GB) for this offering, tied to the shown price. 0 marks an unreported spec.
     * @type {number}
     * @memberof Pricing
     */
    ramGb?: number;
    /**
     * host storage (GB) for this offering, tied to the shown price. 0 marks an unreported spec.
     * @type {number}
     * @memberof Pricing
     */
    storageGb?: number;
    /**
     * 
     * @type {string}
     * @memberof Pricing
     */
    region: string;
    /**
     * 
     * @type {PricingTierEnum}
     * @memberof Pricing
     */
    tier: PricingTierEnum;
    /**
     * hourly price for the whole listed configuration — covers all gpu_count GPUs
     * @type {number}
     * @memberof Pricing
     */
    pricePerHour: number;
    /**
     * count of available units, summed across merged identical offers
     * @type {number}
     * @memberof Pricing
     */
    available: number;
    /**
     * true when instances of this offering are typically reachable within about a minute of launch; false for capacity with longer provisioning times (~3-5 minutes)
     * @type {boolean}
     * @memberof Pricing
     */
    instantBoot: boolean;
    /**
     * true when this offering is community-supplied capacity
     * @type {boolean}
     * @memberof Pricing
     */
    community: boolean;
    /**
     * Instance filesystem size (GB) a launch of THIS offering receives — the platform default where the upstream honors a configured size, otherwise the machine's own reported disk; tied to the shown (cheapest) price like cpu_cores. 0 marks an unreported disk (unknown, not zero).
     * @type {number}
     * @memberof Pricing
     */
    instanceDiskGb?: number;
    /**
     * true when a launch of this offering may choose its own disk size via the create request's disk_gb. A distinguishing field in the offer merge — configurable and fixed-disk capacity for the same SKU stay separate rows.
     * @type {boolean}
     * @memberof Pricing
     */
    diskConfigurable?: boolean;
    /**
     * Retail price of one GB of instance disk beyond instance_disk_gb, per hour, for launches of this offering. A launch requesting disk_gb above instance_disk_gb is billed approximately price_per_hour + (disk_gb − instance_disk_gb) × disk_price_per_gb_hour (the exact billed rate folds disk into one cent-rounded hourly price). 0 when the offering is not disk-configurable, or when disk above the included allowance is currently free.
     * @type {number}
     * @memberof Pricing
     */
    diskPricePerGbHour?: number;
    /**
     * per-offering capacity classification — "secure" for datacenter-operated hardware, "community" for supplier/peer-hosted hardware with a softer SLA. The string twin of `community`, classified per offering rather than per upstream. May transiently be empty for cache entries written before the field existed.
     * @type {PricingCapacityClassEnum}
     * @memberof Pricing
     */
    capacityClass?: PricingCapacityClassEnum;
}


/**
 * @export
 */
export const PricingTierEnum = {
    Spot: 'spot',
    OnDemand: 'on_demand'
} as const;
export type PricingTierEnum = typeof PricingTierEnum[keyof typeof PricingTierEnum];

/**
 * @export
 */
export const PricingCapacityClassEnum = {
    Secure: 'secure',
    Community: 'community',
    Empty: ''
} as const;
export type PricingCapacityClassEnum = typeof PricingCapacityClassEnum[keyof typeof PricingCapacityClassEnum];


/**
 * Check if a given object implements the Pricing interface.
 */
export function instanceOfPricing(value: object): value is Pricing {
    if ((!('gpuType' in (value as Record<string, any>)) && !('gpu_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuType'] === undefined && (value as Record<string, any>)['gpu_type'] === undefined)) return false;
    if ((!('gpuCount' in (value as Record<string, any>)) && !('gpu_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuCount'] === undefined && (value as Record<string, any>)['gpu_count'] === undefined)) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if ((!('pricePerHour' in (value as Record<string, any>)) && !('price_per_hour' in (value as Record<string, any>))) || ((value as Record<string, any>)['pricePerHour'] === undefined && (value as Record<string, any>)['price_per_hour'] === undefined)) return false;
    if (!('available' in value) || value['available'] === undefined) return false;
    if ((!('instantBoot' in (value as Record<string, any>)) && !('instant_boot' in (value as Record<string, any>))) || ((value as Record<string, any>)['instantBoot'] === undefined && (value as Record<string, any>)['instant_boot'] === undefined)) return false;
    if (!('community' in value) || value['community'] === undefined) return false;
    return true;
}

export function PricingFromJSON(json: any): Pricing {
    return PricingFromJSONTyped(json, false);
}

export function PricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pricing {
    if (json == null) {
        return json;
    }
    return {
        
        'gpuType': json['gpu_type'],
        'gpuCount': json['gpu_count'],
        'cpuCores': json['cpu_cores'] == null ? undefined : json['cpu_cores'],
        'ramGb': json['ram_gb'] == null ? undefined : json['ram_gb'],
        'storageGb': json['storage_gb'] == null ? undefined : json['storage_gb'],
        'region': json['region'],
        'tier': json['tier'],
        'pricePerHour': json['price_per_hour'],
        'available': json['available'],
        'instantBoot': json['instant_boot'],
        'community': json['community'],
        'instanceDiskGb': json['instance_disk_gb'] == null ? undefined : json['instance_disk_gb'],
        'diskConfigurable': json['disk_configurable'] == null ? undefined : json['disk_configurable'],
        'diskPricePerGbHour': json['disk_price_per_gb_hour'] == null ? undefined : json['disk_price_per_gb_hour'],
        'capacityClass': json['capacity_class'] == null ? undefined : json['capacity_class'],
    };
}

export function PricingToJSON(json: any): Pricing {
    return PricingToJSONTyped(json, false);
}

export function PricingToJSONTyped(value?: Pricing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gpu_type': value['gpuType'],
        'gpu_count': value['gpuCount'],
        'cpu_cores': value['cpuCores'],
        'ram_gb': value['ramGb'],
        'storage_gb': value['storageGb'],
        'region': value['region'],
        'tier': value['tier'],
        'price_per_hour': value['pricePerHour'],
        'available': value['available'],
        'instant_boot': value['instantBoot'],
        'community': value['community'],
        'instance_disk_gb': value['instanceDiskGb'],
        'disk_configurable': value['diskConfigurable'],
        'disk_price_per_gb_hour': value['diskPricePerGbHour'],
        'capacity_class': value['capacityClass'],
    };
}

