/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pricing } from './Pricing';
import {
    PricingFromJSON,
    PricingFromJSONTyped,
    PricingToJSON,
    PricingToJSONTyped,
} from './Pricing';

/**
 * 
 * @export
 * @interface PricingPage
 */
export interface PricingPage {
    /**
     * 
     * @type {Array<Pricing>}
     * @memberof PricingPage
     */
    data: Array<Pricing>;
    /**
     * 
     * @type {string}
     * @memberof PricingPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the PricingPage interface.
 */
export function instanceOfPricingPage(value: object): value is PricingPage {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function PricingPageFromJSON(json: any): PricingPage {
    return PricingPageFromJSONTyped(json, false);
}

export function PricingPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PricingFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function PricingPageToJSON(json: any): PricingPage {
    return PricingPageToJSONTyped(json, false);
}

export function PricingPageToJSONTyped(value?: PricingPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PricingToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

