/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Problem
 */
export interface Problem {
    /**
     * 
     * @type {string}
     * @memberof Problem
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof Problem
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof Problem
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof Problem
     */
    detail: string;
    /**
     * 
     * @type {ProblemCodeEnum}
     * @memberof Problem
     */
    code: ProblemCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof Problem
     */
    requestId: string;
}


/**
 * @export
 */
export const ProblemCodeEnum = {
    Unauthenticated: 'unauthenticated',
    InvalidApiKey: 'invalid_api_key',
    InsufficientScope: 'insufficient_scope',
    NotFound: 'not_found',
    IdempotencyConflict: 'idempotency_conflict',
    IdempotencyMismatch: 'idempotency_mismatch',
    ValidationFailed: 'validation_failed',
    InvalidGpuType: 'invalid_gpu_type',
    DiskUnavailable: 'disk_unavailable',
    ModelTooLarge: 'model_too_large',
    InsufficientBalance: 'insufficient_balance',
    QuotaExceeded: 'quota_exceeded',
    RateLimited: 'rate_limited',
    InternalError: 'internal_error',
    OperationFailed: 'operation_failed'
} as const;
export type ProblemCodeEnum = typeof ProblemCodeEnum[keyof typeof ProblemCodeEnum];


/**
 * Check if a given object implements the Problem interface.
 */
export function instanceOfProblem(value: object): value is Problem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    return true;
}

export function ProblemFromJSON(json: any): Problem {
    return ProblemFromJSONTyped(json, false);
}

export function ProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Problem {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'status': json['status'],
        'detail': json['detail'],
        'code': json['code'],
        'requestId': json['request_id'],
    };
}

export function ProblemToJSON(json: any): Problem {
    return ProblemToJSONTyped(json, false);
}

export function ProblemToJSONTyped(value?: Problem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'code': value['code'],
        'request_id': value['requestId'],
    };
}

