/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * All fields optional; an empty body registers a zero-spec placeholder in pending_verification.
 * @export
 * @interface RegisterCommunityMachineRequest
 */
export interface RegisterCommunityMachineRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterCommunityMachineRequest
     */
    gpuType?: string;
    /**
     * 
     * @type {number}
     * @memberof RegisterCommunityMachineRequest
     */
    gpuCount?: number;
    /**
     * 
     * @type {number}
     * @memberof RegisterCommunityMachineRequest
     */
    vramPerGpuGb?: number;
    /**
     * 
     * @type {number}
     * @memberof RegisterCommunityMachineRequest
     */
    pricePerHour?: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterCommunityMachineRequest
     */
    region?: string;
    /**
     * Supplier-chosen rental model. Optional; omitted resolves to on_demand. spot lists the machine as cheaper interruptible capacity.
     * @type {RegisterCommunityMachineRequestTierEnum}
     * @memberof RegisterCommunityMachineRequest
     */
    tier?: RegisterCommunityMachineRequestTierEnum;
}


/**
 * @export
 */
export const RegisterCommunityMachineRequestTierEnum = {
    OnDemand: 'on_demand',
    Spot: 'spot'
} as const;
export type RegisterCommunityMachineRequestTierEnum = typeof RegisterCommunityMachineRequestTierEnum[keyof typeof RegisterCommunityMachineRequestTierEnum];


/**
 * Check if a given object implements the RegisterCommunityMachineRequest interface.
 */
export function instanceOfRegisterCommunityMachineRequest(value: object): value is RegisterCommunityMachineRequest {
    return true;
}

export function RegisterCommunityMachineRequestFromJSON(json: any): RegisterCommunityMachineRequest {
    return RegisterCommunityMachineRequestFromJSONTyped(json, false);
}

export function RegisterCommunityMachineRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterCommunityMachineRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'gpuType': json['gpu_type'] == null ? undefined : json['gpu_type'],
        'gpuCount': json['gpu_count'] == null ? undefined : json['gpu_count'],
        'vramPerGpuGb': json['vram_per_gpu_gb'] == null ? undefined : json['vram_per_gpu_gb'],
        'pricePerHour': json['price_per_hour'] == null ? undefined : json['price_per_hour'],
        'region': json['region'] == null ? undefined : json['region'],
        'tier': json['tier'] == null ? undefined : json['tier'],
    };
}

export function RegisterCommunityMachineRequestToJSON(json: any): RegisterCommunityMachineRequest {
    return RegisterCommunityMachineRequestToJSONTyped(json, false);
}

export function RegisterCommunityMachineRequestToJSONTyped(value?: RegisterCommunityMachineRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gpu_type': value['gpuType'],
        'gpu_count': value['gpuCount'],
        'vram_per_gpu_gb': value['vramPerGpuGb'],
        'price_per_hour': value['pricePerHour'],
        'region': value['region'],
        'tier': value['tier'],
    };
}

