/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A stored private-registry login (metadata only — the password is write-only and encrypted at rest).
 * @export
 * @interface RegistryCredential
 */
export interface RegistryCredential {
    /**
     * 
     * @type {string}
     * @memberof RegistryCredential
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryCredential
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryCredential
     */
    registry?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryCredential
     */
    username?: string;
    /**
     * 
     * @type {Date}
     * @memberof RegistryCredential
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the RegistryCredential interface.
 */
export function instanceOfRegistryCredential(value: object): value is RegistryCredential {
    return true;
}

export function RegistryCredentialFromJSON(json: any): RegistryCredential {
    return RegistryCredentialFromJSONTyped(json, false);
}

export function RegistryCredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistryCredential {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'registry': json['registry'] == null ? undefined : json['registry'],
        'username': json['username'] == null ? undefined : json['username'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function RegistryCredentialToJSON(json: any): RegistryCredential {
    return RegistryCredentialToJSONTyped(json, false);
}

export function RegistryCredentialToJSONTyped(value?: RegistryCredential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'registry': value['registry'],
        'username': value['username'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

