/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpendingLimit
 */
export interface SpendingLimit {
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    monthlyLimitCents: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    monthlyLimitDollars: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    currentMonthSpendCents: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    currentMonthSpendDollars: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    percentUsed: number;
    /**
     * 
     * @type {Date}
     * @memberof SpendingLimit
     */
    billingCycleStart: Date;
    /**
     * 
     * @type {SpendingLimitEnforcementEnum}
     * @memberof SpendingLimit
     */
    enforcement: SpendingLimitEnforcementEnum;
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    autoTerminateHours?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    dailyLimitCents?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    dailyLimitDollars?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingLimit
     */
    currentDaySpendCents: number;
}


/**
 * @export
 */
export const SpendingLimitEnforcementEnum = {
    StopRunning: 'stop_running',
    BlockLaunch: 'block_launch',
    NotifyOnly: 'notify_only'
} as const;
export type SpendingLimitEnforcementEnum = typeof SpendingLimitEnforcementEnum[keyof typeof SpendingLimitEnforcementEnum];


/**
 * Check if a given object implements the SpendingLimit interface.
 */
export function instanceOfSpendingLimit(value: object): value is SpendingLimit {
    if ((!('monthlyLimitCents' in (value as Record<string, any>)) && !('monthly_limit_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['monthlyLimitCents'] === undefined && (value as Record<string, any>)['monthly_limit_cents'] === undefined)) return false;
    if ((!('monthlyLimitDollars' in (value as Record<string, any>)) && !('monthly_limit_dollars' in (value as Record<string, any>))) || ((value as Record<string, any>)['monthlyLimitDollars'] === undefined && (value as Record<string, any>)['monthly_limit_dollars'] === undefined)) return false;
    if ((!('currentMonthSpendCents' in (value as Record<string, any>)) && !('current_month_spend_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['currentMonthSpendCents'] === undefined && (value as Record<string, any>)['current_month_spend_cents'] === undefined)) return false;
    if ((!('currentMonthSpendDollars' in (value as Record<string, any>)) && !('current_month_spend_dollars' in (value as Record<string, any>))) || ((value as Record<string, any>)['currentMonthSpendDollars'] === undefined && (value as Record<string, any>)['current_month_spend_dollars'] === undefined)) return false;
    if ((!('percentUsed' in (value as Record<string, any>)) && !('percent_used' in (value as Record<string, any>))) || ((value as Record<string, any>)['percentUsed'] === undefined && (value as Record<string, any>)['percent_used'] === undefined)) return false;
    if ((!('billingCycleStart' in (value as Record<string, any>)) && !('billing_cycle_start' in (value as Record<string, any>))) || ((value as Record<string, any>)['billingCycleStart'] === undefined && (value as Record<string, any>)['billing_cycle_start'] === undefined)) return false;
    if (!('enforcement' in value) || value['enforcement'] === undefined) return false;
    if ((!('currentDaySpendCents' in (value as Record<string, any>)) && !('current_day_spend_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['currentDaySpendCents'] === undefined && (value as Record<string, any>)['current_day_spend_cents'] === undefined)) return false;
    return true;
}

export function SpendingLimitFromJSON(json: any): SpendingLimit {
    return SpendingLimitFromJSONTyped(json, false);
}

export function SpendingLimitFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpendingLimit {
    if (json == null) {
        return json;
    }
    return {
        
        'monthlyLimitCents': json['monthly_limit_cents'],
        'monthlyLimitDollars': json['monthly_limit_dollars'],
        'currentMonthSpendCents': json['current_month_spend_cents'],
        'currentMonthSpendDollars': json['current_month_spend_dollars'],
        'percentUsed': json['percent_used'],
        'billingCycleStart': (new Date(json['billing_cycle_start'])),
        'enforcement': json['enforcement'],
        'autoTerminateHours': json['auto_terminate_hours'] == null ? undefined : json['auto_terminate_hours'],
        'dailyLimitCents': json['daily_limit_cents'] == null ? undefined : json['daily_limit_cents'],
        'dailyLimitDollars': json['daily_limit_dollars'] == null ? undefined : json['daily_limit_dollars'],
        'currentDaySpendCents': json['current_day_spend_cents'],
    };
}

export function SpendingLimitToJSON(json: any): SpendingLimit {
    return SpendingLimitToJSONTyped(json, false);
}

export function SpendingLimitToJSONTyped(value?: SpendingLimit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'monthly_limit_cents': value['monthlyLimitCents'],
        'monthly_limit_dollars': value['monthlyLimitDollars'],
        'current_month_spend_cents': value['currentMonthSpendCents'],
        'current_month_spend_dollars': value['currentMonthSpendDollars'],
        'percent_used': value['percentUsed'],
        'billing_cycle_start': value['billingCycleStart'].toISOString(),
        'enforcement': value['enforcement'],
        'auto_terminate_hours': value['autoTerminateHours'],
        'daily_limit_cents': value['dailyLimitCents'],
        'daily_limit_dollars': value['dailyLimitDollars'],
        'current_day_spend_cents': value['currentDaySpendCents'],
    };
}

