/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SSHKey
 */
export interface SSHKey {
    /**
     * 
     * @type {string}
     * @memberof SSHKey
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SSHKey
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SSHKey
     */
    fingerprint: string;
    /**
     * 
     * @type {Date}
     * @memberof SSHKey
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the SSHKey interface.
 */
export function instanceOfSSHKey(value: object): value is SSHKey {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('fingerprint' in value) || value['fingerprint'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function SSHKeyFromJSON(json: any): SSHKey {
    return SSHKeyFromJSONTyped(json, false);
}

export function SSHKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SSHKey {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'fingerprint': json['fingerprint'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function SSHKeyToJSON(json: any): SSHKey {
    return SSHKeyToJSONTyped(json, false);
}

export function SSHKeyToJSONTyped(value?: SSHKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'fingerprint': value['fingerprint'],
        'created_at': value['createdAt'].toISOString(),
    };
}

