/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SSHKey } from './SSHKey';
import {
    SSHKeyFromJSON,
    SSHKeyFromJSONTyped,
    SSHKeyToJSON,
    SSHKeyToJSONTyped,
} from './SSHKey';

/**
 * 
 * @export
 * @interface SSHKeyPage
 */
export interface SSHKeyPage {
    /**
     * 
     * @type {Array<SSHKey>}
     * @memberof SSHKeyPage
     */
    data: Array<SSHKey>;
    /**
     * 
     * @type {string}
     * @memberof SSHKeyPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the SSHKeyPage interface.
 */
export function instanceOfSSHKeyPage(value: object): value is SSHKeyPage {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function SSHKeyPageFromJSON(json: any): SSHKeyPage {
    return SSHKeyPageFromJSONTyped(json, false);
}

export function SSHKeyPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SSHKeyPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SSHKeyFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function SSHKeyPageToJSON(json: any): SSHKeyPage {
    return SSHKeyPageToJSONTyped(json, false);
}

export function SSHKeyPageToJSONTyped(value?: SSHKeyPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(SSHKeyToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

