/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamOptions
 */
export interface StreamOptions {
    /**
     * When true, the final stream chunk carries usage totals (CHAT-03).
     * @type {boolean}
     * @memberof StreamOptions
     */
    includeUsage?: boolean;
}

/**
 * Check if a given object implements the StreamOptions interface.
 */
export function instanceOfStreamOptions(value: object): value is StreamOptions {
    return true;
}

export function StreamOptionsFromJSON(json: any): StreamOptions {
    return StreamOptionsFromJSONTyped(json, false);
}

export function StreamOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'includeUsage': json['include_usage'] == null ? undefined : json['include_usage'],
    };
}

export function StreamOptionsToJSON(json: any): StreamOptions {
    return StreamOptionsToJSONTyped(json, false);
}

export function StreamOptionsToJSONTyped(value?: StreamOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'include_usage': value['includeUsage'],
    };
}

