/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The supplier-facing projection of a community machine. `occupied` replaces the renting customer's instance id (never exposed to the supplier); `online` is the server-derived 60s-heartbeat liveness.
 * @export
 * @interface SupplierMachineView
 */
export interface SupplierMachineView {
    /**
     * 
     * @type {string}
     * @memberof SupplierMachineView
     */
    machineId: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierMachineView
     */
    gpuType?: string;
    /**
     * 
     * @type {number}
     * @memberof SupplierMachineView
     */
    gpuCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierMachineView
     */
    vramPerGpuGb?: number;
    /**
     * Whole-machine hourly rate (never per-GPU).
     * @type {number}
     * @memberof SupplierMachineView
     */
    pricePerHour?: number;
    /**
     * 
     * @type {string}
     * @memberof SupplierMachineView
     */
    region?: string;
    /**
     * 
     * @type {SupplierMachineViewTierEnum}
     * @memberof SupplierMachineView
     */
    tier: SupplierMachineViewTierEnum;
    /**
     * 
     * @type {SupplierMachineViewStatusEnum}
     * @memberof SupplierMachineView
     */
    status: SupplierMachineViewStatusEnum;
    /**
     * 
     * @type {SupplierMachineViewVerificationStatusEnum}
     * @memberof SupplierMachineView
     */
    verificationStatus: SupplierMachineViewVerificationStatusEnum;
    /**
     * Server-derived — heartbeated within the last 60 seconds.
     * @type {boolean}
     * @memberof SupplierMachineView
     */
    online: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SupplierMachineView
     */
    lastHeartbeatAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SupplierMachineView
     */
    firstHeartbeatAt?: Date;
    /**
     * A customer instance is currently renting this machine.
     * @type {boolean}
     * @memberof SupplierMachineView
     */
    occupied: boolean;
    /**
     * Server-computed 0–100; machines below the platform threshold are auto-delisted.
     * @type {number}
     * @memberof SupplierMachineView
     */
    reliabilityScore?: number;
    /**
     * 
     * @type {string}
     * @memberof SupplierMachineView
     */
    delistReason?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierMachineView
     */
    suspendReason?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierMachineView
     */
    agentVersion?: string;
    /**
     * 
     * @type {Date}
     * @memberof SupplierMachineView
     */
    createdAt: Date;
}


/**
 * @export
 */
export const SupplierMachineViewTierEnum = {
    OnDemand: 'on_demand',
    Spot: 'spot'
} as const;
export type SupplierMachineViewTierEnum = typeof SupplierMachineViewTierEnum[keyof typeof SupplierMachineViewTierEnum];

/**
 * @export
 */
export const SupplierMachineViewStatusEnum = {
    PendingVerification: 'pending_verification',
    Listed: 'listed',
    Delisted: 'delisted',
    Suspended: 'suspended',
    Draining: 'draining'
} as const;
export type SupplierMachineViewStatusEnum = typeof SupplierMachineViewStatusEnum[keyof typeof SupplierMachineViewStatusEnum];

/**
 * @export
 */
export const SupplierMachineViewVerificationStatusEnum = {
    Unverified: 'unverified',
    Verified: 'verified',
    Failed: 'failed'
} as const;
export type SupplierMachineViewVerificationStatusEnum = typeof SupplierMachineViewVerificationStatusEnum[keyof typeof SupplierMachineViewVerificationStatusEnum];


/**
 * Check if a given object implements the SupplierMachineView interface.
 */
export function instanceOfSupplierMachineView(value: object): value is SupplierMachineView {
    if ((!('machineId' in (value as Record<string, any>)) && !('machine_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['machineId'] === undefined && (value as Record<string, any>)['machine_id'] === undefined)) return false;
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('verificationStatus' in (value as Record<string, any>)) && !('verification_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['verificationStatus'] === undefined && (value as Record<string, any>)['verification_status'] === undefined)) return false;
    if (!('online' in value) || value['online'] === undefined) return false;
    if (!('occupied' in value) || value['occupied'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function SupplierMachineViewFromJSON(json: any): SupplierMachineView {
    return SupplierMachineViewFromJSONTyped(json, false);
}

export function SupplierMachineViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierMachineView {
    if (json == null) {
        return json;
    }
    return {
        
        'machineId': json['machine_id'],
        'gpuType': json['gpu_type'] == null ? undefined : json['gpu_type'],
        'gpuCount': json['gpu_count'] == null ? undefined : json['gpu_count'],
        'vramPerGpuGb': json['vram_per_gpu_gb'] == null ? undefined : json['vram_per_gpu_gb'],
        'pricePerHour': json['price_per_hour'] == null ? undefined : json['price_per_hour'],
        'region': json['region'] == null ? undefined : json['region'],
        'tier': json['tier'],
        'status': json['status'],
        'verificationStatus': json['verification_status'],
        'online': json['online'],
        'lastHeartbeatAt': json['last_heartbeat_at'] == null ? undefined : (new Date(json['last_heartbeat_at'])),
        'firstHeartbeatAt': json['first_heartbeat_at'] == null ? undefined : (new Date(json['first_heartbeat_at'])),
        'occupied': json['occupied'],
        'reliabilityScore': json['reliability_score'] == null ? undefined : json['reliability_score'],
        'delistReason': json['delist_reason'] == null ? undefined : json['delist_reason'],
        'suspendReason': json['suspend_reason'] == null ? undefined : json['suspend_reason'],
        'agentVersion': json['agent_version'] == null ? undefined : json['agent_version'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function SupplierMachineViewToJSON(json: any): SupplierMachineView {
    return SupplierMachineViewToJSONTyped(json, false);
}

export function SupplierMachineViewToJSONTyped(value?: SupplierMachineView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_id': value['machineId'],
        'gpu_type': value['gpuType'],
        'gpu_count': value['gpuCount'],
        'vram_per_gpu_gb': value['vramPerGpuGb'],
        'price_per_hour': value['pricePerHour'],
        'region': value['region'],
        'tier': value['tier'],
        'status': value['status'],
        'verification_status': value['verificationStatus'],
        'online': value['online'],
        'last_heartbeat_at': value['lastHeartbeatAt'] == null ? value['lastHeartbeatAt'] : value['lastHeartbeatAt'].toISOString(),
        'first_heartbeat_at': value['firstHeartbeatAt'] == null ? value['firstHeartbeatAt'] : value['firstHeartbeatAt'].toISOString(),
        'occupied': value['occupied'],
        'reliability_score': value['reliabilityScore'],
        'delist_reason': value['delistReason'],
        'suspend_reason': value['suspendReason'],
        'agent_version': value['agentVersion'],
        'created_at': value['createdAt'].toISOString(),
    };
}

