/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateEnvInner
 */
export interface TemplateEnvInner {
    /**
     * 
     * @type {string}
     * @memberof TemplateEnvInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateEnvInner
     */
    _default?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TemplateEnvInner
     */
    userOverridable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TemplateEnvInner
     */
    secret?: boolean;
}

/**
 * Check if a given object implements the TemplateEnvInner interface.
 */
export function instanceOfTemplateEnvInner(value: object): value is TemplateEnvInner {
    return true;
}

export function TemplateEnvInnerFromJSON(json: any): TemplateEnvInner {
    return TemplateEnvInnerFromJSONTyped(json, false);
}

export function TemplateEnvInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateEnvInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        '_default': json['default'] == null ? undefined : json['default'],
        'userOverridable': json['user_overridable'] == null ? undefined : json['user_overridable'],
        'secret': json['secret'] == null ? undefined : json['secret'],
    };
}

export function TemplateEnvInnerToJSON(json: any): TemplateEnvInner {
    return TemplateEnvInnerToJSONTyped(json, false);
}

export function TemplateEnvInnerToJSONTyped(value?: TemplateEnvInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'default': value['_default'],
        'user_overridable': value['userOverridable'],
        'secret': value['secret'],
    };
}

