/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateEnvInner } from './TemplateEnvInner';
import {
    TemplateEnvInnerFromJSON,
    TemplateEnvInnerFromJSONTyped,
    TemplateEnvInnerToJSON,
    TemplateEnvInnerToJSONTyped,
} from './TemplateEnvInner';
import type { TemplatePortsInner } from './TemplatePortsInner';
import {
    TemplatePortsInnerFromJSON,
    TemplatePortsInnerFromJSONTyped,
    TemplatePortsInnerToJSON,
    TemplatePortsInnerToJSONTyped,
} from './TemplatePortsInner';

/**
 * A deployable application template. The container image (registry path) and start command are internal orchestration details and are intentionally absent from this schema (TMPL-13 defense-by-omission).
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    category: string;
    /**
     * Deployable kind. "service" is a long-running app exposed at connection.app_url. "finetuning" is a run-to-completion job (no app_url) and is currently advertised only as a coming-soon catalog entry — not yet deployable.
     * @type {TemplateKindEnum}
     * @memberof Template
     */
    kind: TemplateKindEnum;
    /**
     * 
     * @type {TemplateStatusEnum}
     * @memberof Template
     */
    status?: TemplateStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    containerDiskGb?: number;
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    minVramGb?: number;
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    minGpuCount?: number;
    /**
     * 
     * @type {Array<TemplatePortsInner>}
     * @memberof Template
     */
    ports: Array<TemplatePortsInner>;
    /**
     * 
     * @type {Array<TemplateEnvInner>}
     * @memberof Template
     */
    env?: Array<TemplateEnvInner>;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    docsUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Template
     */
    includes?: Array<string>;
}


/**
 * @export
 */
export const TemplateKindEnum = {
    Service: 'service',
    Finetuning: 'finetuning'
} as const;
export type TemplateKindEnum = typeof TemplateKindEnum[keyof typeof TemplateKindEnum];

/**
 * @export
 */
export const TemplateStatusEnum = {
    ComingSoon: 'coming_soon'
} as const;
export type TemplateStatusEnum = typeof TemplateStatusEnum[keyof typeof TemplateStatusEnum];


/**
 * Check if a given object implements the Template interface.
 */
export function instanceOfTemplate(value: object): value is Template {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('displayName' in (value as Record<string, any>)) && !('display_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['displayName'] === undefined && (value as Record<string, any>)['display_name'] === undefined)) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('ports' in value) || value['ports'] === undefined) return false;
    return true;
}

export function TemplateFromJSON(json: any): Template {
    return TemplateFromJSONTyped(json, false);
}

export function TemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Template {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['display_name'],
        'category': json['category'],
        'kind': json['kind'],
        'status': json['status'] == null ? undefined : json['status'],
        'containerDiskGb': json['container_disk_gb'] == null ? undefined : json['container_disk_gb'],
        'minVramGb': json['min_vram_gb'] == null ? undefined : json['min_vram_gb'],
        'minGpuCount': json['min_gpu_count'] == null ? undefined : json['min_gpu_count'],
        'ports': ((json['ports'] as Array<any>).map(TemplatePortsInnerFromJSON)),
        'env': json['env'] == null ? undefined : ((json['env'] as Array<any>).map(TemplateEnvInnerFromJSON)),
        'docsUrl': json['docs_url'] == null ? undefined : json['docs_url'],
        'description': json['description'] == null ? undefined : json['description'],
        'includes': json['includes'] == null ? undefined : json['includes'],
    };
}

export function TemplateToJSON(json: any): Template {
    return TemplateToJSONTyped(json, false);
}

export function TemplateToJSONTyped(value?: Template | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'display_name': value['displayName'],
        'category': value['category'],
        'kind': value['kind'],
        'status': value['status'],
        'container_disk_gb': value['containerDiskGb'],
        'min_vram_gb': value['minVramGb'],
        'min_gpu_count': value['minGpuCount'],
        'ports': ((value['ports'] as Array<any>).map(TemplatePortsInnerToJSON)),
        'env': value['env'] == null ? undefined : ((value['env'] as Array<any>).map(TemplateEnvInnerToJSON)),
        'docs_url': value['docsUrl'],
        'description': value['description'],
        'includes': value['includes'],
    };
}

