/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Template } from './Template';
import {
    TemplateFromJSON,
    TemplateFromJSONTyped,
    TemplateToJSON,
    TemplateToJSONTyped,
} from './Template';

/**
 * 
 * @export
 * @interface TemplateList
 */
export interface TemplateList {
    /**
     * 
     * @type {TemplateListObjectEnum}
     * @memberof TemplateList
     */
    object: TemplateListObjectEnum;
    /**
     * 
     * @type {Array<Template>}
     * @memberof TemplateList
     */
    data: Array<Template>;
}


/**
 * @export
 */
export const TemplateListObjectEnum = {
    List: 'list'
} as const;
export type TemplateListObjectEnum = typeof TemplateListObjectEnum[keyof typeof TemplateListObjectEnum];


/**
 * Check if a given object implements the TemplateList interface.
 */
export function instanceOfTemplateList(value: object): value is TemplateList {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'list') return false;
    
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TemplateListFromJSON(json: any): TemplateList {
    return TemplateListFromJSONTyped(json, false);
}

export function TemplateListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateList {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(TemplateFromJSON)),
    };
}

export function TemplateListToJSON(json: any): TemplateList {
    return TemplateListToJSONTyped(json, false);
}

export function TemplateListToJSONTyped(value?: TemplateList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(TemplateToJSON)),
    };
}

