/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatePortsInner
 */
export interface TemplatePortsInner {
    /**
     * 
     * @type {number}
     * @memberof TemplatePortsInner
     */
    port?: number;
    /**
     * 
     * @type {TemplatePortsInnerProtocolEnum}
     * @memberof TemplatePortsInner
     */
    protocol?: TemplatePortsInnerProtocolEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TemplatePortsInner
     */
    primary?: boolean;
}


/**
 * @export
 */
export const TemplatePortsInnerProtocolEnum = {
    Http: 'http',
    Tcp: 'tcp'
} as const;
export type TemplatePortsInnerProtocolEnum = typeof TemplatePortsInnerProtocolEnum[keyof typeof TemplatePortsInnerProtocolEnum];


/**
 * Check if a given object implements the TemplatePortsInner interface.
 */
export function instanceOfTemplatePortsInner(value: object): value is TemplatePortsInner {
    return true;
}

export function TemplatePortsInnerFromJSON(json: any): TemplatePortsInner {
    return TemplatePortsInnerFromJSONTyped(json, false);
}

export function TemplatePortsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatePortsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'port': json['port'] == null ? undefined : json['port'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
        'primary': json['primary'] == null ? undefined : json['primary'],
    };
}

export function TemplatePortsInnerToJSON(json: any): TemplatePortsInner {
    return TemplatePortsInnerToJSONTyped(json, false);
}

export function TemplatePortsInnerToJSONTyped(value?: TemplatePortsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'port': value['port'],
        'protocol': value['protocol'],
        'primary': value['primary'],
    };
}

