/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateInstanceRequest
 */
export interface UpdateInstanceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateInstanceRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateInstanceRequest interface.
 */
export function instanceOfUpdateInstanceRequest(value: object): value is UpdateInstanceRequest {
    return true;
}

export function UpdateInstanceRequestFromJSON(json: any): UpdateInstanceRequest {
    return UpdateInstanceRequestFromJSONTyped(json, false);
}

export function UpdateInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateInstanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateInstanceRequestToJSON(json: any): UpdateInstanceRequest {
    return UpdateInstanceRequestToJSONTyped(json, false);
}

export function UpdateInstanceRequestToJSONTyped(value?: UpdateInstanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

