/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSpendingLimitRequest
 */
export interface UpdateSpendingLimitRequest {
    /**
     * Monthly limit in USD (minimum 1.00).
     * @type {number}
     * @memberof UpdateSpendingLimitRequest
     */
    monthlyLimitDollars: number;
    /**
     * 
     * @type {UpdateSpendingLimitRequestEnforcementEnum}
     * @memberof UpdateSpendingLimitRequest
     */
    enforcement?: UpdateSpendingLimitRequestEnforcementEnum;
    /**
     * Hours after the limit is reached before auto-terminate; null = never.
     * @type {number}
     * @memberof UpdateSpendingLimitRequest
     */
    autoTerminateHours?: number;
    /**
     * Opt-in daily cap in USD. Omit = unchanged, 0 = clear, > 0 = set.
     * @type {number}
     * @memberof UpdateSpendingLimitRequest
     */
    dailyLimitDollars?: number;
}


/**
 * @export
 */
export const UpdateSpendingLimitRequestEnforcementEnum = {
    StopRunning: 'stop_running',
    BlockLaunch: 'block_launch',
    NotifyOnly: 'notify_only'
} as const;
export type UpdateSpendingLimitRequestEnforcementEnum = typeof UpdateSpendingLimitRequestEnforcementEnum[keyof typeof UpdateSpendingLimitRequestEnforcementEnum];


/**
 * Check if a given object implements the UpdateSpendingLimitRequest interface.
 */
export function instanceOfUpdateSpendingLimitRequest(value: object): value is UpdateSpendingLimitRequest {
    if ((!('monthlyLimitDollars' in (value as Record<string, any>)) && !('monthly_limit_dollars' in (value as Record<string, any>))) || ((value as Record<string, any>)['monthlyLimitDollars'] === undefined && (value as Record<string, any>)['monthly_limit_dollars'] === undefined)) return false;
    return true;
}

export function UpdateSpendingLimitRequestFromJSON(json: any): UpdateSpendingLimitRequest {
    return UpdateSpendingLimitRequestFromJSONTyped(json, false);
}

export function UpdateSpendingLimitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSpendingLimitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'monthlyLimitDollars': json['monthly_limit_dollars'],
        'enforcement': json['enforcement'] == null ? undefined : json['enforcement'],
        'autoTerminateHours': json['auto_terminate_hours'] == null ? undefined : json['auto_terminate_hours'],
        'dailyLimitDollars': json['daily_limit_dollars'] == null ? undefined : json['daily_limit_dollars'],
    };
}

export function UpdateSpendingLimitRequestToJSON(json: any): UpdateSpendingLimitRequest {
    return UpdateSpendingLimitRequestToJSONTyped(json, false);
}

export function UpdateSpendingLimitRequestToJSONTyped(value?: UpdateSpendingLimitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'monthly_limit_dollars': value['monthlyLimitDollars'],
        'enforcement': value['enforcement'],
        'auto_terminate_hours': value['autoTerminateHours'],
        'daily_limit_dollars': value['dailyLimitDollars'],
    };
}

