/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCommunityMachineRequest
 */
export interface UpdateCommunityMachineRequest {
    /**
     * Whole-machine hourly rate (never per-GPU). Must clear the platform floor; a below-floor price is rejected with `price-below-floor` carrying the concrete `floor_per_hour`.
     * @type {number}
     * @memberof UpdateCommunityMachineRequest
     */
    pricePerHour: number;
}

/**
 * Check if a given object implements the UpdateCommunityMachineRequest interface.
 */
export function instanceOfUpdateCommunityMachineRequest(value: object): value is UpdateCommunityMachineRequest {
    if ((!('pricePerHour' in (value as Record<string, any>)) && !('price_per_hour' in (value as Record<string, any>))) || ((value as Record<string, any>)['pricePerHour'] === undefined && (value as Record<string, any>)['price_per_hour'] === undefined)) return false;
    return true;
}

export function UpdateCommunityMachineRequestFromJSON(json: any): UpdateCommunityMachineRequest {
    return UpdateCommunityMachineRequestFromJSONTyped(json, false);
}

export function UpdateCommunityMachineRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCommunityMachineRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pricePerHour': json['price_per_hour'],
    };
}

export function UpdateCommunityMachineRequestToJSON(json: any): UpdateCommunityMachineRequest {
    return UpdateCommunityMachineRequestToJSONTyped(json, false);
}

export function UpdateCommunityMachineRequestToJSONTyped(value?: UpdateCommunityMachineRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price_per_hour': value['pricePerHour'],
    };
}

