/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsageBucket } from './UsageBucket';
import {
    UsageBucketFromJSON,
    UsageBucketFromJSONTyped,
    UsageBucketToJSON,
    UsageBucketToJSONTyped,
} from './UsageBucket';

/**
 * 
 * @export
 * @interface UsagePage
 */
export interface UsagePage {
    /**
     * 
     * @type {Array<UsageBucket>}
     * @memberof UsagePage
     */
    data: Array<UsageBucket>;
    /**
     * 
     * @type {string}
     * @memberof UsagePage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the UsagePage interface.
 */
export function instanceOfUsagePage(value: object): value is UsagePage {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function UsagePageFromJSON(json: any): UsagePage {
    return UsagePageFromJSONTyped(json, false);
}

export function UsagePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsagePage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UsageBucketFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function UsagePageToJSON(json: any): UsagePage {
    return UsagePageToJSONTyped(json, false);
}

export function UsagePageToJSONTyped(value?: UsagePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UsageBucketToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

