/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageBucket
 */
export interface UsageBucket {
    /**
     * 
     * @type {Date}
     * @memberof UsageBucket
     */
    bucketStart: Date;
    /**
     * 
     * @type {string}
     * @memberof UsageBucket
     */
    instanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof UsageBucket
     */
    gpuType?: string;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    gpuSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    costCents: number;
}

/**
 * Check if a given object implements the UsageBucket interface.
 */
export function instanceOfUsageBucket(value: object): value is UsageBucket {
    if ((!('bucketStart' in (value as Record<string, any>)) && !('bucket_start' in (value as Record<string, any>))) || ((value as Record<string, any>)['bucketStart'] === undefined && (value as Record<string, any>)['bucket_start'] === undefined)) return false;
    if ((!('gpuSeconds' in (value as Record<string, any>)) && !('gpu_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuSeconds'] === undefined && (value as Record<string, any>)['gpu_seconds'] === undefined)) return false;
    if ((!('costCents' in (value as Record<string, any>)) && !('cost_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['costCents'] === undefined && (value as Record<string, any>)['cost_cents'] === undefined)) return false;
    return true;
}

export function UsageBucketFromJSON(json: any): UsageBucket {
    return UsageBucketFromJSONTyped(json, false);
}

export function UsageBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'bucketStart': (new Date(json['bucket_start'])),
        'instanceId': json['instance_id'] == null ? undefined : json['instance_id'],
        'gpuType': json['gpu_type'] == null ? undefined : json['gpu_type'],
        'gpuSeconds': json['gpu_seconds'],
        'costCents': json['cost_cents'],
    };
}

export function UsageBucketToJSON(json: any): UsageBucket {
    return UsageBucketToJSONTyped(json, false);
}

export function UsageBucketToJSONTyped(value?: UsageBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket_start': value['bucketStart'].toISOString(),
        'instance_id': value['instanceId'],
        'gpu_type': value['gpuType'],
        'gpu_seconds': value['gpuSeconds'],
        'cost_cents': value['costCents'],
    };
}

