/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoJob
 */
export interface VideoJob {
    /**
     * 
     * @type {string}
     * @memberof VideoJob
     */
    id: string;
    /**
     * 
     * @type {VideoJobObjectEnum}
     * @memberof VideoJob
     */
    object: VideoJobObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof VideoJob
     */
    model: string;
    /**
     * 
     * @type {VideoJobStatusEnum}
     * @memberof VideoJob
     */
    status: VideoJobStatusEnum;
    /**
     * Generation progress 0-100.
     * @type {number}
     * @memberof VideoJob
     */
    progress: number;
    /**
     * 
     * @type {string}
     * @memberof VideoJob
     */
    size?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoJob
     */
    seconds?: number;
    /**
     * Unix timestamp (seconds) when the job was created.
     * @type {number}
     * @memberof VideoJob
     */
    createdAt: number;
    /**
     * Unix timestamp (seconds) when the job completed.
     * @type {number}
     * @memberof VideoJob
     */
    completedAt?: number;
    /**
     * Unix timestamp (seconds) when the artifact expires (24h after completion).
     * @type {number}
     * @memberof VideoJob
     */
    expiresAt?: number;
    /**
     * Canonical failure code when status is failed.
     * @type {string}
     * @memberof VideoJob
     */
    error?: string;
    /**
     * Final billed cost in cents; present once the job completes (failed/cancelled jobs are never billed).
     * @type {number}
     * @memberof VideoJob
     */
    costCents?: number;
}


/**
 * @export
 */
export const VideoJobObjectEnum = {
    Video: 'video'
} as const;
export type VideoJobObjectEnum = typeof VideoJobObjectEnum[keyof typeof VideoJobObjectEnum];

/**
 * @export
 */
export const VideoJobStatusEnum = {
    Queued: 'queued',
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled',
    Expired: 'expired'
} as const;
export type VideoJobStatusEnum = typeof VideoJobStatusEnum[keyof typeof VideoJobStatusEnum];


/**
 * Check if a given object implements the VideoJob interface.
 */
export function instanceOfVideoJob(value: object): value is VideoJob {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'video') return false;
    
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function VideoJobFromJSON(json: any): VideoJob {
    return VideoJobFromJSONTyped(json, false);
}

export function VideoJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'model': json['model'],
        'status': json['status'],
        'progress': json['progress'],
        'size': json['size'] == null ? undefined : json['size'],
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
        'createdAt': json['created_at'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'error': json['error'] == null ? undefined : json['error'],
        'costCents': json['cost_cents'] == null ? undefined : json['cost_cents'],
    };
}

export function VideoJobToJSON(json: any): VideoJob {
    return VideoJobToJSONTyped(json, false);
}

export function VideoJobToJSONTyped(value?: VideoJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'model': value['model'],
        'status': value['status'],
        'progress': value['progress'],
        'size': value['size'],
        'seconds': value['seconds'],
        'created_at': value['createdAt'],
        'completed_at': value['completedAt'],
        'expires_at': value['expiresAt'],
        'error': value['error'],
        'cost_cents': value['costCents'],
    };
}

