/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoJob } from './VideoJob';
import {
    VideoJobFromJSON,
    VideoJobFromJSONTyped,
    VideoJobToJSON,
    VideoJobToJSONTyped,
} from './VideoJob';

/**
 * 
 * @export
 * @interface VideoList
 */
export interface VideoList {
    /**
     * 
     * @type {VideoListObjectEnum}
     * @memberof VideoList
     */
    object: VideoListObjectEnum;
    /**
     * 
     * @type {Array<VideoJob>}
     * @memberof VideoList
     */
    data: Array<VideoJob>;
    /**
     * 
     * @type {boolean}
     * @memberof VideoList
     */
    hasMore: boolean;
}


/**
 * @export
 */
export const VideoListObjectEnum = {
    List: 'list'
} as const;
export type VideoListObjectEnum = typeof VideoListObjectEnum[keyof typeof VideoListObjectEnum];


/**
 * Check if a given object implements the VideoList interface.
 */
export function instanceOfVideoList(value: object): value is VideoList {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (value['object'] !== 'list') return false;
    
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('hasMore' in (value as Record<string, any>)) && !('has_more' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasMore'] === undefined && (value as Record<string, any>)['has_more'] === undefined)) return false;
    return true;
}

export function VideoListFromJSON(json: any): VideoList {
    return VideoListFromJSONTyped(json, false);
}

export function VideoListFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoList {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(VideoJobFromJSON)),
        'hasMore': json['has_more'],
    };
}

export function VideoListToJSON(json: any): VideoList {
    return VideoListToJSONTyped(json, false);
}

export function VideoListToJSONTyped(value?: VideoList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(VideoJobToJSON)),
        'has_more': value['hasMore'],
    };
}

