/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoCreateRequest
 */
export interface VideoCreateRequest {
    /**
     * Customer-facing video model id (e.g. gpuai/wan-2.2-t2v) or alias.
     * @type {string}
     * @memberof VideoCreateRequest
     */
    model: string;
    /**
     * Text description of the video to generate.
     * @type {string}
     * @memberof VideoCreateRequest
     */
    prompt: string;
    /**
     * Output video dimensions as WxH (e.g. 1280x720).
     * @type {string}
     * @memberof VideoCreateRequest
     */
    size?: string;
    /**
     * Output video duration in seconds (the billable unit).
     * @type {number}
     * @memberof VideoCreateRequest
     */
    seconds?: number;
}

/**
 * Check if a given object implements the VideoCreateRequest interface.
 */
export function instanceOfVideoCreateRequest(value: object): value is VideoCreateRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function VideoCreateRequestFromJSON(json: any): VideoCreateRequest {
    return VideoCreateRequestFromJSONTyped(json, false);
}

export function VideoCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'prompt': json['prompt'],
        'size': json['size'] == null ? undefined : json['size'],
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
    };
}

export function VideoCreateRequestToJSON(json: any): VideoCreateRequest {
    return VideoCreateRequestToJSONTyped(json, false);
}

export function VideoCreateRequestToJSONTyped(value?: VideoCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'prompt': value['prompt'],
        'size': value['size'],
        'seconds': value['seconds'],
    };
}

