/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMImage
 */
export interface VMImage {
    /**
     * 
     * @type {string}
     * @memberof VMImage
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof VMImage
     */
    family: string;
    /**
     * 
     * @type {string}
     * @memberof VMImage
     */
    version: string;
    /**
     * true when the image ships the NVIDIA driver + CUDA baked in.
     * @type {boolean}
     * @memberof VMImage
     */
    driverPreinstalled?: boolean;
}

/**
 * Check if a given object implements the VMImage interface.
 */
export function instanceOfVMImage(value: object): value is VMImage {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('family' in value) || value['family'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function VMImageFromJSON(json: any): VMImage {
    return VMImageFromJSONTyped(json, false);
}

export function VMImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMImage {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'family': json['family'],
        'version': json['version'],
        'driverPreinstalled': json['driver_preinstalled'] == null ? undefined : json['driver_preinstalled'],
    };
}

export function VMImageToJSON(json: any): VMImage {
    return VMImageToJSONTyped(json, false);
}

export function VMImageToJSONTyped(value?: VMImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'family': value['family'],
        'version': value['version'],
        'driver_preinstalled': value['driverPreinstalled'],
    };
}

