/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEndpoint } from './WebhookEndpoint';
import {
    WebhookEndpointFromJSON,
    WebhookEndpointFromJSONTyped,
    WebhookEndpointToJSON,
    WebhookEndpointToJSONTyped,
} from './WebhookEndpoint';

/**
 * 
 * @export
 * @interface WebhookEndpointPage
 */
export interface WebhookEndpointPage {
    /**
     * 
     * @type {Array<WebhookEndpoint>}
     * @memberof WebhookEndpointPage
     */
    data: Array<WebhookEndpoint>;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the WebhookEndpointPage interface.
 */
export function instanceOfWebhookEndpointPage(value: object): value is WebhookEndpointPage {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function WebhookEndpointPageFromJSON(json: any): WebhookEndpointPage {
    return WebhookEndpointPageFromJSONTyped(json, false);
}

export function WebhookEndpointPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WebhookEndpointFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function WebhookEndpointPageToJSON(json: any): WebhookEndpointPage {
    return WebhookEndpointPageToJSONTyped(json, false);
}

export function WebhookEndpointPageToJSONTyped(value?: WebhookEndpointPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(WebhookEndpointToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

