/* tslint:disable */
/* eslint-disable */
/**
 * GPU.ai Public Developer API
 * Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@gpu.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEndpoint
 */
export interface WebhookEndpoint {
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpoint
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpoint
     */
    url: string;
    /**
     * Returned ONLY at creation; subsequent reads omit.
     * @type {string}
     * @memberof WebhookEndpoint
     */
    secret?: string;
    /**
     * 
     * @type {Array<WebhookEndpointEventTypesEnum>}
     * @memberof WebhookEndpoint
     */
    eventTypes: Array<WebhookEndpointEventTypesEnum>;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookEndpoint
     */
    enabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof WebhookEndpoint
     */
    createdAt: Date;
}


/**
 * @export
 */
export const WebhookEndpointEventTypesEnum = {
    InstanceCreating: 'instance.creating',
    InstanceRunning: 'instance.running',
    InstanceTerminated: 'instance.terminated',
    InstanceFailed: 'instance.failed',
    VideoCompleted: 'video.completed',
    VideoFailed: 'video.failed'
} as const;
export type WebhookEndpointEventTypesEnum = typeof WebhookEndpointEventTypesEnum[keyof typeof WebhookEndpointEventTypesEnum];


/**
 * Check if a given object implements the WebhookEndpoint interface.
 */
export function instanceOfWebhookEndpoint(value: object): value is WebhookEndpoint {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if ((!('eventTypes' in (value as Record<string, any>)) && !('event_types' in (value as Record<string, any>))) || ((value as Record<string, any>)['eventTypes'] === undefined && (value as Record<string, any>)['event_types'] === undefined)) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function WebhookEndpointFromJSON(json: any): WebhookEndpoint {
    return WebhookEndpointFromJSONTyped(json, false);
}

export function WebhookEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'eventTypes': json['event_types'],
        'enabled': json['enabled'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function WebhookEndpointToJSON(json: any): WebhookEndpoint {
    return WebhookEndpointToJSONTyped(json, false);
}

export function WebhookEndpointToJSONTyped(value?: WebhookEndpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'secret': value['secret'],
        'event_types': value['eventTypes'],
        'enabled': value['enabled'],
        'created_at': value['createdAt'].toISOString(),
    };
}

